// Generated by tools/placeholder_art/generate.py from placeholder_art/backdrops.py.
// Do not edit.
#pragma once
// What a conversation between maps is drawn against: an ordered run of flat
// horizontal bands, top to bottom, in master palette entries. No pixels, so a
// backdrop costs no tile, no TMEM and no VRAM on any client: the same picture
// as CI4 texels would be 38,400 bytes against the Nintendo 64's 2,048 usable.
// Presentation only: no rule reads it, it never enters canonical state, and a
// scene that names none is drawn exactly as it was before this menu existed.
inline constexpr int grandleon_backdrop_count = 7;
inline constexpr const char* grandleon_backdrop_names[] = {"throne_hall","night_camp","deep_wood","mountain_dusk","open_sea","star_field","crypt"};
// The rows a backdrop divides a scene into: the coarsest grid any client
// lays a scene out on, which every client scales to its own height.
inline constexpr int grandleon_backdrop_rows = 28;
// How many bands each backdrop actually names, of the 6 the widest one does.
inline constexpr int grandleon_backdrop_band_count[7] = {6,6,6,6,5,5,6};
// Per backdrop, per band: the first row, the row count, and the colour, as
// red, green and blue. Bands past the backdrop's own count are zeroes.
inline constexpr unsigned char grandleon_backdrop_bands[7][6][5] = {
{{0,5,16,19,24},{5,6,91,81,69},{11,2,74,52,33},{13,9,64,56,47},{22,4,92,66,39},{26,2,102,73,46}},{{0,7,16,19,24},{7,5,35,42,51},{12,4,20,54,31},{16,5,59,68,35},{21,5,82,96,47},{26,2,78,51,15}},{{0,8,20,54,31},{8,5,28,74,42},{13,4,39,97,58},{17,5,59,68,35},{22,4,60,42,28},{26,2,94,74,44}},{{0,6,44,27,69},{6,4,70,42,110},{10,4,74,53,67},{14,5,91,81,69},{19,5,64,56,47},{24,4,23,58,58}},{{0,6,15,51,80},{6,4,23,84,122},{10,6,18,56,79},{16,7,27,86,111},{23,5,74,52,33},{0,0,0,0,0}},{{0,9,16,19,24},{9,4,44,27,69},{13,5,35,42,51},{18,6,74,85,96},{24,4,15,51,80},{0,0,0,0,0}},{{0,6,16,19,24},{6,5,43,31,38},{11,6,64,56,47},{17,4,58,56,48},{21,4,74,53,67},{25,3,42,34,30}}};
