// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[152] = {-13,-4,0,4,-5,5,0,0,4,13,0,4,-5,5,0,0,-12,-5,4,24,-4,4,0,1,5,12,4,24,-4,4,0,1,-12,-4,23,37,-4,4,0,1,4,12,23,37,-4,4,0,1,-24,-10,5,47,-11,-7,1,3,-13,13,36,43,-5,5,1,1,13,17,42,55,-4,4,0,1,-17,-13,43,58,-4,4,0,1,-13,13,42,61,-5,5,1,1,12,26,48,52,-7,-2,0,2,24,30,47,54,-8,-2,0,3,-9,9,46,59,-7,-5,0,1,-19,-11,58,65,-5,5,1,2,11,19,58,65,-5,5,1,2,-6,6,60,64,-3,3,0,0,-9,9,62,77,-5,5,0,1,-9,9,66,70,-7,-5,0,3};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,4,-4,4,0,0,3,11,0,4,-4,4,0,0,-10,-4,4,24,-3,3,0,1,4,10,4,24,-3,3,0,1,-10,-3,23,38,-4,4,0,0,3,10,23,38,-4,4,0,0,-24,-18,19,42,-11,-9,0,1,-11,11,37,61,-4,4,1,3,-16,-11,42,57,-4,4,1,1,-24,2,42,46,-11,-9,0,1,11,16,44,60,-4,4,1,1,-2,27,46,50,-11,-9,0,2,26,32,44,52,-13,-8,0,3,-6,6,60,70,-4,4,0,2,-8,8,64,75,-4,5,1,2,0,8,66,70,-6,-4,0,3,-4,4,71,81,-1,6,1,2};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-8,8,0,9,-5,5,0,3,-6,6,8,19,-3,3,0,2,-11,11,17,33,-6,6,1,1,-17,17,32,51,-7,7,1,2,-24,-18,36,44,-6,0,0,2,18,24,36,44,-6,0,0,2,-18,-10,41,52,-3,3,1,2,10,18,41,52,-3,3,1,2,-14,14,49,68,-6,6,1,3,-6,6,57,63,-8,-6,0,3,-10,10,63,76,-5,5,0,1,-10,10,71,76,-6,2,0,3,-3,3,76,88,-2,2,0,0,-8,8,87,98,-3,3,0,3,-4,4,93,101,-2,2,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-14,14,0,15,-7,7,1,0,-16,16,3,48,6,12,1,1,-12,12,13,38,-6,6,1,2,-14,14,32,39,-12,-6,0,2,-9,9,33,37,-13,-12,0,3,-10,10,36,58,-6,6,1,3,-16,-10,36,54,-9,-3,1,1,10,16,36,54,-9,-3,1,1,-29,-19,46,55,-7,1,0,3,19,29,46,55,-7,1,0,3,-8,8,57,70,-5,5,0,1,-8,8,61,65,-7,-6,0,3,-30,-20,70,78,-3,6,0,2,20,30,70,78,-3,6,0,2,-12,12,73,78,-3,3,1,3,-11,-7,77,90,-2,2,0,2,7,11,77,90,-2,2,0,2,-2,2,77,93,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-11,-3,0,4,-5,5,0,0,3,11,0,4,-5,5,0,0,-10,-4,4,26,-4,4,0,3,4,10,4,26,-4,4,0,3,-13,13,25,46,-7,7,0,3,-6,6,25,46,-8,-7,1,3,-19,-15,47,65,-4,4,0,3,-15,15,44,71,-8,8,0,3,15,19,50,69,-4,4,0,3,-6,6,44,71,-10,-8,1,3,-15,15,68,73,-7,2,1,2,-7,7,71,82,-4,4,0,2,16,22,63,88,-4,-1,0,1,-8,8,73,78,-6,-4,0,0,-8,8,79,83,-5,1,1,2,10,26,88,94,-6,-1,0,3,16,22,88,94,-12,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[192] = {-11,-3,0,4,-5,5,0,0,3,11,0,4,-5,5,0,0,-10,-4,4,26,-4,4,0,1,4,10,4,26,-4,4,0,1,-15,15,3,61,6,11,1,1,-10,-3,25,42,-5,5,0,2,3,10,25,42,-5,5,0,2,17,29,36,40,1,8,0,2,20,26,0,79,3,7,0,2,-12,12,40,52,-6,6,1,2,-17,-12,50,65,-4,4,0,2,12,17,50,65,-4,4,0,2,-12,12,50,70,-7,7,1,3,-22,-15,54,60,-8,-3,0,1,-8,8,56,60,-8,-7,0,3,-24,-18,56,63,-10,-4,0,3,26,30,64,78,0,11,1,3,-19,-11,65,74,-6,6,1,2,11,19,65,74,-6,6,1,2,-9,9,71,82,-6,6,0,2,-9,9,74,78,-8,-6,0,0,21,25,77,89,3,7,0,3,-9,9,79,84,-6,6,0,3,-3,3,81,89,-1,8,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[144] = {-15,-6,0,6,-8,0,0,0,6,15,0,6,-8,0,0,0,-14,-7,6,24,-8,-1,0,1,7,14,6,24,-8,-1,0,1,-14,14,3,45,6,10,0,0,-28,-8,21,27,-15,-11,0,3,-13,-5,22,41,-7,1,0,1,5,13,22,41,-7,1,0,1,-12,12,39,50,-10,0,1,1,-18,-12,46,62,-13,-4,0,1,-12,12,49,67,-10,0,1,3,12,18,52,67,-13,-4,0,1,8,28,60,66,-15,-11,0,3,-10,10,66,71,-11,-4,1,3,-15,15,67,73,-12,-2,0,1,-9,9,70,85,-14,-6,0,0,-7,7,74,78,-15,-14,0,3,-7,7,83,90,-13,-7,0,0};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-16,-9,0,26,4,8,0,0,-3,4,0,26,4,8,0,0,10,17,0,26,4,8,0,0,-16,-9,0,26,-11,-6,0,1,-3,4,0,26,-11,-6,0,1,10,17,0,26,-11,-6,0,1,-18,20,24,45,-9,7,0,1,28,35,30,34,-11,-5,0,1,21,31,31,46,-7,2,0,2,15,21,34,47,-6,1,1,2,-22,-12,37,47,-4,2,0,1,28,35,37,41,-11,-5,0,1,23,31,39,44,-9,-7,0,3,-17,-9,45,54,-4,2,1,3,-4,4,45,54,-4,2,1,3,9,17,45,54,-4,2,1,3,-27,-19,46,58,-4,2,0,1,-28,-20,55,67,-4,2,0,1,-27,-19,65,76,-5,1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {19,17,15,18,17,24,18,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,24,30,21,26,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {466,429,430,508,430,555,423,503};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,25,28,27,27,28,23,24};
