// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-18,-2,0,7,-8,8,0,0,2,18,0,7,-8,8,0,0,-13,-6,7,36,-6,6,0,1,6,13,7,36,-6,6,0,1,-13,-5,34,58,-7,7,0,2,5,13,34,58,-7,7,0,2,13,31,10,82,-16,-8,1,3,14,30,42,50,-18,-16,0,3,-23,-17,38,70,-12,-6,0,1,-12,12,56,66,-8,8,0,0,14,18,66,94,-6,6,0,1,-14,14,64,100,-9,9,1,2,-18,-14,68,96,-6,6,0,1,-24,-16,68,96,-13,-5,0,2,-11,11,74,92,-11,-9,0,3,-20,-12,94,106,-9,9,1,2,12,20,94,106,-9,9,1,2,-9,9,98,106,-6,6,0,0,-23,-17,94,110,-12,-6,0,3,-7,7,104,124,-9,9,0,2,-6,6,110,117,-11,-9,0,0,-3,3,120,128,-8,6,1,3};
inline constexpr short grandleon_playstation_mesh_archer[176] = {-12,-4,0,7,-8,8,0,0,4,12,0,7,-8,8,0,0,-11,-5,7,40,-5,5,0,2,5,11,7,40,-5,5,0,2,-11,-4,38,62,-6,6,0,1,4,11,38,62,-6,6,0,1,-10,10,60,70,-7,7,0,0,12,17,68,90,-6,6,0,1,-17,-12,70,92,-6,6,0,1,-9,9,68,98,-7,7,1,2,13,27,74,82,-14,-8,0,1,-3,13,76,84,-15,-9,0,2,-26,-8,78,84,-14,-10,0,2,-4,4,80,88,-9,-7,0,3,-34,-28,76,88,-16,-8,0,3,-16,-10,94,102,-7,7,1,1,-9,9,98,114,-6,6,0,2,-9,9,104,110,-8,-6,0,3,-10,10,112,122,-7,7,1,2,-9,9,116,119,-9,-6,0,0,4,8,116,128,-2,2,0,2,-2,14,120,126,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-10,-3,0,6,-6,6,0,0,3,10,0,6,-6,6,0,0,-13,13,10,66,-8,8,1,1,-2,2,14,62,-10,-8,0,3,12,19,52,64,-8,0,0,3,11,16,62,84,-5,5,1,1,-16,-11,64,88,-5,5,1,1,-6,6,70,96,7,13,0,1,-8,8,64,92,-7,7,1,2,-21,-17,76,82,-4,2,0,3,-24,-14,84,94,-6,4,0,2,-22,-16,86,92,-8,-6,0,3,-6,6,90,98,-6,6,0,0,-5,5,96,112,-6,6,0,2,-5,5,101,107,-8,-6,0,3,-6,6,110,120,-7,7,1,1,-5,5,114,117,-9,-6,0,3,-2,4,118,123,-2,2,0,2,-1,3,118,128,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-9,9,0,24,-8,8,1,0,-9,9,6,70,8,14,1,1,-8,8,22,56,-7,7,1,2,16,20,0,112,-3,3,0,1,-8,8,50,58,-9,-7,0,0,-14,-10,54,80,-5,5,1,1,10,15,56,82,-5,5,1,1,-7,7,54,86,-7,7,1,3,-4,4,62,74,-9,-7,0,3,-30,-22,70,90,-5,5,0,3,-9,9,84,100,-6,6,0,1,-9,9,89,95,-8,-6,0,3,-11,11,96,110,-6,8,1,2,-10,10,102,106,-8,-5,0,0,-4,4,108,120,-2,6,1,2,6,30,108,118,-7,7,0,2,7,29,116,124,-5,5,0,3,7,29,122,127,-3,3,0,3,15,21,122,128,-3,3,0,3};
inline constexpr short grandleon_playstation_mesh_healer[168] = {-10,-3,0,6,-6,6,0,0,3,10,0,6,-6,6,0,0,-9,-3,6,34,-5,5,0,3,3,9,6,34,-5,5,0,3,-9,-2,32,56,-5,5,0,3,2,9,32,56,-5,5,0,3,-11,11,54,62,-6,6,0,0,-17,-13,62,88,-5,5,0,3,-13,13,60,92,-7,7,0,3,13,17,64,90,-5,5,0,3,-11,11,72,78,-9,-7,1,3,-3,3,66,84,-9,-7,1,3,-14,14,90,100,-9,9,1,2,10,18,88,112,4,12,0,2,-12,12,94,97,-11,-8,0,0,-11,11,98,114,-5,5,0,2,-11,11,103,109,-7,-5,0,0,-11,11,112,120,-6,6,0,3,-2,2,118,125,-2,2,0,2,-10,10,119,124,-4,0,0,2,-4,4,124,128,-4,4,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-12,-4,0,7,-7,7,0,0,4,12,0,7,-7,7,0,0,-11,-5,7,38,-5,5,0,1,5,11,7,38,-5,5,0,1,-14,14,6,90,7,15,1,1,-11,-4,36,60,-6,6,0,2,4,11,36,60,-6,6,0,2,-24,-20,0,118,-1,5,0,1,-13,13,58,68,-7,7,0,0,-18,-13,70,94,-6,6,0,2,13,18,70,94,-6,6,0,2,-12,12,66,100,-9,9,1,3,-10,10,78,86,-11,-9,0,3,-18,-11,94,106,-8,8,1,2,11,18,94,106,-8,8,1,2,-39,-19,88,116,0,6,1,3,-10,10,100,107,-5,5,0,0,-10,10,105,122,-8,8,0,2,-10,10,109,115,-10,-8,0,0,-25,-19,116,128,-1,5,0,3,-30,-14,120,126,-1,5,0,3,-2,2,120,128,-6,8,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-12,-4,0,7,-8,6,0,0,4,12,0,7,-8,6,0,0,-11,-5,7,36,-6,4,0,1,5,11,7,36,-6,4,0,1,-11,-4,34,58,-7,5,0,1,4,11,34,58,-7,5,0,1,-11,11,56,66,-8,6,0,0,-26,-19,60,66,-9,-1,0,0,19,26,62,68,-9,-1,0,0,-18,-12,64,86,-6,4,0,1,-11,11,60,104,7,13,0,0,12,18,66,88,-6,4,0,1,-11,11,64,96,-7,5,1,2,-25,-21,64,92,-8,-2,0,3,21,25,66,94,-8,-2,0,3,-3,3,68,90,-9,-7,0,3,-12,12,94,102,-8,6,0,1,-11,11,100,124,-8,8,0,0,-10,10,107,112,-10,-8,0,3,-10,10,110,116,-10,-7,0,3,-4,4,122,128,-6,4,0,0};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-14,-8,0,48,5,13,0,0,11,18,0,48,5,13,0,0,-14,-8,0,48,-15,-7,0,1,11,18,0,48,-15,-7,0,1,22,29,48,56,-8,0,0,0,-16,19,44,74,-14,10,0,1,-22,-18,52,66,-8,2,0,1,-14,18,50,56,-16,-14,0,3,-22,-19,56,62,-10,-8,0,3,12,38,56,76,-10,2,0,2,22,27,62,70,-12,-10,0,3,22,27,65,70,-12,-9,0,0,-22,6,72,84,-10,6,1,2,-2,25,72,84,-10,6,1,2,-17,18,79,91,-4,0,0,2,-3,3,82,100,-6,2,0,1,-1,2,98,122,-4,0,0,2,-2,4,120,128,-5,1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,22,19,19,21,22,21,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,24,30,21,26,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {466,429,430,508,430,555,423,503};
