// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-13,-5,0,10,-8,8,0,1,5,13,0,10,-8,8,0,1,-12,-5,8,44,-7,7,0,1,5,12,8,44,-7,7,0,1,-13,13,42,54,-8,8,0,0,-5,5,44,50,-11,-9,0,3,-22,-8,38,58,-16,-10,0,1,-25,-6,50,56,-18,-16,0,3,-12,12,52,88,-8,8,1,2,-12,12,62,68,-12,-10,1,0,-19,-12,62,84,-6,6,0,2,-25,-6,54,80,-16,-10,0,1,12,19,68,92,-6,6,0,2,-19,-9,62,78,-19,-17,1,3,-12,12,76,82,-12,-10,1,0,16,22,84,96,-8,-2,0,1,-22,-8,78,96,-16,-10,0,1,-16,-8,98,108,6,12,1,1,-9,9,88,110,-7,7,0,2,-8,8,96,102,-10,-8,0,0,20,26,94,122,-6,2,0,3,-11,11,108,128,-8,2,1,2};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-13,-5,0,10,-8,8,0,1,5,13,0,10,-8,8,0,1,-12,-5,8,44,-7,7,0,1,5,12,8,44,-7,7,0,1,-13,13,28,42,-10,10,0,1,-14,14,40,64,-9,9,1,2,-18,-12,62,84,-6,6,0,2,12,18,64,88,-6,6,0,2,-12,12,62,94,-9,9,0,1,10,17,84,94,6,10,1,3,-5,5,64,94,-12,-10,0,1,0,28,78,88,-12,-6,0,1,-30,2,80,86,-12,-8,0,3,10,17,94,108,4,12,0,1,-4,6,86,92,-15,-11,0,0,-9,9,88,112,-7,7,0,2,-8,8,98,103,-10,-8,0,0,-11,11,108,128,-8,4,0,1};
inline constexpr short grandleon_playstation_mesh_mage[128] = {2,8,0,8,-7,5,0,1,-11,-3,0,10,-8,6,0,1,3,8,6,44,-6,5,0,1,-10,-3,8,46,-7,6,0,1,-11,11,30,62,-8,8,1,1,10,17,40,52,-12,-6,0,3,10,15,52,76,-6,6,0,2,-10,10,60,70,-9,9,0,0,-15,-10,56,80,-6,6,0,2,-10,10,68,100,-8,8,1,2,-4,4,66,100,-11,-9,1,0,-18,-10,76,120,-6,6,0,1,10,18,76,120,-6,6,0,1,-8,8,88,112,-7,7,0,2,-7,7,100,104,-10,-8,1,3,-11,11,112,128,-6,8,0,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[192] = {-13,-5,0,10,-8,8,0,1,5,13,0,10,-8,8,0,1,-12,-5,8,44,-7,7,0,1,5,12,8,44,-7,7,0,1,-13,13,28,42,-9,9,0,1,26,32,0,78,0,8,0,1,15,21,0,78,-6,2,0,1,-14,14,40,52,-8,8,0,0,-18,-12,46,74,-6,6,0,2,12,18,50,78,-6,6,0,2,-12,12,50,90,-8,8,1,2,-19,-13,62,84,-12,-8,0,1,14,32,76,84,-6,8,0,1,12,18,82,94,-10,-2,0,1,16,30,86,92,-12,-6,0,3,30,34,83,95,-13,-5,0,3,-17,-11,82,98,-12,-8,0,1,22,32,98,110,2,12,0,3,-9,9,88,112,-7,7,0,2,-8,8,98,103,-10,-8,0,0,-16,-12,96,102,-14,-12,0,3,24,34,112,128,12,22,0,3,-11,11,108,126,-8,6,0,1,-10,10,112,117,-10,-8,0,3};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-21,21,0,26,-7,7,0,3,6,11,18,24,-10,-8,0,1,-18,18,24,56,-8,8,0,3,-10,-5,34,40,-11,-9,0,1,-13,13,54,92,-8,8,0,3,14,20,58,88,-6,6,0,2,-20,-14,74,104,-6,6,0,2,-13,13,82,92,-11,-9,1,3,-17,-11,88,98,-8,4,1,3,11,17,88,98,-8,4,1,3,-9,9,88,112,-7,7,0,2,-8,8,98,103,-10,-8,0,0,-25,-13,104,122,-6,4,0,1,-23,-15,108,118,-9,-7,1,3,-11,11,108,128,-8,4,0,3,-26,-12,120,126,-6,4,0,1};
inline constexpr short grandleon_playstation_mesh_commander[160] = {-13,-5,0,10,-8,8,0,1,5,13,0,10,-8,8,0,1,-12,-5,8,40,-7,7,0,1,5,12,8,40,-7,7,0,1,-18,18,38,70,-8,8,1,1,20,26,8,116,6,12,0,1,-19,-12,62,90,-6,6,1,2,12,19,62,90,-6,6,1,2,-13,13,68,104,-8,8,1,2,-5,5,68,102,-11,-9,0,3,-19,-13,88,94,-8,-2,0,2,13,19,88,94,-8,-2,0,2,26,34,98,114,4,18,1,3,-9,9,88,112,-7,7,0,2,28,33,102,108,0,3,0,3,-8,8,98,103,-10,-8,0,0,-16,16,110,116,-6,12,0,0,19,27,114,124,6,12,0,2,-4,4,116,128,2,12,1,3,-9,9,114,126,-7,7,0,1};
inline constexpr short grandleon_playstation_mesh_rogue[144] = {-23,-13,0,10,-9,7,0,1,13,23,0,10,-9,7,0,1,-22,-12,8,46,-8,6,0,1,12,22,8,46,-8,6,0,1,-14,14,44,54,-9,9,1,2,-19,-13,50,76,-6,6,0,2,-13,13,52,88,-8,8,0,3,-13,13,62,68,-11,-8,1,3,-26,-12,78,86,8,16,1,1,13,19,66,90,-6,6,0,2,-13,13,72,78,-11,-8,1,3,-26,-12,88,96,8,16,1,2,-9,9,78,100,-7,7,0,2,15,21,84,94,-8,-2,0,1,-8,8,88,94,-10,-8,0,0,18,26,92,114,-6,0,0,3,-11,11,98,118,-8,4,1,2,-6,6,116,128,-6,6,1,3};
inline constexpr short grandleon_playstation_mesh_beast[136] = {-10,-2,0,8,-10,2,0,2,4,12,0,8,-10,2,0,2,-24,-10,4,18,-3,7,1,1,-8,-3,6,28,-6,2,0,2,5,10,6,28,-6,2,0,2,-18,-4,16,32,-3,7,1,2,-12,2,28,48,-3,7,1,2,-8,16,26,74,-9,11,1,2,-6,12,40,70,-12,-9,1,1,-4,8,56,62,-14,-12,0,3,6,18,68,88,-7,7,1,3,4,24,88,102,-6,10,1,3,16,26,88,96,-10,-4,0,2,9,13,94,98,-8,-6,0,0,22,27,100,118,0,8,0,3,2,7,100,120,-4,4,0,3,12,17,102,128,-2,6,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,18,16,24,16,20,18,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,28,18,25,21,26,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,420,416,503,452,581,434,353};
