// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[128] = {-16,-6,0,5,-5,5,0,1,6,16,0,5,-5,5,0,1,-14,-6,5,28,-4,4,0,1,6,14,5,28,-4,4,0,1,-17,17,27,40,-6,6,1,1,-13,13,39,64,-6,6,1,2,-32,22,48,51,-10,-6,0,2,22,33,51,56,-10,-6,0,3,-24,-13,54,67,-5,5,0,1,13,24,54,67,-5,5,0,1,-13,13,57,60,-8,-6,1,3,-14,14,60,68,-4,5,0,1,-24,-13,67,69,-5,5,1,3,13,24,67,69,-5,5,1,3,-9,9,62,74,-8,-1,0,3,-11,11,71,82,-5,5,0,0};
inline constexpr short grandleon_playstation_mesh_archer[128] = {-13,-4,0,6,-6,6,0,1,4,13,0,6,-6,6,0,1,-12,-5,6,32,-4,4,1,1,5,12,6,32,-4,4,1,1,-22,-18,17,42,1,6,0,1,-14,14,30,42,-6,6,1,1,13,19,43,66,4,9,0,1,-16,-12,43,60,-4,4,1,1,12,16,43,60,-4,4,1,1,-12,12,40,68,-6,6,1,2,-12,12,52,56,-8,-6,1,3,-27,-20,40,92,1,6,0,1,13,19,66,75,6,10,0,3,-8,8,63,78,-9,-1,0,1,-15,15,75,78,-6,6,0,2,-7,7,78,83,-4,4,0,2};
inline constexpr short grandleon_playstation_mesh_mage[112] = {-14,14,0,44,-6,6,1,1,-4,4,3,44,-8,-6,1,3,-16,-11,35,41,-7,-2,0,2,11,16,35,41,-7,-2,0,2,-16,-11,40,58,-5,5,1,1,11,16,40,58,-5,5,1,1,14,19,35,84,2,6,0,1,-11,11,43,72,-5,5,1,2,-4,4,44,72,-8,-5,1,3,-12,12,69,72,-8,-6,0,3,19,26,70,87,3,8,0,3,-8,8,70,86,-9,-2,0,2,-6,6,81,84,-5,-4,0,3,-4,4,81,98,-4,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[128] = {-20,20,0,17,-7,7,1,1,-18,18,16,38,-6,6,1,2,-31,-21,22,38,-4,4,0,3,21,31,27,43,-4,4,0,3,-24,-16,33,48,-4,4,0,3,16,24,34,50,-4,4,0,3,-14,14,38,43,-7,-6,1,3,-11,11,39,63,-5,5,0,3,19,25,51,68,-4,1,0,3,20,26,67,71,-4,0,0,2,-12,-8,64,76,-4,3,0,0,8,12,64,76,-4,3,0,0,22,32,69,78,1,7,0,1,-8,8,64,74,-8,-1,0,2,-9,9,73,76,-6,-5,1,3,-11,11,74,84,-4,5,0,0};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-13,13,0,20,-5,5,0,3,-15,15,19,39,-5,5,0,3,-21,-15,33,39,-6,-2,0,2,15,21,33,39,-6,-2,0,2,-22,-16,13,75,0,4,0,1,-16,16,37,52,-5,5,0,3,-20,-15,40,56,-4,4,0,3,15,20,40,56,-4,4,0,3,-4,16,39,52,-7,-5,1,2,-18,18,51,64,-6,6,0,3,-16,4,52,64,-8,-6,1,2,-15,15,59,63,-8,-6,1,3,-24,-19,64,73,0,3,0,3,-9,9,63,79,-8,0,0,2,-7,7,71,72,-9,-8,0,0,-26,-14,73,85,1,5,0,3};
inline constexpr short grandleon_playstation_mesh_commander[144] = {-14,-5,0,5,-5,5,0,1,5,14,0,5,-5,5,0,1,-12,-5,5,25,-4,4,0,1,5,12,5,25,-4,4,0,1,-20,20,11,33,-6,6,1,1,-26,-12,21,25,-8,-5,0,3,-18,18,31,46,-5,5,1,2,8,13,38,66,6,10,0,1,-13,13,41,64,-6,6,0,0,-13,13,49,53,-8,-6,1,3,-21,-13,53,61,-5,4,0,1,13,21,53,61,-5,4,0,1,-13,13,65,75,6,16,1,2,-14,14,61,69,-4,6,0,0,-4,4,74,76,8,13,0,3,-9,9,61,73,-8,-1,0,2,-11,11,69,80,-5,5,0,0,-9,9,73,79,-8,-6,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[136] = {-24,-14,0,22,-5,2,0,1,14,24,0,22,-5,2,0,1,-26,-13,16,21,-10,-6,0,2,-21,-12,21,35,-5,2,0,1,12,21,21,35,-5,2,0,1,-15,15,20,36,-7,-2,0,0,-14,14,33,38,-9,-4,1,3,-19,-13,37,49,-6,0,0,1,13,19,37,49,-6,0,0,1,-13,13,36,54,-6,4,0,1,-11,11,37,53,-9,-6,0,0,-11,11,53,58,-7,2,0,2,12,22,55,60,-11,-7,0,3,-11,11,57,72,-5,4,0,1,-10,10,62,65,-6,-5,1,3,20,28,59,67,-11,-7,1,3,-8,8,69,79,-2,5,0,1};
inline constexpr short grandleon_playstation_mesh_beast[120] = {-18,-10,0,24,2,7,0,0,6,14,0,24,2,7,0,0,-14,-6,0,24,-8,-3,0,1,10,18,0,24,-8,-3,0,1,-20,20,22,42,-8,6,0,1,-24,-12,27,44,0,4,0,1,14,24,26,40,-7,2,0,1,16,28,27,36,-9,-6,1,3,19,34,34,44,-7,1,0,2,26,36,33,39,-10,-7,0,3,-14,14,40,43,-6,4,1,2,19,24,43,52,0,3,0,2,29,34,43,52,0,3,0,2,-27,-19,42,60,1,6,0,2,-29,-23,59,71,2,7,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {16,16,14,16,16,18,17,15};
inline constexpr int grandleon_playstation_mesh_max_parts = 18;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {32,21,19,31,23,22,25,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,490,393,524,489,518,369,476};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,28,28,26,26,28,24,24};
