// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-11,-4,0,6,-6,6,0,1,4,11,0,6,-6,6,0,1,-10,-5,6,30,-4,4,1,2,5,10,6,30,-4,4,0,1,-10,-4,28,42,-5,5,0,2,4,10,28,42,-5,5,1,0,-11,11,39,49,-7,7,0,1,10,28,42,46,-4,1,0,0,-28,-11,27,66,-9,-1,1,2,-11,11,48,52,-7,7,0,2,11,15,48,69,-4,4,0,1,-15,-11,48,69,-4,4,1,3,-12,12,51,73,-6,6,0,2,-3,3,55,79,5,10,0,0,-10,10,55,69,-7,-6,0,1,17,21,46,87,-1,1,0,3,-14,-8,70,76,-4,4,0,0,8,14,70,76,-4,4,0,1,-10,9,73,78,-5,5,0,2,-6,6,75,76,-7,-5,0,3,-9,9,76,91,-6,6,0,2,-9,9,80,84,-7,-6,0,2,-12,-7,87,96,-1,3,0,0,7,12,87,96,-1,3,0,3,-17,-2,90,94,-1,3,0,0};
inline constexpr short grandleon_playstation_mesh_archer[192] = {-12,-4,0,5,-5,5,0,2,4,12,0,5,-5,5,0,1,-29,-13,6,13,3,7,0,0,-10,-4,5,23,-4,4,0,2,4,10,5,23,-4,4,0,2,-10,-3,21,33,-4,4,0,2,3,10,21,33,-4,4,1,2,-13,13,31,40,-5,5,0,2,26,30,6,77,-1,1,0,0,-13,-9,40,53,-3,3,0,3,9,13,40,53,-3,3,0,2,-16,-8,39,62,4,9,0,0,25,31,44,52,-2,2,0,0,-6,6,39,58,-4,4,0,3,14,26,45,50,-5,-1,0,2,-3,3,39,58,-6,-4,0,3,-5,3,52,67,4,8,0,0,-15,-9,60,69,5,9,0,0,-6,6,57,64,-5,3,0,2,-6,6,59,62,-6,-5,0,2,-6,6,63,73,-3,5,0,3,-5,5,70,75,1,6,1,3,-4,4,67,70,-6,-4,0,3,-3,3,70,80,1,6,1,3};
inline constexpr short grandleon_playstation_mesh_mage[160] = {-17,17,0,12,-6,6,1,1,-12,12,10,31,-5,5,1,2,-3,3,4,48,-7,-5,1,2,-12,-8,34,46,-4,4,1,3,8,12,34,46,-4,4,1,3,-11,11,30,51,-4,4,1,3,-17,-10,40,48,-4,1,0,2,-16,-12,9,85,-2,1,1,3,-8,8,49,55,-4,4,0,3,2,8,49,68,4,9,0,0,-5,5,51,53,-7,-4,0,3,-8,8,55,67,-5,3,0,1,-4,4,60,63,-7,-5,0,1,-12,12,63,77,0,6,0,0,-11,-6,68,83,-1,3,0,3,6,11,68,83,-1,3,0,2,-26,-2,57,95,-2,1,0,2,-7,-2,82,95,-1,4,0,0,2,7,82,95,-1,4,0,0,-18,-10,83,92,-4,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-11,11,0,10,-5,5,0,0,-10,10,9,31,-4,4,1,2,-3,3,4,47,-5,-4,1,2,-24,-20,0,70,-1,1,0,1,14,32,27,56,2,7,0,1,-13,-9,32,47,-3,3,1,3,9,13,32,47,-3,3,1,3,-28,-12,38,45,-2,2,1,1,-9,9,31,52,-4,4,1,3,2,10,43,62,4,8,0,0,-12,12,52,61,-4,3,1,3,-4,4,54,58,-6,-4,1,3,-13,13,59,70,-2,5,0,1,-13,-7,64,72,-1,2,0,1,7,13,64,72,-1,2,0,0,-9,9,64,67,-6,-4,0,2,-35,-9,69,75,-4,4,0,0,-26,-18,74,79,-2,2,0,0};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-19,19,0,11,-5,5,0,0,-15,15,10,27,-4,4,1,3,-14,14,26,30,-5,5,1,3,-4,4,2,52,-6,-5,0,3,-20,-16,4,72,-2,1,0,3,-13,13,29,48,-4,4,0,3,-21,-13,36,42,-3,1,0,3,-15,-11,31,50,-3,3,1,3,11,15,31,50,-3,3,0,3,-10,18,45,52,4,7,0,0,1,7,46,60,4,7,0,0,-13,13,53,63,-4,3,0,3,-14,14,60,63,-4,-3,0,3,-15,15,58,75,-2,6,0,3,-11,11,72,80,1,7,0,2,-29,-7,70,77,-2,1,1,3,-21,-15,71,75,-3,-2,0,3};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-12,-4,0,6,-6,6,0,1,4,12,0,6,-6,6,0,0,-11,-5,6,28,-4,4,1,2,5,11,6,28,-4,4,0,1,-14,14,7,67,4,9,1,2,-11,-4,26,41,-4,4,1,2,4,11,26,41,-4,4,0,0,-14,14,39,49,-6,6,1,2,-24,-20,0,93,0,3,1,3,-13,13,48,52,-6,6,0,0,-28,-8,52,60,-1,3,0,1,-15,-11,48,68,-4,4,0,1,11,15,48,68,-4,4,0,1,0,8,51,76,7,11,0,0,-14,14,50,71,-6,6,0,1,-12,12,55,65,-7,-6,0,1,-32,-24,63,70,0,3,0,1,-16,-9,68,75,-4,4,0,1,9,16,68,75,-4,4,0,0,-12,12,71,76,-5,5,0,0,-8,8,73,74,-7,-5,1,2,-43,-19,68,89,0,3,0,1,-12,12,74,89,-5,5,0,1,-12,12,77,81,-7,-5,0,1,-2,2,86,93,-4,5,0,0};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-11,-4,0,5,-5,5,0,1,4,11,0,5,-5,5,0,1,-30,-10,6,11,3,6,0,1,-10,-4,5,19,-3,3,0,1,4,10,5,19,-3,3,0,1,-10,-3,18,27,-3,3,1,2,3,10,18,27,-3,3,0,1,-10,10,26,33,-5,5,1,2,-9,9,32,35,-5,5,0,3,-10,10,25,51,3,7,0,1,-13,-9,34,45,-3,3,0,2,9,13,34,45,-3,3,0,2,-9,9,33,49,-4,4,0,1,-8,8,35,46,-5,-4,0,2,-8,0,41,55,6,9,0,0,-19,-12,41,46,-5,-1,0,2,12,19,41,46,-5,-1,0,1,-8,8,49,55,-4,3,1,2,-4,4,51,53,-5,-4,1,2,-18,-13,46,60,-4,-2,0,1,13,18,46,60,-4,-2,0,0,-10,10,53,66,-2,5,0,2,-7,7,58,62,-6,-5,0,2,-2,4,63,72,2,7,0,1,-9,11,67,71,2,7,0,1};
inline constexpr short grandleon_playstation_mesh_beast[168] = {-12,-5,0,25,5,11,0,0,8,14,0,25,5,11,0,0,4,11,0,25,-11,-5,0,1,-15,-9,0,25,-11,-5,0,1,9,23,24,34,-3,3,0,0,-12,8,22,29,-10,-9,0,2,-13,9,22,43,-9,7,0,1,14,28,30,42,-3,3,0,1,7,12,38,45,-2,2,0,1,-4,14,39,54,4,8,0,1,0,4,41,47,-2,2,1,2,-9,-4,42,49,-2,2,0,1,-24,-8,35,57,-4,3,0,1,20,25,41,53,-2,2,0,0,-19,-14,37,54,-6,-4,0,2,-17,-10,55,63,1,5,1,3,-28,-22,55,62,-7,-1,0,1,-32,-11,54,67,-5,3,0,1,-24,-20,62,66,-7,-5,1,2,-15,-9,66,84,-1,3,0,0,-23,-1,72,81,-1,3,0,0};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,24,20,18,17,25,25,21};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,28,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {472,428,359,478,409,630,419,582};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,23,25,28,23,27};
