// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[168] = {-14,-5,0,5,-5,5,0,0,5,14,0,5,-5,5,0,0,-13,-6,5,28,-4,4,0,1,6,13,5,28,-4,4,0,1,-23,-15,11,29,-7,-3,1,2,-13,-5,26,41,-5,5,0,1,5,13,26,41,-5,5,0,1,-27,-11,28,46,-7,-3,1,3,-14,14,38,48,-6,6,1,1,22,28,44,66,3,7,0,3,-29,-9,44,61,-7,-3,1,3,-12,12,46,67,-7,7,1,1,-5,5,46,67,-8,-7,0,1,-19,-9,63,71,-4,7,0,2,9,19,63,71,-4,7,0,2,24,30,63,77,4,9,0,3,-8,8,66,70,-5,5,0,0,-10,10,69,82,-6,6,0,1,-10,10,71,75,-7,-6,0,0,-3,3,77,85,1,11,0,3,-7,7,75,77,-8,-7,0,3};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-13,-4,0,5,-5,5,0,0,4,13,0,5,-5,5,0,0,-12,-5,5,24,-4,4,0,1,5,12,5,24,-4,4,0,1,-12,-4,23,36,-4,4,0,1,4,12,23,36,-4,4,0,1,-13,13,34,41,-5,5,1,1,10,18,36,58,4,8,0,2,-15,-11,40,52,-4,4,1,1,11,15,40,52,-4,4,1,1,-11,11,40,59,-5,5,1,3,22,32,42,48,-12,-8,0,3,-11,11,45,48,-11,-10,0,1,-5,5,40,59,-6,-5,0,1,-30,30,47,51,-10,-6,0,3,12,16,55,65,5,10,0,3,-6,6,57,65,-6,1,0,2,-12,12,63,76,-4,6,1,2,-2,10,69,77,2,8,1,1,-9,9,66,70,-5,-4,0,0};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-14,14,0,14,-6,6,1,1,-12,12,13,31,-5,5,1,2,-4,4,3,45,-7,-6,0,2,-17,-12,24,31,-6,-1,0,1,12,17,24,31,-6,-1,0,1,-14,-8,28,40,-3,3,1,2,8,14,28,40,-3,3,1,2,-10,10,29,45,-4,4,1,2,-9,9,40,46,-5,5,1,3,-8,8,42,60,-6,3,0,1,-6,6,50,54,-7,-6,0,3,-8,8,58,64,4,8,0,3,-17,-7,61,68,4,8,0,2,7,17,61,68,4,8,0,2,-19,-13,66,81,4,8,0,3,13,19,66,81,4,8,0,3,-17,-7,80,87,4,8,0,2,7,17,80,87,4,8,0,2,-8,8,84,89,4,8,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[168] = {-15,15,0,12,-5,5,1,1,-13,13,11,31,-5,5,1,2,-4,4,4,50,-6,-5,0,1,-30,-16,27,45,1,6,1,0,16,30,27,45,1,6,1,0,-15,-11,30,45,-4,4,1,2,11,15,30,45,-4,4,1,2,-11,11,30,50,-5,5,1,3,-30,-16,43,51,-2,5,0,1,16,30,43,51,-2,5,0,1,-30,-20,49,55,-4,1,0,1,20,30,49,55,-4,1,0,1,-32,-20,53,59,-5,1,0,1,20,32,53,59,-5,1,0,1,-30,-25,55,57,-6,-5,0,3,25,30,55,57,-6,-5,0,3,-31,-23,59,63,1,5,0,3,23,31,59,63,1,5,0,3,-8,8,55,67,-4,4,0,2,-10,10,61,72,-2,6,0,1,-9,9,71,76,-4,4,0,3};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-16,16,0,13,-5,5,0,3,-6,6,3,36,-6,-5,1,3,-22,22,11,35,-5,5,0,3,-22,-16,26,33,-5,-1,0,1,-20,-15,31,48,-4,4,0,3,-15,15,34,53,-5,5,0,3,15,20,39,58,-4,4,0,3,-6,6,34,57,-6,-5,1,3,-7,7,57,60,-5,-4,0,0,-8,8,55,68,-4,4,0,1,-11,11,60,74,-3,6,0,3,16,26,62,73,-5,3,0,2,-10,10,67,70,-5,-3,1,3,19,23,67,70,-6,-5,0,2,-8,8,73,80,0,6,0,3,18,26,72,78,-4,1,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-12,-5,0,28,-4,4,0,1,5,12,0,28,-4,4,0,1,-17,17,4,59,3,7,1,1,-12,-4,27,42,-5,5,0,1,4,12,27,42,-5,5,0,1,16,32,27,53,1,6,1,1,-13,13,39,49,-6,6,1,2,-21,-15,31,68,-6,-1,0,3,-17,-12,49,66,-4,4,0,1,12,17,49,66,-4,4,0,1,-12,12,48,72,-7,7,0,1,18,34,51,75,3,7,1,2,-9,9,56,61,-8,-7,0,3,-20,-10,68,75,-6,4,0,1,10,20,68,75,-6,4,0,1,-23,-13,65,82,-4,1,0,3,20,32,72,90,4,8,1,3,-16,-7,77,84,1,6,0,3,7,16,77,84,1,6,0,3,-10,10,73,86,-6,6,0,1,-10,10,76,80,-8,-6,0,0,-7,7,80,82,-8,-7,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-22,-13,0,20,-5,2,0,1,13,22,0,20,-5,2,0,1,-16,16,3,32,2,7,0,1,-28,-19,13,17,-10,-7,0,3,-21,-14,17,24,-9,-6,0,3,-20,-11,18,31,-5,2,0,1,11,20,18,31,-5,2,0,1,-13,13,17,32,-7,-2,1,2,-15,15,30,35,-7,-2,0,3,-18,-13,34,45,-6,0,0,1,-13,13,32,50,-6,5,0,1,13,18,36,49,-6,0,0,1,-12,12,34,49,-8,-5,1,3,-11,11,49,53,-7,2,1,2,14,24,49,54,-10,-7,0,3,-9,9,52,64,-5,3,0,2,-17,-10,60,65,1,6,0,3,-21,-13,62,67,2,7,0,3,20,30,53,60,-12,-8,0,3,-11,11,58,71,-2,6,0,1,-24,-16,65,69,3,8,0,3,-7,7,61,64,-5,-3,0,3,-8,8,67,74,0,6,0,1};
inline constexpr short grandleon_playstation_mesh_beast[184] = {-21,-13,0,27,4,10,0,0,3,11,0,27,4,10,0,0,-16,-8,0,27,-10,-4,0,1,8,16,0,27,-10,-4,0,1,-32,-24,14,23,-4,1,0,3,-30,-18,19,29,-5,1,0,1,-22,-10,25,37,-6,3,0,1,-20,18,24,50,-10,6,0,1,12,22,38,54,-5,1,0,1,-22,-6,45,55,-1,4,1,2,6,22,45,55,-1,4,1,2,10,16,41,52,-8,-5,1,3,-14,-6,47,52,-6,-3,1,3,0,8,47,52,-6,-3,1,3,-32,-18,52,66,0,5,1,3,18,32,52,66,0,5,1,3,18,28,51,64,-5,1,0,1,26,32,57,61,-13,-11,0,3,19,32,59,70,-9,0,0,1,25,32,60,66,-11,-6,0,1,21,26,65,68,-10,-9,0,3,17,25,69,78,0,5,0,3,25,33,69,82,0,5,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {21,20,19,21,16,22,23,23};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {29,30,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {490,446,377,496,427,650,434,597};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,23,25,28,23,27};
