// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-14,-6,0,6,-5,5,0,1,6,14,0,6,-5,5,0,1,-13,-6,5,30,-4,4,0,2,6,13,5,30,-4,4,0,1,-14,14,29,36,-6,6,0,1,-13,13,42,45,-8,-6,1,0,-13,13,34,64,-6,6,0,1,13,20,43,62,-4,4,0,0,-3,3,36,64,-8,-6,1,2,-20,-13,46,66,-4,4,0,2,-13,13,50,54,-8,-6,0,2,-24,-18,59,66,-4,0,0,0,-11,11,64,79,-5,5,0,2,8,16,72,80,4,8,0,3,8,11,69,72,-6,-4,0,3,-11,11,69,74,-7,-6,0,2,-27,-21,64,87,-4,1,0,3,-11,11,76,92,-5,2,1,3};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-12,-5,0,8,-5,5,0,1,5,12,0,8,-5,5,0,2,-10,-4,7,26,-5,5,0,2,4,10,7,26,-5,5,0,2,-9,9,24,43,-6,6,1,2,-19,-12,45,53,-4,4,0,0,12,18,43,56,-4,4,0,1,-15,15,42,63,-6,6,0,1,-28,1,46,54,-8,-4,0,2,-5,28,48,52,-9,-6,0,0,1,6,49,53,-9,-8,0,3,0,7,42,62,-9,-7,1,1,-12,12,43,62,-9,-8,0,1,-9,-2,53,56,-9,-7,0,3,-4,3,60,71,4,7,0,1,-7,7,59,72,-5,5,1,2,-6,6,64,68,-7,-5,1,3,-7,7,70,84,-5,4,0,1};
inline constexpr short grandleon_playstation_mesh_mage[136] = {-8,-3,0,4,-4,3,0,0,3,11,0,7,-5,4,0,2,-7,-3,3,31,-3,3,0,1,4,10,5,31,-4,3,0,2,-3,3,29,34,-7,-5,1,2,-12,12,29,45,-5,5,0,2,-11,11,44,49,-6,6,0,1,-16,-10,40,57,-3,3,0,1,-10,10,48,67,-5,5,0,3,10,16,51,71,-3,3,0,1,-9,9,60,75,-4,4,0,2,-16,-8,55,81,-3,4,0,1,-9,9,66,70,-6,-5,0,1,11,14,71,79,-4,-2,0,1,-8,8,72,76,-6,-5,0,2,-9,9,74,87,-4,5,0,1,5,19,77,85,-5,-1,0,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-13,-6,0,8,-5,5,0,1,6,13,0,8,-5,5,0,0,-12,-6,6,32,-5,5,0,2,6,12,6,32,-5,5,0,1,-13,13,31,41,-6,6,1,2,18,23,0,81,-2,2,0,1,-12,12,38,44,-7,7,0,2,-18,-12,44,64,-4,4,0,0,-12,12,50,54,-8,-6,1,0,-12,12,43,70,-5,5,1,3,12,18,47,69,-4,4,0,2,-11,11,67,84,-5,5,0,0,-11,11,74,78,-8,-6,0,2,10,30,79,87,-5,5,0,0,10,30,81,84,-6,-5,0,1,-6,6,81,95,-5,5,0,1,-6,6,84,88,-7,-5,0,1,15,25,86,93,-3,3,0,3,17,24,92,98,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_healer[144] = {-12,-4,0,6,-5,5,0,1,4,12,0,6,-5,5,0,0,-11,-4,5,26,-4,4,0,3,4,11,5,26,-4,4,0,3,-14,14,25,41,-6,6,0,3,-8,-2,30,34,-7,-6,0,3,3,23,32,41,-7,-1,0,3,12,18,40,59,-3,3,0,2,3,9,45,50,-7,-6,0,1,-18,-12,41,62,-3,3,0,2,-12,12,40,65,-5,5,0,3,0,6,43,65,-7,-6,0,3,-10,-6,61,66,-6,-5,0,0,6,10,61,66,-6,-5,0,0,-12,12,62,77,-5,5,0,3,6,13,72,78,3,7,0,3,-12,12,68,72,-7,-6,1,3,-12,12,76,88,-5,2,0,2};
inline constexpr short grandleon_playstation_mesh_commander[192] = {-13,-6,0,8,-5,5,0,2,2,9,0,8,-5,5,0,1,-12,-6,6,27,-4,4,0,1,2,8,6,27,-4,4,0,1,-14,11,4,68,6,10,0,1,-14,11,26,47,-6,6,0,1,-24,-19,3,84,3,6,0,3,-13,9,44,50,-6,6,0,1,-5,2,45,48,-8,-6,0,2,-19,-14,46,65,-4,4,0,3,10,15,46,65,-4,4,1,2,-13,9,48,71,-6,6,1,3,-5,2,50,70,-8,-6,1,2,-19,-14,61,65,-6,-1,0,2,10,15,61,65,-6,-1,0,3,-37,-17,68,83,2,11,0,1,-13,9,65,80,-5,5,0,2,-13,9,67,71,-7,-6,0,2,-29,-24,73,78,1,2,0,1,-13,9,71,75,-7,-6,0,1,-12,8,78,88,-5,5,0,1,-13,9,78,82,-7,-6,0,0,-4,1,85,91,-4,7,0,2,-8,5,87,90,-4,7,0,1};
inline constexpr short grandleon_playstation_mesh_rogue[152] = {-26,-8,0,5,-5,4,0,1,8,26,0,5,-5,4,0,1,-24,-8,4,26,-4,3,0,1,8,24,4,26,-4,3,0,1,-11,11,25,31,-5,5,1,3,-11,11,34,37,-6,-5,1,1,-11,11,30,51,-4,4,1,3,-13,13,34,59,4,7,0,3,-18,-12,35,52,-3,3,0,3,-11,11,40,43,-6,-5,0,2,12,18,38,54,-3,3,0,0,-20,-14,51,57,-4,-1,1,2,-12,12,50,61,-4,4,0,2,14,20,53,59,-4,-1,0,0,-12,12,53,57,-5,-4,0,3,-18,-13,56,69,-4,0,1,3,13,18,58,71,-4,0,0,3,-11,11,60,72,-4,4,0,1,-4,4,71,76,-2,5,1,3};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-10,-3,0,5,-6,2,0,1,1,8,0,5,-6,2,0,0,8,23,4,11,-1,4,0,0,-8,-4,3,20,-3,2,0,0,2,6,3,20,-3,2,0,3,2,19,9,20,-1,4,0,1,-2,13,17,29,-1,4,1,2,-12,5,18,50,-5,7,1,2,-10,5,28,47,5,7,1,3,-10,5,26,46,-7,-5,1,2,-10,3,34,38,-9,-7,1,2,-17,-3,47,60,-4,4,1,1,-18,-5,59,68,-5,6,1,3,-25,-15,60,65,-4,0,0,1,-11,-8,63,66,-5,-4,0,0,-18,-12,67,72,1,5,0,3,-17,-13,67,76,1,5,0,3,-7,-3,67,79,-2,3,0,3,-12,-8,68,84,-1,3,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,18,17,19,18,24,19,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,28,18,25,21,26,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,420,416,503,452,581,434,353};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,25,26,28,25,28,23,25};
