// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[152] = {-22,-2,0,8,-8,8,0,1,2,22,0,8,-8,8,0,1,-15,-7,8,40,-6,6,0,1,7,15,8,40,-6,6,0,1,-18,18,38,60,-9,9,1,1,25,30,2,114,0,6,0,1,-16,16,66,72,-12,-9,0,0,-16,16,58,96,-9,9,1,2,7,33,74,84,-5,5,0,1,-34,-6,82,87,-8,8,1,3,6,34,82,87,-8,8,1,3,-28,-12,82,104,-8,8,0,1,12,28,82,104,-8,8,0,1,-9,9,104,114,-5,8,0,0,-8,8,98,114,-12,-2,0,3,-8,8,104,109,-13,-11,0,0,23,33,114,128,0,6,0,3,-8,8,112,128,-7,7,0,0,-3,3,118,128,-10,-7,1,3};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-12,-4,0,8,-7,7,0,1,4,12,0,8,-7,7,0,1,-11,-4,8,42,-6,6,1,1,4,11,8,42,-6,6,1,1,18,22,20,60,2,8,0,1,-11,11,40,58,-8,8,1,1,11,18,58,66,-5,5,1,1,-18,-12,58,90,6,12,0,1,-15,-11,60,82,-6,6,1,1,-12,12,56,92,-8,8,1,2,-11,11,70,76,-11,-8,0,0,-18,-12,90,102,8,14,0,3,20,25,60,128,2,8,0,1,-11,11,90,108,-11,-1,0,2,-7,7,98,103,-14,-11,0,0,-9,9,104,109,-12,-2,1,3,-8,8,108,122,-6,6,0,0,-3,3,120,127,-2,4,0,0};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-13,13,0,6,-9,9,0,0,-9,9,0,56,-8,8,1,1,-3,3,6,54,-10,-8,1,3,-8,8,58,66,-10,-6,0,2,-17,-10,54,80,-6,6,1,1,10,17,54,80,-6,6,1,1,-10,10,54,92,-7,7,1,2,-3,3,62,84,-12,-9,0,3,-10,10,88,92,-10,-7,0,0,-22,-16,96,112,-2,4,0,3,-9,9,92,108,-11,-1,0,2,-6,6,99,103,-13,-10,0,0,18,24,100,120,-2,4,0,3,-7,7,104,108,-8,-6,0,3,-5,5,106,128,-4,3,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[120] = {-14,14,0,24,-9,9,1,1,-16,16,22,56,-8,8,1,2,-20,-14,50,56,-8,-2,0,2,25,29,8,110,-2,4,0,1,-14,14,60,66,-11,-8,1,3,-28,-14,54,84,-6,6,0,3,-9,9,54,94,-8,8,0,3,10,24,70,90,-6,4,0,3,21,29,86,94,-3,4,0,2,-11,11,96,112,-11,-1,0,2,-7,7,103,107,-14,-11,0,0,-12,12,106,110,-12,-4,1,3,16,38,108,118,-6,6,0,0,-11,11,110,126,-6,6,0,0,19,35,116,128,-5,5,1,3};
inline constexpr short grandleon_playstation_mesh_healer[120] = {-12,-4,0,6,-7,7,0,2,4,12,0,6,-7,7,0,2,-13,13,4,12,-9,9,0,1,-13,13,4,54,-8,8,0,3,16,21,12,110,-2,4,0,1,13,20,60,68,-3,3,0,2,-19,-13,56,82,-6,6,0,3,-4,18,56,76,-11,-8,1,2,-13,13,52,92,-8,8,0,3,-17,5,74,92,-11,-8,1,2,-11,11,84,88,-12,-10,0,0,-11,11,92,116,-11,0,0,2,-10,10,102,105,-13,-11,0,0,9,29,108,124,-1,5,0,3,17,21,122,128,-1,5,0,3};
inline constexpr short grandleon_playstation_mesh_commander[160] = {-19,3,0,8,-8,8,0,1,-3,19,0,8,-8,8,0,1,-11,-4,8,38,-6,6,0,1,4,11,8,38,-6,6,0,1,-14,14,36,58,-8,8,1,1,-27,-5,44,50,-11,-7,0,3,-14,14,30,92,8,13,1,2,-14,14,56,96,-8,8,0,1,-12,-7,70,128,12,17,0,1,-19,-12,82,100,-7,7,0,1,12,19,82,100,-7,7,0,1,-10,10,84,90,-11,-8,1,3,-11,11,94,106,-5,9,0,0,-12,10,96,126,13,17,1,2,-10,8,106,114,11,13,0,3,-9,9,96,112,-11,-1,0,2,-7,7,99,102,-14,-11,0,3,-11,11,108,126,-7,7,0,0,-16,-11,116,128,-3,1,0,3,11,16,116,128,-3,1,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {-25,-3,0,34,-7,5,0,1,3,25,0,34,-7,5,0,1,-16,-8,32,54,-7,5,0,1,8,16,32,54,-7,5,0,1,-11,11,50,60,-9,7,0,0,-8,8,52,58,-12,-9,1,3,-19,-12,58,82,-8,0,0,1,12,19,58,82,-8,0,0,1,-9,9,58,90,-9,5,0,1,-9,9,62,84,-12,-9,0,0,-11,11,72,96,5,11,0,2,-22,-15,76,84,-9,-3,0,2,15,22,76,84,-9,-3,0,2,-10,10,88,96,-11,3,0,0,-33,-28,84,108,-8,-3,0,3,16,21,84,108,-8,-3,0,3,-11,11,94,118,-7,6,0,1,-10,10,98,106,-12,-7,0,2,-7,7,104,110,-14,-11,0,3,-6,6,114,128,-4,6,0,1};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-12,-7,0,40,4,12,0,0,7,13,0,40,4,12,0,0,5,10,0,40,-13,-5,0,1,-15,-10,0,40,-13,-5,0,1,-17,14,34,68,-13,9,0,1,-27,-3,38,66,-12,6,0,2,4,27,50,74,-2,6,0,1,-34,-11,54,64,-9,-1,0,3,-26,-23,56,62,-8,-2,0,0,-24,0,58,68,-14,7,1,3,-28,-5,56,78,-10,2,0,2,-13,11,64,72,-13,7,1,2,-24,-8,65,71,-16,-13,0,0,-16,-12,76,92,-4,4,0,1,-21,-17,76,92,-4,4,0,1,16,22,70,102,-1,7,0,2,-28,0,80,88,-6,2,0,1,17,22,98,128,0,8,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {19,18,15,15,15,20,20,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 20;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {32,21,19,31,23,22,25,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,490,393,524,489,518,369,476};
