// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-12,-4,0,7,-7,7,0,0,4,12,0,7,-7,7,0,0,-11,-4,5,40,-5,5,0,3,4,11,5,40,-5,5,0,3,-12,12,40,46,-9,-8,0,0,-12,12,40,62,-8,8,1,2,-31,-25,58,68,-6,-4,0,3,-38,-18,46,88,-4,4,1,2,-13,13,60,94,-8,8,1,3,15,22,72,86,-5,2,0,3,-11,11,66,88,-10,-8,0,1,4,12,78,108,6,12,0,1,-12,12,92,99,-7,7,0,0,17,21,84,122,-3,3,0,2,-13,13,97,114,-8,7,0,3,-12,12,102,108,-10,-8,0,0,-12,12,110,118,-9,8,0,1,-10,10,114,128,-7,7,0,2};
inline constexpr short grandleon_playstation_mesh_archer[128] = {-9,-3,0,36,-5,5,0,3,3,9,0,36,-5,5,0,3,-12,12,34,40,-8,-7,0,0,-11,11,34,56,-7,7,1,2,-10,10,54,59,-7,-6,0,0,-22,-17,10,118,-4,2,0,2,-23,-16,58,70,-5,1,1,1,9,16,58,92,3,9,0,1,-11,11,54,92,-6,6,1,2,-10,10,66,72,-8,-6,0,3,-16,-9,68,76,-5,1,0,3,-12,-5,76,104,5,10,0,0,-11,11,90,96,-7,6,1,3,-10,10,96,118,-7,6,0,3,-9,9,102,107,-9,-7,0,0,-5,5,114,128,-6,7,0,0};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-12,12,0,24,-6,6,1,2,-15,15,22,27,-7,-6,0,0,-12,12,50,57,-7,-5,1,1,-11,11,24,90,-5,5,1,3,-17,-13,6,114,-3,3,0,3,-14,-7,60,68,-4,2,0,3,-4,4,66,72,-8,-6,0,3,-9,9,60,84,-6,-5,0,0,-9,11,70,96,5,10,0,0,-11,11,86,92,-7,-5,0,0,-8,8,88,118,-5,5,1,1,-8,8,94,106,-7,-5,0,0,-6,-2,97,102,-9,-7,1,3,2,6,97,102,-9,-7,1,3,-19,-11,110,122,-4,3,1,3,-3,5,116,128,-4,4,1,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[136] = {-12,12,0,5,-8,-7,0,0,-11,11,0,30,-7,7,1,2,-13,13,28,86,-5,5,1,3,-22,-16,6,114,-3,3,0,1,-16,-8,60,68,-4,2,0,3,-11,11,62,68,-8,-7,0,3,-11,11,56,80,-7,-5,0,0,11,29,78,86,3,8,0,0,-12,12,82,92,-6,6,1,1,8,32,88,100,2,8,0,0,-11,11,90,112,-6,6,0,3,-11,11,96,101,-8,-6,0,0,24,30,106,114,-2,2,1,2,-12,12,108,120,-7,6,0,0,-32,-6,112,121,-5,5,0,0,-12,-6,118,125,-3,3,1,2,-29,-9,119,128,-4,4,1,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-3,3,0,10,-7,-6,0,0,-14,14,0,26,-6,6,0,3,-30,-10,22,36,-5,1,0,0,-23,-17,26,32,-7,-5,1,3,-27,-20,40,52,2,6,0,2,-11,11,24,74,-5,5,0,3,-21,-17,44,56,-3,0,0,1,-11,11,48,54,-7,-5,1,1,-18,-11,54,64,-5,1,0,3,2,8,70,92,6,10,0,2,-12,12,72,94,-5,5,0,3,-12,12,92,98,-7,-5,1,2,-9,9,90,122,-6,6,0,2,-6,-2,99,104,-10,-8,0,2,2,6,99,104,-10,-8,0,2,-8,8,96,110,-8,-6,0,0,-6,6,118,128,-4,4,0,2};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-12,-4,0,7,-7,7,0,0,4,12,0,7,-7,7,0,0,-10,-4,5,50,-5,5,0,3,4,10,5,50,-5,5,0,3,-18,-14,28,70,-4,2,0,2,-12,12,46,60,-8,8,1,1,-13,13,30,88,5,10,1,2,18,22,4,128,2,8,0,1,-12,12,58,64,-9,-8,0,0,-19,-13,68,82,-5,2,0,3,-13,13,62,94,-8,8,1,3,-10,-2,72,102,7,12,0,0,-11,11,68,88,-10,-8,0,1,16,36,88,98,3,9,1,2,-15,-9,90,99,-6,6,0,1,9,15,90,99,-6,6,0,1,-11,11,93,101,-7,7,0,0,18,38,100,124,3,9,1,3,-9,9,99,118,-7,6,0,3,-9,9,104,109,-9,-7,0,0,-9,9,114,124,-8,7,0,2,-2,2,120,128,-6,6,1,2,-6,6,118,121,-10,-7,0,0};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-1,21,0,5,-5,5,0,0,-25,-3,0,5,-7,3,0,0,-18,-10,0,28,-6,4,0,3,6,14,0,36,-4,6,0,3,-28,-20,20,27,-8,-2,0,2,18,26,24,31,-6,0,0,2,-23,-17,25,31,-8,-2,0,0,15,21,29,35,-6,0,0,0,-22,-14,30,42,-7,-1,0,3,12,20,34,46,-5,3,0,3,-14,14,32,50,-8,6,1,2,-2,2,32,44,-9,-8,0,0,-9,9,48,82,-6,5,1,3,-10,14,44,98,5,11,0,1,-9,9,60,66,-8,-6,0,0,6,14,66,88,8,13,0,0,-9,9,80,87,-7,6,1,1,-11,11,84,116,-6,7,0,1,-11,11,92,104,-8,-6,0,0,-6,-2,95,100,-10,-8,0,3,2,6,95,100,-10,-8,0,3,-12,10,114,122,-4,4,0,1,-5,3,112,128,-4,4,0,1};
inline constexpr short grandleon_playstation_mesh_beast[184] = {7,13,0,40,2,9,0,1,-13,-7,0,40,2,9,0,1,10,16,0,44,-12,-4,0,2,-17,-10,0,44,-12,-4,0,2,23,28,40,50,-3,2,1,3,17,25,44,54,-4,3,0,2,7,21,40,66,-8,5,0,2,5,9,36,60,-12,-9,0,3,-2,3,36,60,-12,-9,0,3,-9,-4,36,60,-12,-9,0,3,-23,-9,42,68,-8,5,0,2,-12,8,58,68,-7,2,0,3,-5,13,64,74,-8,3,1,1,-5,2,72,80,-5,1,1,3,-25,-17,74,82,-9,-3,1,2,-24,-17,64,100,-5,2,0,3,-32,-8,87,105,-5,2,0,3,-24,-20,102,107,-9,-7,0,0,-34,-10,98,118,-9,0,0,3,-29,-23,108,116,-6,0,0,1,-30,-14,107,112,-11,-8,0,0,-28,-21,113,117,-8,-6,0,0,-25,-19,116,128,-6,0,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,16,16,17,17,23,23,23};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,21,20,29,21,27,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {545,417,385,531,405,560,394,391};
