// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-15,-1,0,5,-6,5,0,1,0,14,0,5,-6,5,0,1,-10,-5,3,25,-3,3,1,3,4,9,3,25,-3,3,1,2,-10,9,19,50,3,6,0,2,-10,-4,23,41,-4,4,1,3,3,9,23,41,-4,4,0,1,-11,10,40,46,-6,6,0,2,-30,-13,29,63,-3,3,0,1,-24,-19,43,50,-4,-3,1,3,-12,11,44,68,-6,6,0,1,12,18,54,63,-3,2,0,1,-10,9,48,63,-8,-6,0,2,-30,-13,58,62,-4,-3,0,2,8,26,63,68,-3,1,0,1,-11,10,66,71,-6,6,0,1,15,18,66,87,-2,2,0,2,-11,10,70,85,-6,6,0,1,-10,9,74,78,-7,-6,0,0,-6,-2,75,77,-8,-7,0,1,1,5,75,77,-8,-7,0,1,-3,2,83,88,-2,2,0,1};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-10,-4,0,27,-4,4,0,1,4,10,0,27,-4,4,1,2,19,24,6,47,-3,1,0,0,-11,11,26,37,-4,4,0,2,-11,11,21,54,4,6,1,1,-11,11,36,39,-5,-4,0,2,18,25,44,53,-4,1,0,0,-3,3,37,69,-4,4,0,2,-11,11,49,52,-6,-4,0,0,-16,-9,43,69,2,6,0,3,10,18,50,56,-4,1,0,2,-11,11,43,66,-4,4,0,2,-11,11,56,59,-6,-4,0,3,19,24,47,87,-3,1,0,0,-14,-10,66,77,3,6,0,0,-10,10,67,72,-5,4,0,3,-9,9,69,73,-6,-5,0,1,-9,9,72,87,-5,4,0,2,-9,9,76,79,-6,-5,0,2,-4,4,84,92,-4,4,0,0};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-13,13,0,6,-5,-4,1,2,-7,7,0,23,-5,5,1,2,14,18,3,84,-2,2,0,1,-12,12,21,70,-4,4,1,2,-12,12,41,46,-5,-4,1,3,8,15,47,53,-3,2,0,2,-10,10,53,59,-5,-4,1,3,-14,-8,66,73,-4,4,0,0,-8,8,70,91,-4,4,1,2,-7,7,75,84,-5,-4,0,2,-7,-2,77,81,-7,-5,1,2,2,7,77,81,-7,-5,0,1,12,20,82,93,-4,3,0,3,13,19,85,88,-5,-4,0,0,-5,1,90,97,-3,3,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-10,10,0,4,-5,-4,0,1,-9,9,0,17,-5,5,1,2,-30,-8,26,31,0,4,0,2,-14,14,13,52,3,6,0,3,-13,13,30,34,-5,-4,0,2,-12,12,15,57,-4,4,0,2,16,22,3,72,-2,2,0,2,-33,-11,36,43,0,4,0,1,-12,12,39,43,-5,-4,0,2,9,17,41,46,-3,1,0,0,-9,9,55,60,-5,-4,0,0,-9,9,57,62,-5,-4,0,3,-10,10,59,74,-4,4,0,3,26,32,65,70,-1,1,1,2,-10,10,63,67,-5,-4,0,2,8,30,71,77,-4,4,0,1,-10,10,72,77,-3,3,0,2,10,28,76,83,-3,3,0,2,8,14,77,82,-4,0,0,0};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-14,14,0,4,-5,-4,0,1,-13,13,0,23,-4,4,0,2,12,30,17,27,-3,1,1,2,18,24,20,24,-5,-3,0,3,19,23,26,32,-2,0,0,3,20,27,30,38,1,4,0,0,18,22,32,39,-2,0,0,3,-12,12,22,52,-4,4,0,3,-4,4,5,65,-6,-5,0,3,12,19,38,44,-3,1,0,2,-13,13,51,65,-4,4,0,2,-7,-2,67,71,-7,-5,0,2,2,7,67,71,-7,-5,0,2,-9,9,62,83,-5,3,0,3,-8,8,65,75,-8,-7,0,2,-6,6,81,86,-3,3,0,0};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-18,2,0,6,-5,5,0,1,-2,18,0,6,-5,5,0,1,-11,-5,4,39,-4,4,0,2,5,11,4,39,-4,4,0,3,-15,15,1,61,4,8,1,2,17,21,22,54,-3,1,0,2,-15,15,36,47,-6,6,0,1,-22,-18,1,93,1,6,0,2,-14,14,45,49,-7,-6,0,0,15,22,51,61,-4,1,0,3,-15,15,48,71,-7,7,0,1,-39,-15,61,68,2,7,0,2,-12,12,52,67,-8,-7,0,2,-18,-10,67,74,-4,4,0,3,10,18,67,74,-4,4,0,0,-13,13,70,76,-6,6,0,3,-9,9,72,73,-8,-6,0,1,-37,-19,70,89,2,7,0,2,-13,13,74,89,-5,5,0,1,-11,11,79,82,-7,-6,0,3,-12,12,79,83,-7,-5,0,2,-10,10,87,91,-4,4,0,2,-3,3,87,93,-4,4,0,0};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {2,24,0,4,-2,5,0,1,-27,-5,0,4,-5,1,0,0,4,22,0,18,-1,5,0,1,-20,-12,0,20,-5,1,0,2,-30,-22,8,13,-5,-2,0,0,-25,-19,12,16,-5,-2,0,1,-24,-16,14,22,-5,-1,0,1,-15,13,18,28,-4,3,0,1,-11,11,31,34,-5,-4,0,3,-11,11,26,48,-4,3,0,2,-15,11,24,58,3,7,0,3,-3,4,28,48,-5,-4,0,2,12,20,46,55,-3,2,0,3,13,21,53,56,-3,2,0,0,-12,12,50,68,-4,4,0,1,-11,11,55,62,-5,-4,0,1,-7,-2,57,60,-6,-5,1,3,2,7,57,60,-6,-5,1,3,15,19,55,77,-2,1,0,0,-22,0,65,73,1,5,0,1};
inline constexpr short grandleon_playstation_mesh_beast[168] = {8,15,0,22,1,5,0,3,-15,-8,0,22,1,5,0,1,12,19,0,24,-6,-2,0,1,-19,-12,0,24,-6,-2,0,3,6,11,19,32,-6,-5,0,3,-2,3,19,32,-6,-5,0,3,-10,-5,19,32,-6,-5,0,1,8,24,22,35,-4,3,0,1,-26,-10,23,37,-4,3,0,3,-15,9,31,37,-4,1,0,3,20,27,31,45,-2,2,0,1,-6,2,35,41,-3,1,0,3,-35,-13,40,44,-5,-2,0,3,-28,-20,34,54,-3,1,0,3,23,29,44,51,-2,1,0,2,-38,-10,47,56,-3,1,0,3,-39,-11,53,63,-4,1,1,2,-28,-23,55,58,-5,-4,0,0,-34,-26,58,62,-3,0,0,0,-32,-24,61,63,-4,-3,0,0,-29,-21,62,69,-3,0,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,20,15,19,16,23,20,21};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,22,20,31,22,27,28,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {563,436,397,546,423,579,409,408};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,26,28,24,25,28,23,20};
