// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-12,-4,0,5,-5,5,0,0,4,12,0,5,-5,5,0,0,-11,-4,3,27,-3,3,0,3,4,11,3,27,-3,3,0,3,-12,12,27,31,-6,-5,0,0,-12,12,27,42,-5,5,1,2,-31,-25,40,46,-4,-3,0,3,-38,-18,31,60,-3,3,1,2,-13,13,41,64,-5,5,1,3,15,22,49,59,-3,1,0,3,-11,11,45,60,-7,-5,0,1,4,12,53,74,4,8,0,1,-12,12,63,68,-5,5,0,0,17,21,57,83,-2,2,0,2,-13,13,66,78,-5,5,0,3,-12,12,70,74,-7,-5,0,0,-12,12,75,81,-6,5,0,1,-10,10,78,87,-5,5,0,2};
inline constexpr short grandleon_playstation_mesh_archer[128] = {-9,-3,0,25,-3,3,0,3,3,9,0,25,-3,3,0,3,-12,12,24,28,-6,-5,0,0,-11,11,24,39,-5,5,1,2,-10,10,38,41,-5,-4,0,0,-22,-17,7,82,-3,1,0,2,-23,-16,41,49,-3,1,1,1,9,16,41,64,2,6,0,1,-10,10,46,50,-6,-4,0,3,-11,11,38,64,-4,4,1,2,-16,-9,48,53,-3,1,0,3,-12,-5,53,73,3,7,0,0,-11,11,63,67,-5,4,1,3,-10,10,67,82,-5,4,0,3,-9,9,71,75,-6,-5,0,0,-5,5,80,89,-4,5,0,0};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-12,12,0,18,-5,5,1,2,-15,15,17,21,-5,-4,0,0,-11,11,18,69,-4,4,1,3,-12,12,39,44,-5,-4,1,1,-17,-13,5,88,-2,2,0,3,-14,-7,46,52,-3,2,0,3,-4,4,51,55,-6,-5,0,3,-9,9,46,65,-5,-4,0,0,-9,11,54,74,4,8,0,0,-11,11,66,71,-5,-4,0,0,-8,8,68,91,-4,4,1,1,-8,8,72,82,-5,-4,0,0,-6,-2,75,79,-7,-5,1,3,2,6,75,79,-7,-5,1,3,-19,-11,85,94,-3,2,1,3,-3,5,89,99,-3,3,1,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[136] = {-12,12,0,3,-5,-4,0,0,-11,11,0,19,-5,5,1,2,-13,13,18,55,-3,3,1,3,-22,-16,4,74,-2,2,0,1,-16,-8,39,44,-3,1,0,3,-11,11,40,44,-5,-4,0,3,-11,11,36,52,-5,-3,0,0,11,29,50,55,2,5,0,0,-12,12,53,59,-4,4,1,1,8,32,57,65,1,5,0,0,-11,11,58,72,-4,4,0,3,-11,11,62,65,-5,-4,0,0,24,30,68,74,-1,1,1,2,-12,12,70,77,-5,4,0,0,-32,-6,72,78,-3,3,0,0,-12,-6,76,81,-2,2,1,2,-29,-9,77,83,-3,3,1,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-3,3,0,7,-5,-4,0,0,-14,14,0,18,-4,4,0,3,-30,-10,15,24,-3,1,0,0,-23,-17,18,22,-5,-3,1,3,-27,-20,27,35,1,4,0,2,-11,11,16,50,-3,3,0,3,-21,-17,30,38,-2,0,0,1,-11,11,33,37,-5,-3,1,1,-18,-11,37,44,-3,1,0,3,2,8,48,63,4,7,0,2,-12,12,49,64,-3,3,0,3,-12,12,63,67,-5,-3,1,2,-9,9,61,83,-4,4,0,2,-6,-2,67,71,-7,-5,0,2,2,6,67,71,-7,-5,0,2,-8,8,65,75,-5,-4,0,0,-6,6,80,87,-3,3,0,2};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-12,-4,0,5,-5,5,0,0,4,12,0,5,-5,5,0,0,-10,-4,4,36,-4,4,0,3,4,10,4,36,-4,4,0,3,-18,-14,20,51,-3,1,0,2,-12,12,33,44,-6,6,1,1,-13,13,22,64,4,7,1,2,18,22,3,93,1,6,0,1,-12,12,42,47,-7,-6,0,0,-19,-13,49,60,-4,1,0,3,-13,13,45,68,-6,6,1,3,-10,-2,52,74,5,9,0,0,-11,11,49,64,-7,-6,0,1,16,36,64,71,2,7,1,2,-15,-9,65,72,-4,4,0,1,9,15,65,72,-4,4,0,1,-11,11,68,73,-5,5,0,0,18,38,73,90,2,7,1,3,-9,9,72,86,-5,4,0,3,-9,9,76,79,-7,-5,0,0,-9,9,83,90,-6,5,0,2,-2,2,87,93,-4,4,1,2,-6,6,86,88,-7,-5,0,0};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-1,21,0,3,-3,3,0,0,-25,-3,0,3,-4,2,0,0,-18,-10,0,18,-4,3,0,3,6,14,0,23,-3,4,0,3,-28,-20,13,17,-5,-1,0,2,18,26,15,19,-4,0,0,2,-23,-17,16,19,-5,-1,0,0,15,21,18,22,-4,0,0,0,-22,-14,19,26,-4,-1,0,3,12,20,21,29,-3,2,0,3,-14,14,20,31,-5,4,1,2,-2,2,20,28,-6,-5,0,0,-9,9,30,51,-4,3,1,3,-10,14,28,61,3,7,0,1,-9,9,38,41,-5,-4,0,0,6,14,41,55,5,8,0,0,-9,9,50,54,-4,4,1,1,-11,11,53,73,-4,4,0,1,-11,11,58,65,-5,-4,0,0,2,6,59,63,-8,-7,0,3,-6,-2,59,63,-8,-7,0,3,-12,10,71,76,-3,3,0,1,-5,3,70,80,-3,3,0,1};
inline constexpr short grandleon_playstation_mesh_beast[184] = {-13,-7,0,22,1,5,0,1,7,13,0,22,1,5,0,1,-16,-10,0,24,-6,-2,0,2,10,17,0,24,-6,-2,0,2,-28,-23,22,27,-2,1,1,3,-25,-17,24,29,-2,2,0,2,-9,-5,19,32,-6,-5,0,3,-3,2,19,32,-6,-5,0,3,4,9,19,32,-6,-5,0,3,-21,-7,22,35,-4,3,0,2,9,23,23,37,-4,3,0,2,-8,12,31,37,-4,1,0,3,-13,5,34,40,-4,2,1,1,-2,5,39,43,-3,1,1,3,17,25,40,44,-5,-2,1,2,17,24,34,54,-3,1,0,3,8,32,47,56,-3,1,0,3,20,24,55,58,-5,-4,0,0,10,34,53,63,-5,0,0,3,23,29,58,62,-3,0,0,1,14,30,58,60,-6,-4,0,0,21,28,61,63,-4,-3,0,0,19,25,62,69,-3,0,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,16,16,17,17,23,23,23};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,21,20,29,21,27,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {545,417,385,531,405,560,394,391};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,26,28,24,25,28,23,20};
