// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-21,1,0,5,-5,5,0,1,-1,21,0,5,-5,5,0,1,-13,-6,5,27,-4,4,0,1,6,13,5,27,-4,4,0,1,-17,17,26,42,-6,6,1,1,-30,-25,1,75,0,4,0,1,-16,16,45,49,-7,-5,0,0,-16,16,40,62,-5,5,1,2,-32,-4,49,56,-3,3,0,1,-32,-4,55,58,-5,5,1,3,4,32,55,58,-5,5,1,3,-4,4,51,75,5,8,0,0,-27,-9,55,66,-5,5,0,1,9,27,55,66,-5,5,0,1,-9,9,65,74,-7,-1,0,3,-34,-22,75,83,0,4,0,3,-8,8,73,77,-8,-3,0,0,-7,7,74,83,-5,5,0,0};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,6,-5,5,0,1,3,11,0,6,-5,5,0,1,-10,-3,6,29,-4,4,1,1,3,10,6,29,-4,4,1,1,-21,-17,16,42,1,6,0,1,-11,11,32,44,-6,6,1,1,-17,-10,45,51,-4,4,0,2,12,18,41,64,4,9,0,1,-11,11,42,67,-5,5,1,2,-10,10,49,54,-7,-5,0,0,-3,3,48,76,4,8,0,0,12,18,64,73,6,10,0,3,-24,-19,42,93,1,6,0,1,-11,11,65,77,-8,-1,0,3,-7,7,71,73,-9,-7,0,0,-9,9,74,87,-4,4,0,0,-8,8,83,86,-6,-4,1,3};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-16,16,0,6,-7,7,1,3,-11,11,0,39,-6,6,1,1,9,15,39,57,-5,5,1,1,-15,-9,39,57,-5,5,1,1,-8,8,42,48,-8,-5,0,2,-10,10,38,68,-5,5,1,2,-3,3,47,75,5,9,0,0,-3,3,45,62,-9,-7,0,3,-11,11,65,68,-8,-5,0,0,-10,10,68,80,-8,-1,0,3,5,8,69,83,-6,3,0,0,-8,-5,69,83,-6,3,0,0,-7,7,73,76,-10,-8,0,0,-22,-16,74,87,-2,3,0,3,-9,9,78,84,-5,4,0,0,-4,4,83,96,-3,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[136] = {-16,16,0,14,-7,7,1,1,-18,18,12,38,-5,5,1,2,-10,10,39,47,5,9,1,2,22,26,7,76,-1,3,0,1,-28,-8,38,54,-3,3,0,3,-12,12,42,46,-7,-5,1,3,-10,10,36,62,-5,5,0,3,-4,4,41,68,4,7,0,0,11,19,50,62,-3,2,0,3,19,26,59,65,-2,3,0,2,-9,-6,62,76,-5,3,0,0,6,9,62,76,-5,3,0,0,-13,13,63,74,-7,-1,0,3,-9,9,68,71,-9,-7,0,0,13,37,74,81,-4,4,0,0,-12,12,73,84,-4,4,0,0,15,35,80,86,-3,3,1,3};
inline constexpr short grandleon_playstation_mesh_healer[120] = {-11,-3,0,4,-5,5,0,2,3,11,0,4,-5,5,0,2,-15,15,3,7,-6,6,0,1,-15,15,3,39,-6,6,0,3,-35,-30,10,78,-1,3,0,1,-36,-30,43,49,-2,2,0,2,-16,6,39,53,-7,-5,1,2,11,17,41,59,-4,4,0,3,-13,13,38,64,-5,5,0,3,-10,10,49,67,4,7,0,2,-4,16,52,64,-7,-5,1,2,-11,11,64,67,-8,-7,0,0,-11,11,67,77,-8,-1,0,3,-12,12,64,85,-6,4,0,2,-27,-9,77,89,-1,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[168] = {-3,19,0,5,-5,5,0,1,-19,3,0,5,-5,5,0,1,3,10,5,26,-4,4,0,1,-10,-3,5,26,-4,4,0,1,-13,13,25,41,-5,5,1,1,-26,-6,30,34,-7,-5,0,3,-13,13,26,59,5,8,1,2,-12,12,43,47,-7,-5,1,3,-12,12,39,63,-5,5,0,1,-4,4,46,68,3,6,0,0,-12,-7,44,84,8,11,0,1,11,16,55,64,-4,4,0,1,-16,-11,55,64,-4,4,0,1,-10,10,63,69,-3,5,0,0,-12,10,64,81,8,11,1,2,-9,9,69,75,7,8,0,3,-7,7,65,67,-8,-7,0,3,-8,8,64,73,-7,-1,0,3,-10,10,72,82,-4,4,0,0,10,14,75,84,-2,1,0,3,-14,-10,75,84,-2,1,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-16,-8,0,21,-5,3,0,1,8,16,0,21,-5,3,0,1,-14,-7,19,31,-5,3,0,1,7,14,19,31,-5,3,0,1,-11,11,28,39,-6,3,0,1,-10,10,36,41,-7,-4,1,3,-18,-11,40,52,-5,0,0,2,11,18,40,52,-5,0,0,2,-8,8,40,58,-5,3,0,1,-3,3,45,63,3,6,0,0,-9,9,48,61,3,6,0,2,-7,7,43,54,-7,-5,0,0,-21,-14,48,53,-5,-1,0,2,14,21,48,53,-5,-1,0,2,-9,9,57,62,-6,1,0,0,-29,-24,53,68,-5,-1,0,3,24,29,53,68,-5,-1,0,3,-10,10,61,75,-4,3,0,1,-9,9,63,68,-7,-4,0,3,-7,7,66,70,-10,-8,0,3,-6,6,72,83,-2,3,0,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {7,13,0,24,2,7,0,0,-14,-8,0,24,2,7,0,0,-11,-5,0,24,-7,-2,0,1,10,16,0,24,-7,-2,0,1,-14,16,20,39,-7,5,0,1,4,26,22,38,-6,4,0,2,-26,-5,30,42,-1,4,0,1,11,32,31,37,-5,-1,0,3,23,26,32,35,-6,-2,0,0,10,15,30,34,-10,-7,0,3,1,23,33,39,-8,4,1,3,-10,12,37,41,-7,4,1,2,7,28,32,45,-8,-1,0,2,11,25,37,41,-9,-8,0,0,-22,-16,40,59,-1,4,0,2,12,16,44,55,-2,2,0,1,17,21,44,55,-2,2,0,1,1,28,48,54,-2,2,0,1,-22,-18,57,76,0,5,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,17,16,17,15,21,21,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 21;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {31,21,19,30,23,22,25,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {464,472,374,507,471,501,352,460};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,28,28,26,26,28,24,24};
