// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-17,1,0,7,-7,7,0,0,-2,16,0,7,-7,7,0,0,-12,-6,18,30,5,13,0,0,-10,-5,7,36,-6,6,0,1,4,10,7,36,-6,6,0,1,-12,11,34,54,-9,9,1,2,-11,10,50,57,-11,-8,0,0,-11,10,52,90,-8,8,0,1,-26,-5,42,92,-14,-10,0,2,-25,-6,50,84,-17,-14,1,1,14,17,76,84,-5,1,0,1,7,24,82,88,-5,-1,0,0,-3,3,84,112,9,17,0,0,-13,-8,86,97,-7,7,0,2,7,13,86,97,-7,7,0,2,14,17,84,128,-5,-1,0,3,-11,10,96,120,-8,8,0,3,-10,-7,98,122,-6,8,0,0,7,10,98,122,-6,8,0,0,-3,3,99,108,-13,-8,0,3,-2,1,101,105,-15,-13,0,0,-9,-5,118,127,-1,6,0,0,4,9,118,127,-1,6,0,0,-18,4,122,127,-1,6,0,0,-11,10,114,124,-11,-8,0,0};
inline constexpr short grandleon_playstation_mesh_archer[176] = {-9,-2,0,7,-8,6,0,0,4,10,0,7,-8,6,0,0,-8,-3,7,34,-5,5,0,2,5,10,7,34,-5,5,0,2,9,27,22,32,5,13,0,2,22,28,30,48,7,15,0,3,-20,-14,10,60,-6,0,0,1,-10,12,32,56,-8,8,1,3,-9,11,52,58,-9,-7,0,0,-7,9,54,86,-7,7,1,2,-11,-5,68,100,6,14,0,1,8,14,70,78,-11,-4,0,2,-13,-7,68,86,-8,-1,0,2,-6,8,90,110,7,12,0,0,-20,-14,60,128,-6,0,0,1,-7,7,88,108,-7,7,0,2,-2,3,91,100,-12,-7,0,3,-1,2,93,97,-14,-12,0,0,-6,8,104,112,-10,-7,0,0,-10,2,110,119,-1,6,0,2,-6,-1,106,124,-1,6,0,2,2,7,106,124,-1,6,0,2};
inline constexpr short grandleon_playstation_mesh_mage[176] = {-16,16,0,14,-9,9,0,1,-20,-14,0,56,-5,1,0,1,-14,14,12,54,-8,8,0,1,-4,4,12,88,-11,-8,1,3,-13,13,52,60,-10,-8,1,3,-11,11,58,88,-8,8,0,2,9,15,60,84,-7,3,0,2,-15,-9,60,84,-7,1,0,2,-20,-14,56,112,-5,1,0,1,-12,12,80,108,8,14,0,0,-12,12,84,90,-11,-8,0,3,-12,12,90,110,-7,7,0,2,-3,3,94,102,-12,-7,0,1,-2,2,95,99,-14,-12,0,0,-14,14,108,114,-8,8,0,0,-13,13,106,112,-10,-7,0,0,-14,-6,112,121,-1,6,0,3,6,14,112,121,-1,6,0,3,-29,-5,108,120,-6,2,0,2,-12,-8,119,128,-1,6,0,3,8,12,119,128,-1,6,0,3,-14,-6,122,127,-1,6,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[176] = {-11,11,0,18,-9,9,1,2,-8,8,16,52,-8,8,1,2,-4,4,16,84,-10,-7,1,3,-6,6,48,55,-10,-7,0,0,-38,-32,0,114,-4,2,0,1,-9,9,50,84,-7,7,0,2,8,14,56,82,-6,2,0,2,-16,-8,58,86,-6,2,0,2,-10,10,78,104,8,14,0,0,24,32,86,94,-4,6,0,3,-10,10,82,88,-10,-7,1,3,-11,11,86,106,-7,7,0,2,-3,3,90,97,-11,-7,0,0,18,26,98,106,0,8,1,3,28,34,102,110,-2,4,0,3,-10,-4,104,114,-1,7,0,2,4,10,104,114,-1,7,0,2,-19,5,109,114,-1,7,0,2,-13,13,102,110,-9,-7,0,0,-29,-11,112,120,-7,5,0,0,-29,-11,118,128,-5,3,0,3,-22,-4,116,124,-8,-5,1,3};
inline constexpr short grandleon_playstation_mesh_healer[152] = {-14,14,0,14,-9,9,0,2,-13,13,12,50,-8,8,0,2,-11,11,12,50,-11,-8,1,3,-31,-7,42,56,-6,4,0,1,-14,14,44,51,-10,-8,1,3,-31,-7,54,60,-7,5,0,0,-23,-15,58,68,-5,3,0,1,-14,14,46,82,-8,8,1,2,-13,-8,50,76,-6,2,0,2,11,16,54,80,-7,2,0,2,-3,3,70,100,9,15,0,1,-11,11,82,102,-7,7,0,2,-3,3,85,93,-12,-7,0,3,-2,2,87,91,-14,-12,0,0,-12,-6,100,110,-2,5,0,2,6,12,100,110,-2,5,0,2,-11,11,94,118,-4,10,1,2,-10,10,98,106,-9,-7,0,1,-9,9,114,128,-1,8,1,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-7,-1,0,7,-8,8,0,1,4,11,0,7,-8,8,0,1,-6,-1,7,34,-5,5,0,1,5,10,7,34,-5,5,0,1,-10,13,4,78,7,14,1,1,-10,13,32,58,-9,9,1,3,19,24,0,114,3,9,0,1,-8,12,54,61,-11,-9,0,3,-8,12,58,94,-8,8,0,1,-1,5,66,86,-11,-8,1,3,-1,4,80,104,8,16,0,0,20,36,84,110,2,10,1,2,-11,-6,88,99,-8,6,0,2,9,15,88,99,-8,6,0,2,26,31,92,102,0,2,0,3,-8,12,98,118,-7,7,0,2,-7,11,100,108,-10,-7,0,0,18,25,112,124,3,9,0,3,-8,-4,112,122,-2,5,0,1,8,12,112,122,-2,5,0,1,-16,3,118,123,-2,5,0,1,0,3,116,128,-9,6,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-12,-5,0,8,-8,3,0,2,5,12,0,8,-8,3,0,2,14,30,18,28,4,12,0,1,-11,-6,8,32,-8,1,0,2,6,11,8,32,-8,1,0,2,24,32,26,42,6,14,0,3,-14,14,30,52,-8,6,1,3,-12,12,50,57,-10,1,0,0,-11,11,55,84,-8,6,1,3,-15,-9,58,80,-11,-2,0,2,9,15,58,80,-11,-2,0,2,-18,-10,76,82,-9,-5,0,0,10,18,76,82,-9,-5,0,0,-4,4,86,108,9,15,0,0,-25,-21,80,104,-9,-5,0,3,12,16,80,104,-9,-5,0,3,-7,7,88,108,-7,7,0,2,-3,3,91,99,-12,-7,0,3,-9,9,90,114,-4,9,0,1,-2,2,93,97,-14,-12,0,0,-8,8,104,110,-9,-7,0,0,-7,7,110,122,1,9,0,1,-7,-2,112,128,-1,5,0,2,2,7,112,128,-1,5,0,2,-9,1,120,128,-1,5,0,2};
inline constexpr short grandleon_playstation_mesh_beast[152] = {10,16,0,40,7,15,0,0,-8,-3,0,40,7,15,0,0,10,16,0,40,-15,-7,0,1,-8,-3,0,40,-15,-7,0,1,-11,11,36,46,-14,14,0,2,14,18,44,62,-3,5,0,1,-12,16,36,72,-13,13,0,1,-34,-14,46,60,-16,-6,0,2,-29,-7,42,78,-11,9,0,1,17,21,58,70,-1,7,0,0,-27,-23,56,66,-6,0,0,3,-25,-21,52,62,-18,-14,0,3,-20,-15,66,72,-13,-11,0,0,-19,-14,76,88,2,8,0,1,-19,-14,76,88,-8,-2,0,1,4,8,70,102,-3,3,1,3,-4,0,70,118,-3,3,1,3,-23,5,82,111,-3,3,1,3,-12,-8,70,128,-3,3,1,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,22,22,22,19,22,25,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,24,20,32,20,26,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {472,485,471,531,487,569,415,425};
