// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-13,-5,0,7,-6,6,0,1,5,13,0,7,-6,6,0,1,-12,-5,6,31,-5,5,0,1,5,12,6,31,-5,5,0,1,-13,13,30,39,-6,6,0,0,-5,5,31,36,-8,-6,0,3,-22,-8,27,42,-11,-7,0,1,-25,-6,36,40,-13,-11,0,3,-12,12,37,63,-6,6,1,2,-12,12,44,49,-9,-7,1,0,-19,-12,44,60,-4,4,0,2,-25,-6,39,57,-11,-7,0,1,12,19,49,66,-4,4,0,2,-19,-9,44,56,-14,-12,1,3,-12,12,54,59,-9,-7,1,0,16,22,60,69,-6,-1,0,1,-22,-8,56,69,-11,-7,0,1,-16,-8,70,77,4,9,1,1,-9,9,63,79,-5,5,0,2,-8,8,69,73,-7,-6,0,0,20,26,67,87,-4,1,0,3,-11,11,77,92,-6,1,1,2};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-13,-5,0,7,-5,5,0,1,5,13,0,7,-5,5,0,1,-12,-5,5,30,-5,5,0,1,5,12,5,30,-5,5,0,1,-13,13,19,28,-7,7,0,1,-14,14,27,43,-6,6,1,2,-18,-12,42,56,-4,4,0,2,12,18,43,59,-4,4,0,2,-12,12,42,63,-6,6,0,1,10,17,56,63,4,7,1,3,-5,5,43,63,-8,-7,0,1,0,28,52,59,-8,-4,0,1,-30,2,54,58,-8,-5,0,3,10,17,63,73,3,8,0,1,-4,6,58,62,-10,-7,0,0,-9,9,59,75,-5,5,0,2,-8,8,66,69,-7,-5,0,0,-11,11,73,86,-5,3,0,1};
inline constexpr short grandleon_playstation_mesh_mage[128] = {2,8,0,5,-5,3,0,1,-11,-3,0,7,-5,4,0,1,3,8,4,29,-4,3,0,1,-10,-3,5,31,-5,4,0,1,-11,11,20,41,-5,5,1,1,10,17,27,35,-8,-4,0,3,10,15,35,51,-4,4,0,2,-10,10,40,47,-6,6,0,0,-15,-10,37,53,-4,4,0,2,-10,10,45,67,-5,5,1,2,-4,4,44,67,-7,-6,1,0,-18,-10,51,80,-4,4,0,1,10,18,51,80,-4,4,0,1,-8,8,59,75,-5,5,0,2,-7,7,67,69,-7,-5,1,3,-11,11,75,85,-4,5,0,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[192] = {-13,-5,0,6,-5,5,0,1,5,13,0,6,-5,5,0,1,-12,-5,5,27,-4,4,0,1,5,12,5,27,-4,4,0,1,-13,13,17,26,-6,6,0,1,26,32,0,49,0,5,0,1,15,21,0,49,-4,1,0,1,-14,14,25,32,-5,5,0,0,-18,-12,29,46,-4,4,0,2,12,18,31,49,-4,4,0,2,-12,12,31,56,-5,5,1,2,-19,-13,39,52,-7,-5,0,1,14,32,47,52,-4,5,0,1,12,18,51,59,-6,-1,0,1,16,30,54,57,-7,-4,0,3,30,34,52,59,-8,-3,0,3,-17,-11,51,61,-7,-5,0,1,22,32,61,68,1,7,0,3,-9,9,55,70,-4,4,0,2,-8,8,61,64,-6,-5,0,0,-16,-12,60,63,-9,-7,0,3,24,34,70,80,7,14,0,3,-11,11,67,78,-5,4,0,1,-10,10,70,73,-6,-5,0,3};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-21,21,0,18,-5,5,0,3,6,11,12,16,-7,-5,0,1,-18,18,16,38,-5,5,0,3,-10,-5,23,27,-7,-6,0,1,14,20,39,60,-4,4,0,2,-13,13,37,63,-5,5,0,3,-20,-14,50,71,-4,4,0,2,-13,13,56,63,-7,-6,1,3,-17,-11,60,67,-5,3,1,3,11,17,60,67,-5,3,1,3,-9,9,60,76,-5,5,0,2,-8,8,67,70,-7,-5,0,0,-25,-13,71,83,-4,3,0,1,-23,-15,73,80,-6,-5,1,3,-11,11,73,87,-5,3,0,3,-26,-12,82,86,-4,3,0,1};
inline constexpr short grandleon_playstation_mesh_commander[160] = {-13,-5,0,7,-6,6,0,1,5,13,0,7,-6,6,0,1,-12,-5,6,28,-5,5,0,1,5,12,6,28,-5,5,0,1,-18,18,26,48,-6,6,1,1,20,26,6,80,4,8,0,1,-19,-12,43,62,-4,4,1,2,12,19,43,62,-4,4,1,2,-13,13,47,72,-6,6,1,2,-5,5,47,70,-8,-6,0,3,-19,-13,61,65,-6,-1,0,2,13,19,61,65,-6,-1,0,2,26,34,67,79,3,12,1,3,-9,9,61,77,-5,5,0,2,28,33,70,74,0,2,0,3,-8,8,67,71,-7,-6,0,0,-16,16,76,80,-4,8,0,0,19,27,79,85,4,8,0,2,-4,4,80,88,1,8,1,3,-9,9,79,87,-5,5,0,1};
inline constexpr short grandleon_playstation_mesh_rogue[144] = {-23,-13,0,6,-5,4,0,1,13,23,0,6,-5,4,0,1,-22,-12,5,27,-5,4,0,1,12,22,5,27,-5,4,0,1,-14,14,26,32,-5,5,1,2,-19,-13,30,45,-4,4,0,2,-13,13,31,53,-5,5,0,3,-13,13,37,41,-7,-5,1,3,-26,-12,47,51,5,10,1,1,13,19,39,54,-4,4,0,2,-13,13,43,47,-7,-5,1,3,-26,-12,53,57,5,10,1,2,-9,9,47,60,-4,4,0,2,15,21,50,56,-5,-1,0,1,-8,8,53,56,-6,-5,0,0,18,26,55,68,-4,0,0,3,-11,11,59,71,-5,2,1,2,-6,6,69,76,-4,4,1,3};
inline constexpr short grandleon_playstation_mesh_beast[136] = {-10,-2,0,5,-6,1,0,2,4,12,0,5,-6,1,0,2,-24,-10,3,12,-2,4,1,1,-8,-3,4,18,-4,1,0,2,5,10,4,18,-4,1,0,2,-18,-4,10,21,-2,4,1,2,-12,2,18,31,-2,4,1,2,-8,16,17,48,-6,7,1,2,-6,12,26,45,-8,-6,1,1,-4,8,36,40,-9,-8,0,3,6,18,44,57,-4,4,1,3,4,24,57,66,-4,6,1,3,16,26,57,62,-6,-3,0,2,9,13,60,63,-5,-4,0,0,22,27,64,76,0,5,0,3,2,7,64,77,-3,3,0,3,12,17,66,82,-1,4,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,18,16,24,16,20,18,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,28,18,25,21,26,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,420,416,503,452,581,434,353};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,25,26,28,25,28,23,25};
