// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[160] = {-13,-3,0,5,-7,7,0,0,3,13,0,5,-7,7,0,0,-12,-4,5,37,-5,5,0,1,4,12,5,37,-5,5,0,1,-12,-3,37,60,-6,6,1,0,3,12,37,60,-6,6,1,0,-13,13,60,71,-8,8,0,0,14,22,57,65,-12,-6,0,1,-18,-11,69,95,-6,6,0,2,11,18,69,95,-6,6,0,2,-11,11,71,97,-7,7,1,3,-23,-9,55,101,-16,-9,1,2,16,20,57,126,-12,-8,0,3,-19,-10,91,105,-8,8,1,2,10,19,91,105,-8,8,1,2,-4,4,95,102,-4,4,0,0,-6,6,101,112,-6,6,0,1,-8,8,105,119,-8,8,0,3,-8,8,107,113,-10,-8,0,0,-2,2,117,128,-7,3,1,3};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,5,-6,6,0,0,3,11,0,5,-6,6,0,0,-10,-4,5,37,-4,4,0,1,4,10,5,37,-4,4,0,1,-10,-3,37,58,-5,5,1,0,3,10,37,58,-5,5,1,0,-20,-15,28,78,-8,-4,0,3,-11,11,58,72,-7,7,1,1,5,12,70,100,7,14,0,1,10,17,70,94,-6,6,0,2,-17,-10,70,96,-6,6,0,2,-10,10,70,98,-6,6,1,3,-21,-14,78,92,-9,-3,0,1,-5,5,100,111,-5,5,0,1,-7,7,104,118,-7,7,1,2,-20,-15,92,128,-8,-4,0,3,-3,3,114,124,1,7,1,2};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-16,16,0,8,-9,9,0,0,-14,14,7,48,-8,8,1,1,-5,5,7,48,-10,-8,1,3,17,22,10,64,-9,-5,0,1,-11,11,46,78,-7,7,1,2,-5,5,46,78,-9,-7,1,3,-15,-11,54,80,-6,6,1,1,11,15,54,80,-7,5,1,1,12,17,62,72,-10,-4,0,2,-6,6,76,92,-6,6,0,2,17,22,64,102,-9,-5,0,1,-15,15,90,98,-8,2,1,2,-10,10,96,110,-6,3,1,3,16,24,100,109,-10,-3,0,3,-6,6,108,120,-5,2,1,3,-2,2,118,128,-4,1,1,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-17,17,0,18,-4,10,1,1,-18,-13,6,32,-10,-6,0,1,-3,3,6,32,-10,-6,0,1,13,18,6,32,-10,-6,0,1,-16,16,4,64,8,16,1,0,-13,13,18,44,-2,8,1,2,-27,27,30,44,-11,-6,1,3,-33,33,44,48,-12,-4,0,2,-10,10,44,72,-2,8,1,3,7,11,48,58,-10,-6,0,3,-17,-9,48,70,-6,2,1,2,9,17,48,70,-6,2,1,2,-12,-8,48,66,-10,-6,0,3,-2,2,48,80,-10,-6,0,3,-7,7,72,90,-3,7,0,1,8,18,84,98,4,12,0,2,-9,9,90,97,-3,9,1,3,-10,-4,98,114,4,12,0,3,4,10,98,114,4,12,0,3,18,27,110,128,12,20,0,2};
inline constexpr short grandleon_playstation_mesh_healer[112] = {-16,16,0,8,-9,9,0,0,-14,14,7,50,-8,8,0,3,-5,5,7,50,-10,-8,1,3,-11,11,48,82,-7,7,0,3,15,20,14,112,-6,-2,0,1,-5,5,48,82,-9,-7,1,3,-15,-11,56,84,-6,6,0,3,11,15,56,84,-7,5,0,3,-13,13,82,92,-8,2,1,3,-6,6,92,108,-6,6,0,2,-7,7,102,118,-5,7,0,3,8,27,112,121,-6,-2,0,2,15,20,112,121,-14,6,0,2,15,20,119,128,-6,-2,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-11,-3,0,5,-7,7,0,0,3,11,0,5,-7,7,0,0,-10,-4,5,36,-5,5,0,1,4,10,5,36,-5,5,0,1,-15,15,4,94,8,16,1,1,-10,-3,36,58,-6,6,0,2,3,10,36,58,-6,6,0,2,-12,12,58,72,-7,7,1,2,19,24,20,122,5,11,0,1,-18,-11,70,94,-6,6,0,2,11,18,70,94,-6,6,0,2,-11,11,72,98,-7,7,1,3,-19,-10,92,104,-8,8,1,2,10,19,92,104,-8,8,1,2,-5,5,98,104,-5,5,0,0,23,34,98,120,-4,18,1,3,-8,8,102,116,-8,8,0,2,-22,-17,90,122,-12,-8,0,3,-8,8,105,111,-10,-8,0,0,-9,9,112,117,-9,9,0,1,-3,3,114,124,-2,12,1,3,18,25,122,128,4,12,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[152] = {-26,-16,0,8,-18,-2,0,0,16,26,0,8,-18,-2,0,0,-25,-17,8,28,-16,-4,0,1,17,25,8,28,-16,-4,0,1,-26,-17,26,44,-22,-8,0,1,17,26,26,44,-22,-8,0,1,-20,-9,44,64,-10,4,0,0,9,20,44,64,-10,4,0,0,-27,-20,44,50,-34,-28,0,3,-24,-14,54,58,-30,-24,0,3,-14,14,60,84,-16,-2,1,1,-21,-14,68,92,-22,-12,0,1,14,21,68,92,-22,-12,0,1,-14,14,84,104,-16,-2,1,3,14,24,88,92,-24,-18,0,3,-18,18,96,106,-12,2,0,1,20,27,96,102,-20,-14,0,3,-12,12,98,110,-28,-16,1,3,-8,8,108,128,-22,-10,0,0};
inline constexpr short grandleon_playstation_mesh_beast[128] = {-19,-10,0,46,6,14,0,0,11,20,0,46,6,14,0,0,-19,-10,0,46,-16,-8,0,1,11,20,0,46,-16,-8,0,1,-34,-29,46,58,1,7,1,3,-34,-25,52,64,0,8,0,1,-27,-19,58,68,-2,8,0,1,-23,19,42,86,-16,14,0,1,14,24,66,96,-10,6,0,1,12,22,78,88,-14,6,1,2,-16,-8,84,98,-5,5,1,3,8,16,84,98,-5,5,1,3,-4,4,86,102,-5,5,1,3,24,31,84,98,-26,-12,0,1,18,30,94,118,-14,0,0,2,19,26,112,128,-6,2,0,0};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {20,17,16,20,14,22,19,16};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {447,461,484,544,447,568,418,478};
