// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-21,1,0,8,-8,8,0,1,-1,21,0,8,-8,8,0,1,-13,-6,8,42,-6,6,0,1,6,13,8,42,-6,6,0,1,-17,17,40,64,-9,9,1,1,-30,-25,2,116,0,6,0,1,-16,16,70,76,-11,-8,0,0,-16,16,62,96,-8,8,1,2,-32,-4,76,86,-5,5,0,1,-32,-4,84,89,-7,7,1,3,4,32,84,89,-7,7,1,3,-4,4,78,116,7,12,0,0,-27,-9,84,102,-7,7,0,1,9,27,84,102,-7,7,0,1,-9,9,100,114,-11,-1,0,3,-8,8,112,118,-12,-5,0,0,-34,-22,116,128,0,6,0,3,-7,7,114,128,-7,7,0,0};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,8,-7,7,0,1,3,11,0,8,-7,7,0,1,-10,-3,8,40,-6,6,1,1,3,10,8,40,-6,6,1,1,-21,-17,22,58,2,8,0,1,-11,11,44,60,-8,8,1,1,-17,-10,62,70,-5,5,0,2,12,18,56,88,6,12,0,1,-11,11,58,92,-7,7,1,2,-10,10,68,74,-10,-7,0,0,-3,3,66,104,6,11,0,0,12,18,88,100,8,14,0,3,-24,-19,58,128,2,8,0,1,-11,11,90,106,-11,-1,0,3,-7,7,97,101,-13,-10,0,0,-9,9,102,120,-6,6,0,0,-8,8,114,118,-8,-6,1,3};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-16,16,0,8,-9,9,1,3,-11,11,0,52,-8,8,1,1,-15,-9,52,76,-6,6,1,1,9,15,52,76,-6,6,1,1,-8,8,56,64,-10,-6,0,2,-10,10,50,90,-7,7,1,2,-3,3,62,100,7,12,0,0,-3,3,60,82,-12,-9,0,3,-11,11,86,90,-10,-7,0,0,-10,10,90,106,-11,-1,0,3,-8,-5,92,110,-8,4,0,0,5,8,92,110,-8,4,0,0,-7,7,97,101,-13,-10,0,0,16,22,98,116,-2,4,0,3,-9,9,104,112,-6,5,0,0,-4,4,110,128,-4,3,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[136] = {-16,16,0,20,-10,10,1,1,-18,18,18,56,-8,8,1,2,-10,10,58,70,8,13,1,2,22,26,10,112,-2,4,0,1,-28,-8,56,80,-5,5,0,3,-12,12,62,68,-10,-7,1,3,-10,10,54,92,-7,7,0,3,-4,4,60,100,6,11,0,0,11,19,74,92,-5,3,0,3,19,26,88,96,-3,4,0,2,-9,-6,92,112,-7,5,0,0,6,9,92,112,-7,5,0,0,-13,13,94,110,-11,-1,0,3,-9,9,101,105,-13,-10,0,0,13,37,110,120,-6,6,0,0,-12,12,108,124,-6,6,0,0,15,35,118,128,-5,5,1,3};
inline constexpr short grandleon_playstation_mesh_healer[120] = {-11,-3,0,6,-7,7,0,2,3,11,0,6,-7,7,0,2,-15,15,4,10,-9,9,0,1,-15,15,4,56,-8,8,0,3,-35,-30,14,112,-2,4,0,1,-36,-30,62,70,-3,3,0,2,-16,6,56,76,-10,-7,1,2,11,17,58,84,-6,6,0,3,-13,13,54,92,-7,7,0,3,-10,10,70,96,6,10,0,2,-4,16,74,92,-10,-7,1,2,-11,11,92,96,-12,-10,0,0,-11,11,96,110,-11,-1,0,3,-12,12,92,122,-8,6,0,2,-27,-9,110,128,-1,5,0,3};
inline constexpr short grandleon_playstation_mesh_commander[168] = {-19,3,0,8,-8,8,0,1,-3,19,0,8,-8,8,0,1,-10,-3,8,40,-6,6,0,1,3,10,8,40,-6,6,0,1,-13,13,38,62,-8,8,1,1,6,26,46,52,-11,-7,0,3,-13,13,40,90,8,13,1,2,-12,12,66,72,-11,-8,1,3,-12,12,60,96,-8,8,0,1,-4,4,70,104,5,9,0,0,7,12,68,128,12,17,0,1,-16,-11,84,98,-6,6,0,1,11,16,84,98,-6,6,0,1,-10,10,96,106,-5,8,0,0,-10,12,98,124,13,17,1,2,-9,9,106,114,11,13,0,3,-7,7,100,103,-13,-10,0,3,-8,8,98,112,-11,-1,0,3,-10,10,110,126,-6,6,0,0,-14,-10,114,128,-3,1,0,3,10,14,114,128,-3,1,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-16,-8,0,32,-7,5,0,1,8,16,0,32,-7,5,0,1,-14,-7,30,48,-7,5,0,1,7,14,30,48,-7,5,0,1,-11,11,44,60,-9,5,0,1,-10,10,56,64,-11,-6,1,3,-18,-11,62,80,-7,0,0,2,11,18,62,80,-7,0,0,2,-8,8,62,90,-8,4,0,1,-3,3,70,98,5,10,0,0,-9,9,74,94,4,10,0,2,-7,7,66,84,-11,-8,0,0,-21,-14,74,82,-8,-2,0,2,14,21,74,82,-8,-2,0,2,-9,9,88,96,-10,2,0,0,-29,-24,82,106,-7,-2,0,3,24,29,82,106,-7,-2,0,3,-10,10,94,116,-6,5,0,1,-9,9,98,106,-11,-6,0,3,-7,7,103,109,-15,-12,0,3,-6,6,112,128,-3,5,0,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-13,-7,0,40,4,12,0,0,8,14,0,40,4,12,0,0,5,11,0,40,-12,-4,0,1,-16,-10,0,40,-12,-4,0,1,-16,14,34,66,-12,8,0,1,-26,-4,38,64,-11,6,0,2,5,26,50,72,-2,6,0,1,-32,-11,52,62,-9,-1,0,3,-15,-10,50,58,-14,-8,0,3,-26,-23,54,60,-10,-4,0,0,-23,-1,56,66,-13,7,1,3,-28,-7,54,76,-10,2,0,2,-12,10,62,70,-12,7,1,2,-25,-11,63,69,-16,-13,0,0,16,22,68,100,-1,7,0,2,-16,-12,74,94,-4,4,0,1,-21,-17,74,94,-4,4,0,1,-28,-1,81,91,-4,4,0,1,18,22,96,128,0,8,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,17,16,17,15,21,21,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 21;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {31,21,19,30,23,22,25,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {464,472,374,507,471,501,352,460};
