// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-15,-1,0,7,-8,7,0,0,0,14,0,7,-8,7,0,0,-10,-5,5,36,-5,5,0,3,4,9,5,36,-5,5,0,3,-10,9,28,72,5,9,1,1,-10,-4,34,60,-6,6,0,2,3,9,34,60,-6,6,0,2,-11,10,58,66,-8,8,0,0,-30,-13,42,92,-4,4,1,2,-24,-19,62,72,-6,-4,0,0,-12,11,64,98,-9,9,1,3,12,18,78,92,-5,3,0,3,-10,9,70,92,-11,-9,0,1,-30,-13,84,90,-6,-4,0,3,8,26,92,98,-4,2,0,1,-11,10,96,103,-8,8,0,0,15,18,96,126,-3,3,0,3,-11,10,101,123,-8,8,0,2,-10,9,107,113,-10,-8,0,0,-6,-2,108,112,-11,-10,0,3,1,5,108,112,-11,-10,0,3,-3,2,121,128,-3,3,0,1};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-10,-4,0,38,-5,5,0,3,4,10,0,38,-5,5,0,3,19,24,8,66,-4,2,0,2,-11,11,36,52,-6,6,1,2,-11,11,30,76,5,9,1,1,-11,11,50,55,-7,-6,0,0,18,25,62,74,-5,1,1,1,-3,3,52,96,-5,5,0,3,-11,11,68,72,-8,-6,0,0,-16,-9,60,96,3,9,0,1,10,18,70,78,-5,1,0,3,-11,11,60,92,-6,6,0,2,-11,11,78,82,-8,-6,0,0,19,24,66,122,-4,2,0,2,-14,-10,92,108,4,8,0,3,-10,10,94,100,-7,6,1,2,-9,9,96,102,-9,-7,0,1,-9,9,100,122,-7,6,0,3,-9,9,106,111,-9,-7,0,0,-4,4,118,128,-6,5,1,1};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-13,13,0,8,-7,-6,0,0,-7,7,0,30,-6,6,1,1,14,18,4,110,-3,3,0,3,-12,12,28,92,-5,5,1,2,-12,12,54,60,-7,-5,0,0,8,15,62,70,-4,2,0,3,-10,10,70,78,-7,-5,0,3,-14,-8,86,96,-5,5,0,1,-8,8,92,120,-5,5,1,1,-7,7,98,110,-7,-5,0,0,-7,-2,101,106,-9,-7,0,3,2,7,101,106,-9,-7,0,3,12,20,108,122,-5,4,0,3,13,19,112,116,-7,-5,0,0,-5,1,118,128,-4,4,1,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-10,10,0,6,-8,-7,0,0,-9,9,0,26,-7,7,1,2,-30,-8,40,48,0,6,0,1,-14,14,20,80,5,10,1,1,-13,13,46,52,-8,-6,0,0,-12,12,24,88,-6,6,1,2,16,22,4,112,-3,3,0,1,-33,-11,56,66,0,6,0,1,-12,12,60,66,-8,-6,0,3,9,17,64,72,-4,2,0,3,-9,9,86,93,-7,-6,0,0,-9,9,88,96,-8,-6,0,1,-10,10,92,114,-6,6,0,3,26,32,100,108,-2,2,1,2,-10,10,98,104,-8,-6,0,0,8,30,110,120,-6,6,0,0,-10,10,112,120,-5,5,0,1,10,28,118,128,-4,4,1,3,8,14,120,127,-3,3,1,2};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-14,14,0,6,-7,-6,0,1,-13,13,0,34,-6,6,0,3,12,30,26,40,-5,1,0,0,18,24,30,36,-7,-5,1,3,19,23,38,48,-3,0,0,1,20,27,44,56,2,6,0,2,18,22,48,58,-3,0,0,1,-12,12,32,78,-6,6,0,3,-4,4,8,96,-9,-7,1,2,12,19,56,66,-5,1,0,3,-13,13,76,96,-6,6,0,3,-7,-2,100,105,-10,-8,0,2,2,7,100,105,-10,-8,0,2,-9,9,92,124,-8,4,0,2,-8,8,96,112,-12,-10,0,0,-6,6,120,128,-5,5,0,2};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-18,2,0,8,-7,7,0,0,-2,18,0,8,-7,7,0,0,-11,-5,6,54,-5,5,0,3,5,11,6,54,-5,5,0,3,-15,15,2,84,5,11,1,2,17,21,30,74,-4,2,0,2,-15,15,50,64,-8,8,1,1,-22,-18,2,128,2,8,0,1,-14,14,62,68,-9,-8,0,0,15,22,70,84,-5,2,0,3,-15,15,66,98,-9,9,1,3,-39,-15,84,94,3,9,1,2,-12,12,72,92,-11,-9,0,1,-18,-10,92,102,-6,6,0,1,10,18,92,102,-6,6,0,1,-13,13,96,104,-8,8,0,0,-12,12,99,101,-10,-7,0,3,-37,-19,96,122,3,9,1,3,-13,13,102,122,-7,7,0,2,-12,12,108,114,-9,-7,0,0,-11,11,109,113,-10,-9,0,3,-10,10,120,125,-6,6,1,2,-3,3,120,128,-6,6,1,2};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {2,24,0,6,-3,9,0,0,-27,-5,0,6,-9,1,0,0,4,22,0,30,-2,8,0,3,-20,-12,0,34,-8,2,0,3,-30,-22,14,22,-9,-3,0,2,-25,-19,20,26,-9,-3,0,0,-24,-16,24,36,-8,-2,0,3,-15,13,30,46,-7,5,1,2,-11,11,52,57,-9,-7,0,3,-11,11,44,80,-7,5,1,3,-15,11,40,96,5,11,0,1,-3,4,46,80,-9,-7,0,0,12,20,76,92,-5,3,0,3,13,21,88,94,-5,3,0,0,-12,12,84,114,-6,7,0,1,-11,11,92,104,-8,-6,0,0,-7,-2,95,100,-10,-8,0,3,2,7,95,100,-10,-8,0,3,15,19,92,128,-4,2,0,2,-22,0,108,122,2,9,0,1};
inline constexpr short grandleon_playstation_mesh_beast[168] = {8,15,0,40,2,9,0,1,-15,-8,0,40,2,9,0,1,12,19,0,44,-12,-4,0,2,-19,-12,0,44,-12,-4,0,2,8,24,40,66,-8,5,0,2,6,11,36,60,-12,-9,0,3,-2,3,36,60,-12,-9,0,3,-10,-5,36,60,-12,-9,0,3,-26,-10,42,68,-8,5,0,2,-15,9,58,68,-7,2,0,3,20,27,58,84,-4,3,0,2,-6,2,66,76,-5,1,1,3,-35,-13,74,82,-9,-3,1,2,-28,-20,64,100,-5,2,0,3,23,29,82,94,-3,2,1,3,-38,-10,87,105,-5,2,0,3,-28,-23,102,107,-9,-7,0,0,-39,-11,98,118,-7,2,0,3,-34,-26,108,116,-6,0,0,1,-32,-24,113,117,-8,-6,0,0,-29,-21,116,128,-6,0,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,20,15,19,16,23,20,21};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,22,20,31,22,27,28,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {563,436,397,546,423,579,409,408};
