// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-15,1,0,4,-6,4,0,0,-1,15,0,4,-6,4,0,0,-10,-4,4,24,-4,4,0,2,4,10,4,24,-4,4,0,2,-14,2,24,41,-4,4,1,1,-2,14,24,41,-4,4,1,1,-11,11,41,48,-6,6,0,0,-22,-6,44,48,-8,-4,0,1,-15,-10,47,66,-4,4,0,1,10,15,47,66,-4,4,0,1,6,22,36,68,-11,-6,1,2,-7,7,41,68,-6,-5,1,2,-10,10,48,68,-5,5,0,2,-19,-6,64,73,-6,6,1,1,6,19,64,73,-6,6,1,1,-7,7,67,72,-4,4,0,0,-15,-12,47,91,-8,-5,0,3,-7,7,71,79,-4,4,0,1,-7,7,74,84,-6,6,0,3,-7,7,76,80,-7,-6,0,0,-8,8,84,88,0,7,1,2,-2,2,83,90,0,7,1,2};
inline constexpr short grandleon_playstation_mesh_archer[168] = {-12,-4,0,5,-5,3,0,0,4,12,0,5,-5,3,0,0,-11,-5,5,24,-3,3,0,1,5,11,5,24,-3,3,0,1,-11,-4,24,37,-3,3,0,0,4,11,24,37,-3,3,0,0,16,21,13,53,-5,-3,0,1,-12,12,37,46,-5,5,1,2,-12,12,45,49,-5,5,0,0,-17,-10,46,61,-4,4,0,2,-13,-6,47,68,4,9,0,0,10,17,46,63,-4,4,0,2,-12,12,49,64,-4,4,1,1,15,22,50,59,-6,-2,0,3,-12,-7,68,74,5,8,1,3,-9,9,66,74,-3,3,0,2,16,21,57,84,-5,-3,0,1,-9,9,70,78,-5,5,1,1,-8,8,77,80,1,5,1,1,-3,3,76,83,1,5,1,1,-6,6,74,76,-7,-5,0,3};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-15,15,0,5,-7,7,0,0,-13,13,4,34,-6,6,1,2,-21,-16,6,53,-6,-3,0,1,-13,13,34,40,-7,7,0,0,-13,13,38,61,-5,5,1,1,-16,-11,43,61,-5,5,1,2,11,16,43,61,-5,5,1,2,-17,-11,46,53,-7,-2,0,2,-4,4,56,64,-6,-4,0,3,-11,11,59,71,-5,5,0,2,-21,-16,53,82,-6,-3,0,1,-14,14,69,74,-7,2,1,1,-11,11,73,85,-5,2,1,2,-22,-15,81,90,-7,-2,1,3,-11,11,87,94,-3,2,1,2,-3,3,84,97,-5,0,1,2};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-14,14,0,14,-6,6,1,1,-21,21,3,50,6,11,1,0,-19,19,13,37,-5,5,1,2,-18,18,35,41,-6,6,0,0,-23,-18,4,68,-6,-2,0,1,-12,12,40,60,-4,4,1,3,10,17,43,61,-4,4,1,2,-17,-10,45,65,-5,4,1,2,-20,-14,50,57,-6,-1,0,2,-9,9,60,71,-4,4,0,1,-12,12,69,74,-4,5,1,3,-35,-5,65,74,-9,-1,0,1,10,32,71,85,4,10,0,2,-37,-3,72,77,-9,-1,0,0,5,11,74,84,-1,4,0,3,-11,-5,74,84,-1,4,0,3,-38,-32,77,84,-6,-3,0,3,-8,-2,77,85,-6,-3,0,3,-24,-16,77,91,-6,-3,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-15,15,0,5,-7,7,0,0,-13,13,4,34,-6,6,0,3,-8,-3,4,63,-7,-6,1,2,3,8,4,63,-7,-6,1,2,-13,13,42,46,-6,6,0,0,-20,-15,9,81,-4,-1,0,1,-12,12,33,60,-5,5,0,3,-14,-10,43,63,-4,4,0,3,10,14,43,63,-4,4,0,3,-16,-10,48,55,-6,-1,0,2,-12,12,63,70,-5,2,1,2,-10,10,69,80,-4,4,0,2,-11,11,76,87,-4,5,0,3,-7,7,81,84,-6,-4,0,0,-28,-8,85,90,-4,-1,0,3,-20,-15,79,96,-4,-1,0,3,-28,-8,87,95,-4,-1,0,3};
inline constexpr short grandleon_playstation_mesh_commander[184] = {5,11,0,4,-6,4,0,0,-8,-2,0,4,-6,4,0,0,5,10,4,24,-4,4,0,2,-7,-3,4,24,-4,4,0,2,-10,13,4,65,5,11,1,0,5,10,24,39,-4,4,0,1,-7,-2,24,39,-4,4,0,1,-13,-9,28,48,-7,-4,0,0,-9,12,39,46,-5,5,1,1,17,21,11,87,3,7,0,1,-9,12,45,49,-6,6,0,0,-20,-3,46,50,-7,-4,0,2,11,17,48,65,-4,4,0,2,-14,-8,48,65,-4,4,0,2,-8,11,49,68,-5,5,1,3,7,22,63,72,-6,6,1,2,-19,-4,63,72,-6,6,1,2,-6,9,68,72,-4,4,0,0,17,34,68,86,1,8,1,3,-7,10,72,82,-6,6,0,3,-7,10,75,79,-7,-6,0,0,14,25,86,90,3,7,0,3,-1,4,81,90,-6,4,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {-29,-9,0,4,-5,4,0,0,9,29,0,4,-5,4,0,0,-23,-15,4,18,-3,3,0,0,15,23,4,18,-3,3,0,0,-25,-5,18,32,-4,4,0,1,5,25,18,32,-4,4,0,1,-12,12,32,37,-5,5,0,0,-12,12,34,59,4,8,1,0,-11,11,35,54,-4,4,1,1,-19,-12,38,53,-4,4,0,1,12,19,38,53,-4,4,0,1,-30,-14,51,53,-5,-2,0,2,14,30,51,53,-5,-2,0,2,-9,9,53,57,-4,-2,1,2,-10,10,57,64,-3,3,0,2,-24,-19,52,69,-5,-2,0,3,19,24,52,69,-5,-2,0,3,-11,11,60,71,-4,4,0,0,-7,7,65,68,-6,-4,0,3,-3,3,70,76,1,5,0,0};
inline constexpr short grandleon_playstation_mesh_beast[136] = {1,20,0,24,3,8,0,0,-24,-5,0,24,3,8,0,0,1,20,0,24,-8,-4,0,1,-24,-5,0,24,-8,-4,0,1,0,23,23,41,-8,7,0,2,-17,16,22,45,-8,7,0,1,-5,1,22,46,-9,8,1,2,14,20,34,39,-1,3,0,1,-28,-2,31,50,-9,8,1,1,18,23,37,51,-1,3,0,2,-39,-14,40,49,-5,0,0,1,-34,-10,43,57,-7,1,0,2,-30,-27,48,55,-5,-2,0,3,-30,-14,49,52,-10,-8,0,0,-24,-19,55,61,1,4,0,0,-37,-5,57,60,1,4,0,0,-23,-18,57,70,-3,0,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,21,16,19,17,23,20,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {447,461,484,544,447,568,418,478};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,28,27,28,23,21};
