// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[192] = {-16,-1,0,7,-6,6,0,0,1,16,0,7,-6,6,0,0,7,20,7,16,6,10,0,1,-12,-6,7,33,-4,4,0,1,6,12,7,33,-4,4,0,1,-11,11,31,43,-7,7,1,1,-11,11,41,46,-7,7,0,0,10,29,43,47,-2,2,0,0,-29,-12,22,64,-10,-2,1,2,-23,-18,38,47,-11,-10,1,3,12,16,46,68,-4,4,0,1,-16,-12,46,68,-4,4,0,1,-12,12,44,71,-7,7,1,2,-10,10,52,65,-8,-7,1,3,18,21,47,87,-1,1,0,3,-20,-5,68,75,-5,5,0,2,5,20,68,75,-5,5,0,2,-9,9,71,75,-6,6,0,0,-6,6,72,74,-8,-6,0,3,-9,9,74,90,-7,7,0,2,-9,9,78,82,-8,-7,0,0,-19,-3,89,92,-1,3,0,3,-14,-9,87,95,-1,3,0,3,9,14,87,95,-1,3,0,3};
inline constexpr short grandleon_playstation_mesh_archer[184] = {-12,-4,0,6,-5,5,0,0,4,12,0,6,-5,5,0,0,13,27,5,13,4,8,0,1,-11,-4,6,24,-4,4,0,1,4,11,6,24,-4,4,0,1,-11,-3,23,37,-4,4,0,1,3,11,23,37,-4,4,0,1,-11,11,35,42,-5,5,1,2,-30,-26,5,77,-1,1,0,3,-31,-25,42,51,-2,2,0,0,8,16,40,64,4,10,0,1,-14,-10,41,55,-4,4,0,1,10,14,41,55,-4,4,0,1,-26,-14,45,50,-3,1,0,1,-7,7,41,60,-5,5,1,2,-3,3,41,60,-6,-5,0,0,-5,5,59,67,-5,4,0,2,9,15,63,72,5,9,0,3,-5,5,62,65,-6,-5,0,0,-6,6,66,75,-4,5,1,2,-4,4,69,72,-6,-4,0,0,-3,3,74,79,-1,5,0,3,-2,2,73,82,-1,5,0,3};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-13,13,0,16,-6,6,1,1,-12,12,15,36,-5,5,1,2,-4,4,6,52,-7,-5,0,0,-15,-10,33,51,-4,4,1,1,10,15,33,51,-4,4,1,1,-11,11,34,54,-4,4,1,2,13,17,7,82,-3,0,0,1,22,29,42,49,-4,0,0,1,-9,9,52,58,-5,5,1,3,-8,8,57,70,-6,3,0,2,-8,8,63,66,-7,-6,0,3,-11,11,65,82,-3,6,0,1,-13,-7,70,82,-1,3,0,3,7,13,70,82,-1,3,0,3,-7,7,72,77,-9,-7,0,3,11,19,80,91,-4,1,0,3,-9,-4,80,95,-1,4,0,3,4,9,80,95,-1,4,0,3,4,26,86,91,-4,1,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-10,10,0,11,-5,5,1,1,-8,8,10,35,-4,4,1,2,-3,3,2,49,-6,-4,0,0,20,24,0,69,-1,1,0,1,-30,-14,25,57,2,7,1,0,-14,-10,33,49,-3,3,1,2,10,14,33,49,-3,3,1,2,-9,9,33,54,-4,4,1,3,12,28,41,47,-2,2,0,1,-11,11,54,63,-4,4,0,2,-11,11,57,60,-6,-4,0,3,-7,7,58,61,-7,-5,0,0,-11,11,62,73,-3,5,0,1,-15,-8,67,74,-1,2,0,3,8,15,67,74,-1,2,0,3,11,33,68,74,-4,4,0,0,12,32,73,78,-3,3,0,2,19,25,77,79,-2,2,0,3};
inline constexpr short grandleon_playstation_mesh_healer[112] = {-16,16,0,14,-5,5,0,3,-15,15,12,50,-5,5,0,3,-12,12,1,55,-6,-5,1,2,-15,15,30,34,-6,6,0,1,16,20,2,73,-2,1,0,1,13,21,37,44,-3,1,0,1,-18,-13,32,52,-4,4,0,3,13,18,32,52,-4,4,0,3,-12,12,55,65,-4,4,0,1,-13,13,61,64,-5,-4,0,0,-13,13,60,76,-3,6,0,3,-6,6,73,80,0,6,0,3,8,28,71,78,-2,1,0,3,15,21,73,77,-3,-2,1,3};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-13,-5,0,6,-6,6,0,0,5,13,0,6,-6,6,0,0,-12,-5,6,30,-4,4,0,1,5,12,6,30,-4,4,0,1,-14,14,3,69,4,8,1,1,-12,-4,29,43,-5,5,0,1,4,12,29,43,-5,5,0,1,20,24,0,92,0,3,0,3,-15,15,42,49,-6,6,1,2,-15,15,47,52,-6,6,0,0,15,23,53,60,-1,3,0,1,-18,-13,49,69,-4,4,0,1,13,18,49,69,-4,4,0,1,-15,15,50,72,-6,6,0,2,-13,13,56,66,-8,-6,1,3,24,32,63,70,0,3,1,2,-19,-11,69,76,-5,5,0,2,11,19,69,76,-5,5,0,2,-13,13,72,76,-6,6,0,0,-9,9,73,75,-8,-6,0,3,19,43,69,89,0,3,1,3,-12,12,75,89,-6,6,0,1,-12,12,78,81,-7,-6,0,0,-3,3,86,92,-4,6,0,3,-10,10,88,92,-4,6,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[192] = {4,12,0,5,-5,5,0,0,-12,-4,0,5,-5,5,0,0,-29,-7,7,14,3,7,0,1,4,11,5,20,-3,3,0,1,-11,-4,5,20,-3,3,0,1,3,11,19,31,-4,4,0,1,-11,-3,19,31,-4,4,0,1,-11,11,29,35,-5,5,1,1,-11,11,23,52,3,6,0,0,-10,10,34,37,-5,5,0,3,11,15,35,46,-3,3,0,1,-15,-11,35,46,-3,3,0,1,-10,10,36,51,-5,5,0,1,-10,10,37,49,-6,-5,1,2,13,20,42,48,-5,-1,0,1,-20,-13,42,48,-5,-1,0,1,-8,8,50,57,-4,3,0,2,-8,8,52,54,-5,-4,0,3,14,19,48,62,-4,-2,0,3,-19,-14,48,62,-4,-2,0,3,-11,11,54,67,-2,5,0,1,-7,7,59,63,-6,-5,0,3,-3,3,64,72,1,7,0,1,-10,10,67,71,1,7,0,1};
inline constexpr short grandleon_playstation_mesh_beast[176] = {5,11,0,26,5,11,0,0,-14,-8,0,26,5,11,0,0,-11,-5,0,26,-11,-5,0,1,8,14,0,26,-11,-5,0,1,-24,-7,23,35,-4,4,0,1,-8,12,22,30,-10,-9,0,2,-29,-13,28,39,-3,3,0,1,-10,12,22,45,-9,8,0,1,-25,-20,36,48,-2,2,0,3,-12,-8,40,46,-2,2,1,3,-15,4,40,54,4,8,1,2,-5,0,42,49,-2,2,1,3,6,25,36,57,-4,3,0,1,3,8,44,50,-2,2,1,3,13,18,37,54,-6,-4,1,3,22,26,53,56,-5,-3,0,3,21,27,55,62,-6,-1,0,1,10,31,54,67,-5,3,0,1,19,23,62,66,-6,-5,0,3,12,18,66,82,1,4,0,3,12,18,66,81,-4,-1,0,3,3,25,71,79,-4,-1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {24,23,19,18,14,25,24,22};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {29,30,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {490,446,377,496,427,650,434,597};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,23,25,28,23,27};
