// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-11,-4,0,8,-8,8,0,0,4,11,0,8,-8,8,0,0,-10,-5,8,40,-6,6,0,1,5,10,8,40,-6,6,0,1,-10,-4,38,56,-7,7,0,1,4,10,38,56,-7,7,0,1,-11,11,52,66,-9,9,1,2,10,28,56,62,-5,1,0,0,-28,-11,36,88,-12,-2,1,3,-11,11,64,70,-9,9,0,0,11,15,64,92,-5,5,0,1,-15,-11,64,92,-5,5,0,1,-12,12,68,98,-8,8,1,2,-3,3,74,106,7,13,0,0,-10,10,74,92,-10,-8,1,3,17,21,62,116,-2,2,0,3,-14,-8,94,102,-6,6,0,2,8,14,94,102,-6,6,0,2,-10,9,98,104,-7,7,0,0,-6,6,100,102,-10,-7,0,3,-9,9,102,122,-8,8,0,2,-9,9,107,112,-10,-8,0,0,-12,-7,116,128,-2,4,0,3,7,12,116,128,-2,4,0,3,-17,-2,120,126,-2,4,0,3};
inline constexpr short grandleon_playstation_mesh_archer[192] = {-12,-4,0,8,-8,8,0,0,4,12,0,8,-8,8,0,0,-29,-13,10,20,5,11,0,1,-10,-4,8,36,-6,6,0,1,4,10,8,36,-6,6,0,1,-10,-3,34,52,-6,6,0,1,3,10,34,52,-6,6,0,1,-13,13,50,64,-8,8,1,2,26,30,10,122,-2,2,0,3,-16,-8,62,98,7,15,0,1,-13,-9,64,84,-5,5,0,2,9,13,64,84,-5,5,0,2,25,31,70,82,-3,3,0,0,14,26,72,80,-4,2,0,1,-6,6,62,92,-7,7,1,2,-3,3,62,92,-9,-7,0,0,-5,3,82,106,7,13,0,0,-15,-9,96,110,8,14,0,3,-6,6,90,102,-8,4,0,2,-6,6,94,99,-10,-8,0,0,-6,6,100,116,-5,8,1,2,-5,5,112,120,2,10,0,3,-4,4,107,111,-10,-7,0,0,-3,3,112,128,2,10,0,3};
inline constexpr short grandleon_playstation_mesh_mage[160] = {-17,17,0,16,-8,8,1,2,-12,12,14,42,-7,7,1,1,-3,3,6,64,-9,-7,0,0,-11,11,40,68,-6,6,1,2,-12,-8,46,62,-5,5,1,3,8,12,46,62,-5,5,1,3,-17,-10,54,64,-5,1,0,1,-16,-12,12,114,-3,1,0,1,-8,8,66,74,-6,6,1,3,2,8,66,92,6,12,0,0,-5,5,69,71,-9,-6,0,0,-8,8,74,90,-7,4,0,2,-4,4,80,85,-9,-7,0,3,-12,12,84,104,0,8,0,0,-11,-6,92,112,-2,4,0,3,6,11,92,112,-2,4,0,3,-26,-2,77,128,-3,1,0,1,-7,-2,110,128,-1,5,0,3,2,7,110,128,-1,5,0,3,-18,-10,112,124,-5,3,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-11,11,0,16,-8,8,1,2,-10,10,14,50,-7,7,1,1,-3,3,6,76,-8,-6,0,0,-24,-20,0,114,-2,2,0,1,14,32,44,90,4,12,1,0,-13,-9,52,76,-5,5,1,2,9,13,52,76,-5,5,1,2,-28,-12,62,72,-3,3,0,1,-9,9,50,84,-6,6,1,3,2,10,70,100,7,13,0,0,-12,12,84,98,-7,5,0,2,-4,4,88,93,-9,-7,0,3,-13,13,96,114,-4,8,0,1,-13,-7,104,116,-2,4,0,3,7,13,104,116,-2,4,0,3,-9,9,104,109,-9,-6,0,3,-35,-9,112,121,-6,6,0,0,-26,-18,119,128,-4,4,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-19,19,0,18,-8,8,0,3,-15,15,16,44,-7,7,0,2,-14,14,42,48,-8,8,0,1,-4,4,4,84,-10,-8,1,3,-20,-16,6,116,-3,1,0,1,-13,13,46,78,-7,7,0,3,-21,-13,58,68,-5,1,0,1,-15,-11,50,80,-5,5,0,3,11,15,50,80,-5,5,0,3,-10,18,73,84,6,12,0,0,1,7,74,96,6,12,0,0,-13,13,86,102,-6,5,0,1,-14,14,96,101,-7,-5,0,0,-15,15,94,120,-4,9,0,3,-11,11,116,128,2,11,0,3,-29,-7,112,124,-4,2,0,3,-21,-15,115,121,-5,-4,1,3};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-12,-4,0,8,-8,8,0,0,4,12,0,8,-8,8,0,0,-11,-5,8,38,-6,6,0,1,5,11,8,38,-6,6,0,1,-14,14,10,92,6,12,1,2,-11,-4,36,56,-6,6,0,1,4,11,36,56,-6,6,0,1,-14,14,54,68,-8,8,1,2,-24,-20,0,128,0,4,0,3,-13,13,66,71,-8,8,0,0,-28,-8,72,82,-2,4,0,1,-15,-11,66,94,-5,5,0,1,11,15,66,94,-5,5,0,1,0,8,70,104,9,15,0,0,-14,14,69,98,-8,8,0,2,-12,12,76,90,-10,-9,1,3,-32,-24,86,96,0,4,1,2,-16,-9,94,103,-6,6,0,2,9,16,94,103,-6,6,0,2,-12,12,98,104,-7,7,0,0,-8,8,100,102,-10,-7,0,3,-43,-19,94,122,0,4,1,3,-12,12,102,122,-7,7,0,1,-12,12,106,111,-9,-7,0,0,-2,2,118,128,-5,7,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-11,-4,0,8,-8,8,0,0,4,11,0,8,-8,8,0,0,-30,-10,10,20,5,11,0,1,-10,-4,8,34,-6,6,0,1,4,10,8,34,-6,6,0,1,-10,-3,32,48,-6,6,0,1,3,10,32,48,-6,6,0,1,-10,10,46,58,-8,8,1,2,-9,9,56,61,-8,8,0,3,-10,10,44,90,6,12,0,1,-13,-9,60,80,-5,5,0,2,9,13,60,80,-5,5,0,2,-9,9,59,86,-7,7,0,1,-8,8,62,82,-9,-7,1,2,-8,0,72,98,10,16,0,0,-19,-12,72,82,-8,-2,0,1,12,19,72,82,-8,-2,0,1,-8,8,86,98,-7,5,0,2,-4,4,90,94,-9,-7,0,3,-18,-13,82,106,-7,-3,0,3,13,18,82,106,-7,-3,0,3,-10,10,94,116,-3,9,0,1,-7,7,103,109,-11,-8,0,3,-2,4,112,128,4,12,0,1,-9,11,118,126,4,12,0,1};
inline constexpr short grandleon_playstation_mesh_beast[168] = {-12,-5,0,38,7,17,0,0,8,14,0,38,7,17,0,0,4,11,0,38,-17,-7,0,1,-15,-9,0,38,-17,-7,0,1,9,23,36,52,-5,5,0,1,-12,8,34,44,-15,-13,0,2,-13,9,34,66,-13,11,0,1,14,28,46,64,-4,4,0,1,7,12,58,68,-3,3,1,3,-4,14,60,82,6,12,1,2,0,4,62,72,-3,3,1,3,-9,-4,64,74,-3,3,1,3,-24,-8,54,86,-6,4,0,1,20,25,62,80,-3,3,0,3,-19,-14,56,82,-9,-6,1,3,-17,-10,84,96,2,8,1,3,-28,-22,84,94,-10,-2,0,1,-32,-11,82,102,-8,4,0,1,-24,-20,95,100,-10,-8,0,3,-15,-9,100,128,-2,4,0,3,-23,-1,110,124,-2,4,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,24,20,18,17,25,25,21};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,28,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {472,428,359,478,409,630,419,582};
