// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[152] = {-13,-4,0,6,-8,8,0,0,4,13,0,6,-8,8,0,0,-12,-5,6,40,-6,6,0,1,5,12,6,40,-6,6,0,1,-12,-4,38,62,-7,7,0,1,4,12,38,62,-7,7,0,1,-24,-10,8,78,-18,-12,1,3,-13,13,60,72,-8,8,1,1,13,17,70,92,-6,6,0,1,-17,-13,72,96,-6,6,0,1,-13,13,70,102,-9,9,1,1,12,26,80,86,-12,-4,0,2,24,30,78,90,-14,-4,0,3,-9,9,76,98,-11,-9,0,1,-19,-11,96,108,-9,9,1,2,11,19,96,108,-9,9,1,2,-6,6,100,106,-5,5,0,0,-9,9,104,128,-9,9,0,1,-9,9,110,116,-11,-9,0,3};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,6,-7,7,0,0,3,11,0,6,-7,7,0,0,-10,-4,6,38,-5,5,0,1,4,10,6,38,-5,5,0,1,-10,-3,36,60,-6,6,0,0,3,10,36,60,-6,6,0,0,-24,-18,30,66,-18,-14,0,1,-11,11,58,96,-7,7,1,3,-16,-11,66,90,-6,6,1,1,-24,2,66,72,-18,-14,0,1,11,16,70,94,-6,6,1,1,-2,27,72,78,-18,-14,0,2,26,32,70,82,-20,-12,0,3,-6,6,94,110,-6,6,0,2,-8,8,100,118,-6,8,1,2,0,8,104,110,-10,-6,0,3,-4,4,112,128,-2,10,1,2};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-8,8,0,12,-6,6,0,3,-6,6,10,24,-4,4,0,2,-11,11,22,42,-7,7,1,1,-17,17,40,64,-9,9,1,2,-24,-18,46,56,-8,0,0,2,18,24,46,56,-8,0,0,2,-18,-10,52,66,-4,4,1,2,10,18,52,66,-4,4,1,2,-14,14,62,86,-8,8,1,3,-6,6,72,80,-10,-8,0,3,-10,10,80,96,-6,6,0,1,-10,10,90,96,-8,2,0,3,-3,3,96,112,-2,2,0,0,-8,8,110,124,-4,4,0,3,-4,4,118,128,-2,2,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-14,14,0,20,-9,9,1,0,-16,16,4,66,8,16,1,1,-12,12,18,52,-8,8,1,2,-14,14,44,54,-16,-8,0,2,-9,9,45,51,-18,-16,0,3,-10,10,50,80,-8,8,1,3,-16,-10,50,74,-12,-4,1,1,10,16,50,74,-12,-4,1,1,-29,-19,64,76,-10,2,0,3,19,29,64,76,-10,2,0,3,-8,8,78,96,-7,7,0,1,-8,8,84,90,-10,-8,0,3,-30,-20,96,108,-4,8,0,2,20,30,96,108,-4,8,0,2,-12,12,100,108,-4,4,1,3,-11,-7,106,124,-3,3,0,2,7,11,106,124,-3,3,0,2,-2,2,106,128,-3,3,0,2};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-11,-3,0,6,-7,7,0,0,3,11,0,6,-7,7,0,0,-10,-4,6,36,-6,6,0,3,4,10,6,36,-6,6,0,3,-13,13,34,62,-9,9,0,3,-6,6,34,62,-11,-9,1,3,-19,-15,64,88,-6,6,0,3,-15,15,60,96,-11,11,0,3,15,19,68,94,-6,6,0,3,-6,6,60,96,-13,-11,1,3,-15,15,92,100,-9,3,1,2,-7,7,96,112,-6,6,0,2,16,22,86,120,-6,-2,0,1,-8,8,100,106,-8,-6,0,0,-8,8,107,113,-7,1,1,2,10,26,120,128,-8,-2,0,3,16,22,120,128,-16,4,0,3};
inline constexpr short grandleon_playstation_mesh_commander[192] = {-11,-3,0,6,-7,7,0,0,3,11,0,6,-7,7,0,0,-10,-4,6,38,-6,6,0,1,4,10,6,38,-6,6,0,1,-15,15,4,88,8,16,1,1,-10,-3,36,60,-7,7,0,2,3,10,36,60,-7,7,0,2,17,29,52,58,2,12,0,2,20,26,0,114,4,10,0,2,-12,12,58,74,-8,8,1,2,-17,-12,72,94,-6,6,0,2,12,17,72,94,-6,6,0,2,-12,12,72,100,-10,10,1,3,-22,-15,78,86,-12,-4,0,1,-8,8,80,86,-12,-10,0,3,-24,-18,80,90,-14,-6,0,3,26,30,92,112,0,16,1,3,-19,-11,94,106,-9,9,1,2,11,19,94,106,-9,9,1,2,-9,9,102,118,-9,9,0,2,-9,9,106,112,-11,-9,0,0,21,25,110,128,4,10,0,3,-9,9,114,120,-9,9,0,3,-3,3,116,128,-2,12,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[144] = {-15,-6,0,8,-12,0,0,0,6,15,0,8,-12,0,0,0,-14,-7,8,34,-12,-2,0,1,7,14,8,34,-12,-2,0,1,-14,14,4,64,8,14,0,0,-28,-8,30,38,-22,-16,0,3,-13,-5,32,58,-10,2,0,1,5,13,32,58,-10,2,0,1,-12,12,56,72,-14,0,1,1,-18,-12,66,88,-18,-6,0,1,-12,12,70,96,-14,0,1,3,12,18,74,96,-18,-6,0,1,8,28,86,94,-22,-16,0,3,-15,15,96,104,-14,0,0,1,-10,10,94,102,-16,-6,1,3,-9,9,100,122,-20,-8,0,0,-7,7,106,111,-22,-20,0,3,-7,7,118,128,-18,-10,0,0};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-16,-9,0,44,6,14,0,0,-3,4,0,44,6,14,0,0,10,17,0,44,6,14,0,0,-16,-9,0,44,-18,-10,0,1,-3,4,0,44,-18,-10,0,1,10,17,0,44,-18,-10,0,1,-18,20,40,76,-16,12,0,1,28,35,50,58,-18,-8,0,1,21,31,52,78,-12,4,0,2,15,21,58,80,-10,2,1,2,-22,-12,62,80,-6,4,0,1,28,35,62,70,-18,-8,0,1,23,31,66,74,-16,-12,0,3,-17,-9,76,92,-6,4,1,3,-4,4,76,92,-6,4,1,3,9,17,76,92,-6,4,1,3,-27,-19,78,98,-6,4,0,1,-28,-20,94,114,-6,4,0,1,-27,-19,110,128,-8,2,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {19,17,15,18,17,24,18,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,24,30,21,26,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {466,429,430,508,430,555,423,503};
