// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[152] = {-12,-5,0,8,-7,7,0,0,5,12,0,8,-7,7,0,0,-11,-5,6,40,-6,6,0,1,5,11,6,40,-6,6,0,1,-15,15,38,56,-8,8,1,1,-13,13,54,62,-9,9,0,0,-17,-11,62,88,-5,5,0,2,11,17,62,88,-5,5,0,2,-13,13,68,72,-10,-8,1,0,-13,13,60,92,-7,7,1,2,-13,13,78,82,-10,-8,1,0,15,21,84,94,-6,0,0,1,-3,5,88,106,6,11,0,0,-17,-10,82,108,-5,5,0,0,-13,13,92,112,-6,6,0,2,-12,12,99,105,-9,-7,0,0,21,27,92,120,-5,1,0,3,-12,12,110,128,-7,3,1,2,-11,11,118,123,-9,-6,0,0};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-12,-5,0,10,-7,7,0,0,5,12,0,10,-7,7,0,0,-11,-5,8,42,-6,6,0,2,5,11,8,42,-6,6,0,2,-9,9,40,58,-8,8,1,1,-9,9,56,64,-8,8,0,0,-19,-12,66,84,-5,5,0,2,12,19,66,84,-5,5,0,2,-15,15,62,94,-8,8,0,1,-29,1,68,80,-11,-5,0,1,-4,30,71,77,-10,-6,0,3,-4,4,64,92,-11,-9,1,2,1,7,66,92,-12,-10,0,0,2,6,76,81,-13,-11,0,3,-9,-1,78,84,-13,-9,0,0,-14,-8,84,114,-5,6,0,0,8,14,84,114,-5,6,0,0,-7,7,92,112,-6,6,0,2,-7,7,100,106,-9,-7,0,0,-7,7,112,128,-7,7,0,0};
inline constexpr short grandleon_playstation_mesh_mage[136] = {3,8,0,6,-6,4,0,1,-10,-3,0,8,-7,5,0,0,3,7,4,44,-5,4,0,1,-9,-3,6,44,-6,4,0,1,2,8,40,48,-10,-8,0,0,-12,12,40,64,-8,8,1,1,-10,10,62,70,-8,8,0,0,9,14,56,82,-5,5,0,2,-9,9,68,96,-6,6,1,2,-15,-9,72,102,-5,5,0,2,4,10,74,110,6,11,0,0,-9,9,88,108,-6,6,0,2,-9,9,95,101,-9,-7,0,0,-13,-10,102,114,-5,-2,0,1,-10,10,104,109,-9,-7,1,3,-9,9,106,128,-6,7,0,0,-19,-5,110,122,-7,-1,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[176] = {-12,-5,0,8,-7,6,0,0,5,12,0,8,-7,6,0,0,-11,-5,6,40,-6,6,0,1,5,11,6,40,-6,6,0,1,-13,13,38,56,-8,8,0,1,-22,-17,0,104,-3,3,0,1,-11,11,54,62,-8,8,0,0,10,16,60,84,-5,5,0,2,-11,11,60,92,-6,6,1,2,-17,-11,62,90,-5,5,0,2,-12,12,70,75,-9,-7,1,0,-4,4,90,106,6,11,0,0,8,14,82,112,-5,6,0,0,-11,11,90,110,-6,6,0,2,-11,11,98,103,-9,-7,0,0,-31,-9,102,112,-6,6,0,0,-30,-10,104,108,-8,-6,0,3,-25,-15,110,120,-4,4,0,3,-7,7,108,126,-7,5,0,1,-5,5,112,116,-9,-7,0,3,-6,6,116,121,-9,-6,0,3,-23,-16,118,128,-3,3,1,3};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-16,16,0,24,-7,7,1,1,-7,-1,30,36,-10,-8,0,1,-14,14,20,58,-8,8,0,3,-23,-3,44,58,-10,-2,1,1,-12,12,54,60,-9,9,0,0,-16,-10,60,88,-5,5,0,2,-10,10,58,92,-7,7,0,3,10,16,64,92,-5,5,0,2,2,8,70,76,-10,-8,0,1,-6,0,62,92,-10,-8,1,1,7,14,86,112,-5,6,0,1,-12,12,92,112,-6,6,0,2,-12,-5,102,116,5,10,0,3,-12,12,100,105,-9,-7,0,0,-12,12,110,128,-7,4,0,3,-11,11,118,123,-9,-6,0,0};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-12,-4,0,10,-7,7,0,0,4,12,0,10,-7,7,0,0,-10,-4,8,36,-6,6,0,1,4,10,8,36,-6,6,0,1,-13,13,8,94,8,13,1,1,-13,13,34,62,-8,8,1,1,20,25,4,116,4,9,0,1,-11,11,58,66,-8,8,0,0,-3,3,59,64,-10,-8,0,3,-17,-11,62,90,-5,5,1,2,11,17,62,90,-5,5,1,2,-11,11,64,98,-7,7,1,2,-3,3,66,96,-10,-8,0,3,-17,-11,84,90,-7,-1,0,3,11,17,84,90,-7,-1,0,3,3,10,88,108,5,10,0,1,19,41,94,114,3,15,1,3,-11,11,92,98,-9,-7,0,0,-13,13,90,110,-6,6,0,2,27,32,100,108,1,3,0,0,-12,12,98,104,-9,-7,0,0,-11,11,108,122,-6,6,0,3,-12,12,108,113,-9,-7,0,0,-2,2,118,128,-5,9,1,2,-7,7,122,127,-5,9,1,2};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-23,-5,0,8,-7,6,0,0,5,23,0,8,-7,6,0,0,-17,-9,6,42,-6,5,0,1,9,17,6,42,-6,5,0,1,-11,11,40,54,-8,8,1,2,11,17,52,78,-5,5,0,2,-9,9,60,64,-9,-7,1,1,-9,9,52,84,-6,6,0,3,-11,11,56,98,7,12,1,1,-9,9,70,74,-9,-7,1,1,-18,-12,64,92,-5,5,0,2,26,32,74,84,-6,0,0,1,-8,0,86,104,5,9,0,0,26,31,82,104,-5,0,0,3,-12,12,86,106,-6,6,0,2,-21,-15,90,100,-6,0,0,1,-12,12,92,99,-9,-7,0,0,-19,-14,98,120,-5,0,0,3,-11,11,104,124,-6,6,1,1,-10,10,113,118,-8,-5,0,3,-4,4,122,128,-3,7,1,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-9,-2,0,7,-9,3,0,2,3,9,0,7,-9,3,0,2,8,24,4,14,-2,6,1,1,-7,-3,5,29,-5,3,0,2,3,7,5,29,-5,3,0,2,5,20,12,28,-2,6,1,2,0,15,24,42,-2,6,1,2,-8,5,40,70,8,11,1,1,-10,6,27,74,-8,10,1,2,-8,5,38,68,-11,-8,1,1,-7,4,50,56,-13,-11,0,3,-15,-3,70,90,-6,6,1,3,-17,-4,88,102,-7,9,1,3,-24,-14,90,97,-6,0,0,1,-10,-6,94,98,-8,-6,0,0,-16,-10,102,108,1,7,0,3,-15,-11,100,112,1,7,0,3,-6,-2,100,116,-3,4,0,3,-10,-6,102,128,-2,5,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {19,20,17,22,16,25,21,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {24,26,18,25,21,25,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {464,402,397,484,434,563,417,339};
