// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[160] = {-13,-4,0,5,-5,5,0,1,4,13,0,5,-5,5,0,1,-34,-24,0,9,-7,-3,0,1,-12,-5,4,27,-4,4,0,3,5,12,4,27,-4,4,0,3,-12,-4,26,39,-5,5,0,3,4,12,26,39,-5,5,0,3,-13,13,36,46,-6,6,1,1,-38,-20,7,80,-7,-3,1,3,15,21,50,58,-4,1,0,3,-15,15,43,67,-7,7,1,2,-38,-20,50,57,-8,-7,0,2,-6,6,47,65,-8,-7,0,2,14,20,53,78,1,8,0,2,-15,-9,62,69,-5,5,0,1,9,15,62,69,-5,5,0,1,-10,10,65,81,-6,6,0,1,-10,10,69,74,-7,-6,0,0,-8,8,70,74,-8,-7,0,3,-34,-24,77,86,-7,-3,0,1};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-9,-3,0,30,-4,4,0,3,3,9,0,30,-4,4,0,3,-26,-20,3,52,-4,1,0,3,-11,11,27,42,-5,5,1,2,-13,13,17,60,3,7,1,1,11,17,40,66,1,7,0,1,-12,12,46,52,-6,-5,0,3,6,12,44,60,-4,3,0,3,-20,-6,49,54,-4,0,0,3,-4,4,52,70,-4,4,0,3,-12,12,62,67,-6,-5,0,3,12,16,64,80,3,9,0,3,-26,-20,49,89,-4,1,0,3,-11,11,69,73,-6,5,1,3,-6,6,66,72,-9,-4,0,1,-9,9,70,86,-9,1,0,3,-9,9,73,77,-10,-9,0,0,-6,6,83,92,-6,3,0,3};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-9,9,0,8,-4,4,0,2,-4,4,6,27,-2,2,0,1,-20,-4,23,33,-7,-5,0,0,4,20,23,33,-7,-5,0,0,-20,20,31,53,-5,5,1,2,-4,4,33,53,-6,-5,0,1,-14,14,51,73,-5,5,1,3,-4,4,53,73,-6,-5,0,1,-11,11,61,66,-7,-5,0,3,-10,10,72,76,-6,-5,0,1,-10,10,75,92,-5,5,1,1,-9,9,80,87,-6,-5,0,0,-8,-3,81,86,-8,-6,0,2,3,8,81,86,-8,-6,0,2,-5,5,90,100,-3,3,1,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-11,-4,0,17,-4,4,0,2,4,11,0,17,-4,4,0,2,-13,13,12,16,-6,-5,0,1,-30,-18,20,24,-5,5,0,1,18,30,20,24,-5,5,0,1,-13,13,15,42,-5,5,1,2,-28,-18,22,41,-4,4,0,3,18,28,22,41,-4,4,0,3,-11,11,33,37,-7,-5,0,3,-27,-21,40,57,-3,1,0,1,21,27,40,57,-3,1,0,1,-11,11,40,59,-4,4,1,3,-10,10,52,55,-6,-5,0,3,-27,27,55,61,-3,3,0,2,-9,9,58,62,-5,-4,0,1,-10,10,61,77,-4,4,0,2,-9,9,66,74,-5,-4,0,0,-8,-3,68,72,-7,-5,0,3,3,8,68,72,-7,-5,0,3,-6,6,75,85,-3,3,0,2};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-16,16,0,27,-5,5,0,3,-6,6,3,27,-6,-5,1,3,-26,-18,20,26,-4,-1,0,1,-22,-16,24,31,-4,0,0,3,-18,-12,30,42,-3,2,0,3,-13,13,26,51,-5,5,0,3,-30,-20,35,44,-5,0,0,1,-5,5,27,51,-6,-5,1,2,-28,-22,37,42,-7,-5,0,2,-10,10,50,69,-4,4,0,3,-10,10,56,60,-5,-4,1,2,-4,4,51,67,-5,-4,1,3,-7,7,62,70,-5,-4,0,0,-7,-3,64,68,-7,-5,0,2,3,7,64,68,-7,-5,0,2,-6,6,67,86,-3,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-13,-4,0,5,-5,5,0,1,4,13,0,5,-5,5,0,1,-12,-5,4,38,-4,4,0,3,5,12,4,38,-4,4,0,3,-18,18,3,52,3,7,1,1,-14,14,36,46,-6,6,1,2,16,22,4,85,3,7,0,3,-20,-14,20,61,-5,-1,0,1,22,28,46,53,5,12,1,1,-13,13,42,46,-7,-6,0,2,-15,15,45,66,-7,7,1,3,22,30,61,68,5,12,1,2,-7,7,49,64,-8,-7,0,1,-17,-9,58,65,-5,5,0,1,9,17,58,65,-5,5,0,1,-24,-16,58,74,-5,-1,0,2,-11,11,64,81,-5,5,0,3,22,32,76,82,5,12,1,3,-10,10,69,74,-6,-5,0,0,-10,10,80,83,-3,3,0,2,-4,2,80,85,-3,3,0,2,6,12,81,85,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-22,-14,0,23,-4,4,0,3,14,22,0,23,-4,4,0,3,-32,-24,7,12,-8,-5,0,2,-28,-22,11,20,-7,-4,0,1,-16,16,6,38,2,6,0,1,-13,13,21,32,-5,2,1,2,-22,-14,23,32,-4,1,0,3,-8,8,32,42,-7,-5,0,1,-12,12,31,53,-5,4,1,3,-9,9,38,41,-8,-7,0,3,14,22,39,49,-4,1,0,3,-8,8,41,53,-7,-5,0,1,-9,9,48,51,-8,-7,0,3,14,24,56,64,4,8,0,1,-10,10,53,56,-6,-5,1,3,20,28,50,60,-7,-4,0,1,-9,9,55,76,-4,5,0,1,22,30,59,66,-11,-7,0,2,-9,9,62,70,-5,-4,0,0,-8,-3,64,68,-6,-5,0,3,3,8,64,68,-6,-5,0,3};
inline constexpr short grandleon_playstation_mesh_beast[160] = {-15,-8,0,22,-6,-2,0,2,8,15,0,22,-6,-2,0,2,-26,-18,22,27,-3,1,0,2,-22,-12,20,32,-4,2,0,2,-11,-6,18,30,-6,-5,0,3,-1,4,18,30,-6,-5,0,3,9,14,18,30,-6,-5,0,3,19,24,18,30,-6,-5,0,3,20,30,21,33,-4,2,0,2,-29,-24,25,31,-3,1,1,2,-16,26,29,33,-4,1,0,3,-10,-2,32,37,-3,0,1,3,4,12,32,37,-3,0,1,3,22,30,31,47,-3,1,0,3,21,29,36,40,-5,-2,1,3,25,35,42,47,-7,-3,0,2,26,35,43,45,-8,-7,0,0,18,32,44,54,-4,1,0,3,20,25,47,50,-5,-4,0,1,18,26,51,61,0,5,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {20,18,15,20,16,22,21,20};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,22,20,31,22,27,28,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {563,436,397,546,423,579,409,408};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,26,28,24,25,28,23,20};
