// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-15,1,0,6,-8,6,0,0,-1,15,0,6,-8,6,0,0,-10,-4,6,34,-5,5,0,2,4,10,6,34,-5,5,0,2,-14,2,34,58,-6,6,1,1,-2,14,34,58,-6,6,1,1,-11,11,58,68,-8,8,0,0,-22,-6,62,67,-11,-6,0,1,-15,-10,66,92,-6,6,0,1,10,15,66,92,-6,6,0,1,6,22,50,96,-15,-9,1,2,-7,7,58,96,-9,-7,1,2,-10,10,68,96,-7,7,0,2,-19,-6,90,102,-8,8,1,1,6,19,90,102,-8,8,1,1,-7,7,94,101,-5,5,0,0,-15,-12,66,128,-11,-7,0,3,-7,7,100,111,-6,6,0,1,-7,7,104,118,-8,8,0,3,-7,7,106,112,-10,-8,0,0,-8,8,118,123,0,10,1,2,-2,2,116,126,0,10,1,2};
inline constexpr short grandleon_playstation_mesh_archer[168] = {-12,-4,0,7,-7,5,0,0,4,12,0,7,-7,5,0,0,-11,-5,7,36,-4,4,0,1,5,11,7,36,-4,4,0,1,-11,-4,36,56,-5,5,0,0,4,11,36,56,-5,5,0,0,16,21,20,80,-8,-4,0,1,-12,12,56,70,-7,7,1,2,-12,12,68,74,-8,8,0,0,-17,-10,70,93,-6,6,0,2,-13,-6,72,104,6,13,0,0,10,17,70,96,-6,6,0,2,-12,12,74,98,-6,6,1,1,15,22,76,90,-9,-3,0,3,-12,-7,104,112,7,12,1,3,-9,9,100,112,-5,5,0,2,16,21,86,128,-8,-4,0,1,-9,9,106,119,-7,7,1,1,-8,8,117,122,2,8,1,1,-3,3,116,126,2,8,1,1,-6,6,112,115,-10,-7,0,3};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-15,15,0,6,-9,9,0,0,-13,13,5,44,-8,8,1,2,-21,-16,8,70,-8,-4,0,1,-13,13,44,52,-9,9,0,0,-13,13,50,80,-7,7,1,1,-16,-11,56,80,-6,6,1,2,11,16,56,80,-6,6,1,2,-17,-11,60,70,-9,-3,0,2,-4,4,74,84,-8,-5,0,3,-11,11,78,93,-6,6,0,2,-21,-16,70,108,-8,-4,0,1,-14,14,91,97,-9,3,1,1,-11,11,96,112,-6,3,1,2,-22,-15,106,118,-9,-3,1,3,-11,11,114,123,-4,2,1,2,-3,3,110,128,-4,2,1,2};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-14,14,0,20,-8,8,1,1,-21,21,4,70,8,15,1,0,-19,19,18,52,-7,7,1,2,-18,18,50,58,-8,8,0,0,18,23,6,96,-8,-3,0,1,-12,12,56,84,-6,6,1,3,-17,-10,60,86,-6,6,1,2,14,20,70,80,-9,-2,0,2,10,17,64,92,-7,5,1,2,-9,9,84,100,-5,6,0,1,-12,12,98,104,-6,7,1,3,5,35,92,104,-12,-2,0,1,-32,-10,100,120,6,14,0,2,3,37,102,108,-13,-1,0,0,-11,-5,104,118,-2,6,0,3,5,11,104,118,-2,6,0,3,32,38,108,118,-9,-4,0,3,2,8,108,120,-9,-4,0,3,16,24,108,128,-9,-4,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-15,15,0,7,-9,9,0,0,-13,13,6,46,-8,8,0,3,-8,-3,6,84,-10,-8,1,2,3,8,6,84,-10,-8,1,2,-13,13,56,62,-8,8,0,0,-12,12,44,80,-7,7,0,3,-20,-15,12,108,-6,-2,0,1,-14,-10,58,84,-6,6,0,3,10,14,58,84,-6,6,0,3,-16,-10,64,74,-8,-1,0,2,-12,12,84,94,-7,3,1,2,-10,10,92,107,-5,5,0,2,-11,11,102,117,-5,7,0,3,-7,7,108,112,-8,-5,0,0,-28,-8,114,120,-6,-2,0,3,-20,-15,106,128,-6,-2,0,3,-28,-8,116,127,-6,-2,0,3};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-11,-5,0,6,-8,6,0,0,2,8,0,6,-8,6,0,0,-10,-5,6,34,-5,5,0,2,3,7,6,34,-5,5,0,2,-13,10,6,92,7,15,1,0,-10,-5,34,56,-6,6,0,1,2,7,34,56,-6,6,0,1,9,13,40,68,-10,-5,0,0,-12,9,56,66,-7,7,1,1,-21,-17,16,124,4,10,0,1,-12,9,64,70,-8,8,0,0,3,20,66,71,-10,-5,0,2,-17,-11,68,92,-6,6,0,2,8,14,68,92,-6,6,0,2,-11,8,70,96,-7,7,1,3,-22,-7,90,103,-8,8,1,2,4,19,90,103,-8,8,1,2,-9,6,96,103,-5,5,0,0,-34,-17,96,122,2,12,1,3,-10,7,102,117,-8,8,0,3,-10,7,106,112,-10,-8,0,0,-25,-14,122,128,4,10,0,3,-4,1,115,128,-8,6,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {-29,-9,0,6,-8,6,0,0,9,29,0,6,-8,6,0,0,-23,-15,6,30,-5,5,0,0,15,23,6,30,-5,5,0,0,-25,-5,30,54,-6,6,0,1,5,25,30,54,-6,6,0,1,-12,12,54,62,-8,8,0,0,-12,12,58,100,6,13,1,0,-11,11,60,92,-6,6,1,1,-19,-12,64,90,-6,6,0,1,12,19,64,90,-6,6,0,1,-30,-14,86,90,-8,-4,0,2,14,30,86,90,-8,-4,0,2,-9,9,90,97,-6,-3,1,2,-10,10,96,108,-5,5,0,2,-24,-19,88,116,-8,-4,0,3,19,24,88,116,-8,-4,0,3,-11,11,102,120,-6,7,0,0,-7,7,110,115,-10,-7,0,3,-3,3,118,128,2,8,0,0};
inline constexpr short grandleon_playstation_mesh_beast[136] = {1,20,0,44,6,14,0,0,-24,-5,0,44,6,14,0,0,1,20,0,44,-15,-7,0,1,-24,-5,0,44,-15,-7,0,1,0,23,42,76,-15,13,0,2,-17,16,40,82,-14,12,0,1,-5,1,40,84,-16,14,1,2,14,20,62,72,-2,6,0,1,-28,-2,56,92,-16,14,1,1,18,23,68,94,-1,5,0,2,-39,-14,74,90,-10,0,0,1,-34,-10,78,104,-12,2,0,2,-30,-27,88,100,-9,-3,0,3,-30,-14,89,96,-18,-15,0,0,-24,-19,100,112,2,8,0,0,-37,-5,104,110,2,8,0,0,-23,-18,104,128,-6,0,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,21,16,19,17,23,20,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {447,461,484,544,447,568,418,478};
