// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[160] = {-13,-3,0,4,-5,5,0,0,3,13,0,4,-5,5,0,0,-12,-4,4,29,-4,4,0,1,4,12,4,29,-4,4,0,1,-12,-3,29,46,-5,5,1,0,3,12,29,46,-5,5,1,0,-13,13,46,55,-6,6,0,0,14,22,44,50,-9,-5,0,1,-18,-11,53,73,-5,5,0,2,11,18,53,73,-5,5,0,2,-11,11,55,75,-5,5,1,3,-23,-9,42,78,-12,-7,1,2,16,20,44,97,-9,-6,0,3,-19,-10,70,81,-6,6,1,2,10,19,70,81,-6,6,1,2,-4,4,73,79,-3,3,0,0,-6,6,78,86,-5,5,0,1,-8,8,81,92,-6,6,0,3,-8,8,82,87,-8,-6,0,0,-2,2,90,99,-5,2,1,3};
inline constexpr short grandleon_playstation_mesh_archer[136] = {-11,-3,0,3,-4,4,0,0,3,11,0,3,-4,4,0,0,-10,-4,3,25,-3,3,0,1,4,10,3,25,-3,3,0,1,-10,-3,25,40,-3,3,1,0,3,10,25,40,-3,3,1,0,-20,-15,19,53,-5,-3,0,3,-11,11,40,49,-5,5,1,1,5,12,48,68,5,10,0,1,10,17,48,64,-4,4,0,2,-17,-10,48,66,-4,4,0,2,-10,10,48,67,-4,4,1,3,-21,-14,53,63,-6,-2,0,1,-5,5,68,76,-3,3,0,1,-7,7,71,81,-5,5,1,2,-20,-15,63,87,-5,-3,0,3,-3,3,78,85,1,5,1,2};
inline constexpr short grandleon_playstation_mesh_mage[128] = {-16,16,0,6,-7,7,0,0,-14,14,5,37,-6,6,1,1,-5,5,5,37,-8,-6,1,3,17,22,8,49,-7,-4,0,1,-11,11,35,60,-5,5,1,2,-5,5,35,60,-7,-5,1,3,-15,-11,42,62,-5,5,1,1,11,15,42,62,-5,4,1,1,12,17,48,55,-8,-3,0,2,-6,6,59,71,-5,5,0,2,17,22,49,79,-7,-4,0,1,-15,15,69,76,-6,2,1,2,-10,10,74,85,-5,2,1,3,16,24,77,84,-8,-2,0,3,-6,6,83,92,-4,2,1,3,-2,2,91,99,-3,1,1,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-17,17,0,12,-3,6,1,1,-18,-13,4,21,-6,-4,0,1,-3,3,4,21,-6,-4,0,1,13,18,4,21,-6,-4,0,1,-16,16,3,41,5,10,1,0,-13,13,12,28,-1,5,1,2,-27,27,19,28,-7,-4,1,3,-33,33,28,31,-8,-3,0,2,-10,10,28,46,-1,5,1,3,7,11,31,37,-6,-4,0,3,-17,-9,31,45,-4,1,1,2,9,17,31,45,-4,1,1,2,-12,-8,31,42,-6,-4,0,3,-2,2,31,52,-6,-4,0,3,-7,7,46,58,-2,5,0,1,8,18,54,63,3,8,0,2,-9,9,58,62,-2,6,1,3,-10,-4,63,73,3,8,0,3,4,10,63,73,3,8,0,3,18,27,71,82,8,13,0,2};
inline constexpr short grandleon_playstation_mesh_healer[112] = {-16,16,0,6,-7,7,0,0,-14,14,5,37,-6,6,0,3,-5,5,5,37,-7,-6,1,3,15,20,10,82,-4,-1,0,1,-11,11,35,60,-5,5,0,3,-5,5,35,60,-7,-5,1,3,-15,-11,41,62,-4,4,0,3,11,15,41,62,-5,4,0,3,-13,13,60,68,-6,1,1,3,-6,6,68,79,-4,4,0,2,-7,7,75,87,-4,5,0,3,8,27,82,89,-4,-1,0,2,15,20,82,89,-10,4,0,2,15,20,87,94,-4,-1,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-11,-3,0,3,-5,5,0,0,3,11,0,3,-5,5,0,0,-10,-4,3,25,-3,3,0,1,4,10,3,25,-3,3,0,1,-15,15,3,64,5,11,1,1,-10,-3,25,40,-4,4,0,2,3,10,25,40,-4,4,0,2,-12,12,40,49,-5,5,1,2,19,24,14,84,3,8,0,1,-18,-11,48,64,-4,4,0,2,11,18,48,64,-4,4,0,2,-11,11,49,67,-5,5,1,3,-19,-10,63,71,-5,5,1,2,10,19,63,71,-5,5,1,2,-5,5,67,71,-3,3,0,0,23,34,67,82,-3,12,1,3,-8,8,70,80,-5,5,0,2,-22,-17,62,84,-8,-5,0,3,-8,8,72,76,-7,-5,0,0,-9,9,77,80,-6,6,0,1,-3,3,78,85,-1,8,1,3,18,25,84,88,3,8,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[152] = {-26,-16,0,5,-12,-1,0,0,16,26,0,5,-12,-1,0,0,-25,-17,5,18,-10,-3,0,1,17,25,5,18,-10,-3,0,1,-26,-17,17,29,-14,-5,0,1,17,26,17,29,-14,-5,0,1,-20,-9,29,42,-6,3,0,0,9,20,29,42,-6,3,0,0,-27,-20,29,32,-22,-18,0,3,-24,-14,35,38,-19,-16,0,3,-14,14,39,54,-10,-1,1,1,-21,-14,44,60,-14,-8,0,1,14,21,44,60,-14,-8,0,1,-14,14,54,67,-10,-1,1,3,14,24,57,60,-16,-12,0,3,-18,18,62,69,-8,1,0,1,20,27,62,66,-13,-9,0,3,-12,12,64,71,-18,-10,1,3,-8,8,70,83,-14,-6,0,0};
inline constexpr short grandleon_playstation_mesh_beast[128] = {-19,-10,0,24,3,7,0,0,11,20,0,24,3,7,0,0,-19,-10,0,24,-8,-4,0,1,11,20,0,24,-8,-4,0,1,-34,-29,24,31,1,4,1,3,-34,-25,27,34,0,4,0,1,-27,-19,31,36,-1,4,0,1,-23,19,22,45,-8,7,0,1,14,24,35,51,-5,3,0,1,12,22,41,46,-7,3,1,2,-16,-8,44,52,-3,3,1,3,8,16,44,52,-3,3,1,3,-4,4,45,54,-3,3,1,3,24,31,44,52,-14,-6,0,1,18,30,50,62,-7,0,0,2,19,26,59,68,-3,1,0,0};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {20,17,16,20,14,22,19,16};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {447,461,484,544,447,568,418,478};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,28,27,28,23,21};
