// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[184] = {-12,-4,0,4,-4,4,0,1,4,12,0,4,-4,4,0,3,-11,-5,4,21,-3,3,0,3,5,11,4,21,-3,3,0,3,-11,-4,19,34,-4,4,1,3,4,11,19,34,-4,4,1,2,12,28,5,46,-9,-4,0,0,12,28,22,27,-10,-9,0,3,-22,-16,22,40,-7,-3,1,2,-12,12,33,41,-5,5,1,2,12,16,40,56,-3,3,0,0,-16,-12,41,57,-3,3,0,1,-13,13,40,60,-5,5,0,2,-23,-15,39,56,-7,-2,0,1,-4,4,45,55,-6,-5,0,2,-4,4,51,74,5,9,0,0,-17,-10,56,62,-5,5,1,0,10,17,56,62,-5,5,0,2,-9,9,58,63,-3,3,0,1,-22,-16,55,65,-7,-3,1,2,-6,6,62,74,-4,4,0,2,-6,6,66,69,-5,-4,0,0,-5,5,72,78,-5,5,0,2};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-10,-3,0,5,-4,4,0,1,3,10,0,5,-4,4,0,1,-9,-4,5,24,-3,3,1,1,4,9,5,24,-3,3,0,1,-11,11,23,37,-5,5,0,1,-8,8,36,62,-4,4,0,2,10,14,42,57,-3,3,0,1,-14,-10,44,58,-3,3,1,3,11,25,46,52,-9,-5,0,1,-5,11,48,53,-9,-5,0,1,-26,-10,49,53,-9,-6,0,2,-33,-27,48,56,-10,-5,0,3,-3,3,52,57,-5,-4,0,2,-3,3,52,78,5,9,0,0,-8,8,61,72,-3,3,0,2,-9,9,65,69,-5,-3,0,2,-5,5,66,68,-6,-4,0,2,-10,10,70,78,-4,4,0,1,-10,10,78,82,-2,2,1,3,-3,3,77,85,-2,2,1,2};
inline constexpr short grandleon_playstation_mesh_mage[176] = {-9,-3,0,5,-5,5,0,3,3,9,0,5,-5,5,1,3,-8,-3,5,19,-3,3,0,3,3,8,5,19,-3,3,0,0,-14,14,17,46,-6,6,1,3,-2,2,20,43,-8,-6,1,2,11,18,37,46,-5,1,0,2,10,14,45,62,-3,3,0,0,-14,-10,46,65,-4,4,1,3,-8,8,45,69,-5,5,1,3,-20,-16,57,62,-2,1,0,0,-7,7,56,73,5,8,0,2,-24,-12,63,71,-4,2,0,0,-21,-15,65,69,-5,-4,0,0,-3,3,62,88,5,9,0,0,-7,7,68,74,-6,2,0,2,-5,5,73,85,-5,5,0,2,-5,5,76,81,-6,-5,0,2,-6,6,83,92,-5,5,0,2,-4,4,87,89,-6,-4,0,1,-2,6,90,95,-2,2,0,2,0,4,90,99,-2,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-10,10,0,15,-6,6,1,2,-8,8,6,48,5,10,1,1,-8,8,13,39,-4,4,0,2,-8,8,34,40,-6,-4,0,3,15,19,0,82,-2,2,0,0,-13,-9,39,58,-3,3,0,1,-6,6,37,62,-4,4,1,3,9,14,40,59,-3,3,0,1,-3,3,43,52,-6,-4,1,3,-29,-21,51,65,-3,3,0,3,-2,3,55,77,6,10,0,0,-9,9,61,73,-4,4,0,1,-9,9,65,69,-5,-4,0,2,-11,11,70,80,-4,5,0,1,-7,7,74,77,-6,-4,0,1,-3,3,79,87,-1,4,0,0,5,29,79,86,-4,4,0,0,6,28,85,91,-3,3,0,2,6,28,90,94,-1,1,0,0,14,20,90,95,-1,1,0,1};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-12,-4,0,4,-4,4,0,1,3,11,0,4,-4,4,0,1,-11,-4,4,23,-3,3,0,3,3,10,4,23,-3,3,0,2,-16,15,22,42,-5,5,0,3,-4,3,25,39,-7,-5,1,3,-14,14,41,66,-4,4,0,3,12,17,45,64,-3,3,0,3,-18,-13,44,63,-5,1,0,0,-13,12,51,55,-6,-4,0,3,-3,2,47,60,-6,-4,1,3,-20,19,64,71,-6,6,0,2,12,22,63,79,3,8,0,0,-16,15,70,82,-4,4,0,2,-16,15,74,78,-5,-4,0,2,-17,16,79,90,-4,6,0,2,-4,3,89,93,-1,3,0,0};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-11,-3,0,4,-4,4,0,2,3,11,0,4,-4,4,0,2,-10,-4,4,27,-4,4,0,2,4,10,4,27,-4,4,0,3,-13,13,6,65,5,10,1,1,-13,13,25,46,-5,5,0,1,-22,-18,0,86,-1,4,1,3,-12,12,43,49,-6,6,0,2,-15,-11,49,67,-4,4,0,2,11,15,49,67,-4,4,0,2,-11,11,48,71,-6,6,0,1,-9,9,55,61,-7,-6,0,2,-3,3,57,83,4,9,0,0,-16,-9,67,75,-5,5,0,2,9,16,67,75,-5,5,1,2,-36,-18,63,83,0,4,0,3,-9,9,71,77,-3,3,0,1,-11,11,75,88,-4,4,0,1,-11,11,78,83,-6,-4,0,1,-23,-17,85,94,-1,4,0,3,-8,8,86,94,-5,5,0,2,-2,2,91,95,-4,5,0,0};
inline constexpr short grandleon_playstation_mesh_rogue[176] = {-11,-3,0,4,-4,3,0,2,3,11,0,4,-4,3,0,1,-10,-4,4,21,-3,2,0,1,4,10,4,21,-3,2,0,1,-10,-3,20,31,-4,3,0,1,3,10,20,31,-4,3,0,0,-9,9,30,39,-5,4,1,3,-25,-18,36,40,-5,0,0,0,18,25,38,42,-5,0,0,0,-14,-10,39,53,-3,2,0,2,10,14,40,54,-3,2,0,1,-9,9,38,58,-4,3,0,1,-9,9,40,64,4,8,0,2,-24,-20,39,57,-4,-1,0,3,-2,2,40,54,-5,-4,0,1,20,24,40,58,-4,-1,0,0,-2,4,44,68,5,9,0,0,-10,10,58,63,-4,3,0,2,-10,10,62,77,-4,4,0,0,-9,9,66,69,-6,-4,0,3,-7,7,68,72,-7,-5,0,1,-4,4,75,81,-3,2,0,2};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-15,-9,0,28,3,8,0,0,11,17,0,28,3,8,0,0,-15,-9,0,28,-9,-4,0,2,11,17,0,28,-9,-4,0,2,22,28,28,33,-4,0,0,0,-23,-18,30,39,-4,1,0,1,-15,17,26,44,-8,5,0,2,-14,16,29,33,-9,-8,0,2,12,36,33,45,-5,1,0,1,-24,-21,37,45,-2,0,1,2,22,26,37,41,-7,-5,0,2,16,32,38,41,-10,-9,0,2,-21,3,43,50,-5,3,0,2,-1,23,43,50,-5,3,0,2,-3,3,49,60,-3,1,1,2,-15,17,55,62,-2,1,0,0,-1,3,59,73,-2,1,0,0,-2,4,72,78,-2,1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {23,20,22,20,17,22,22,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,22,30,21,25,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {448,413,408,490,411,535,408,484};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,25,28,27,27,28,23,24};
