// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[192] = {-12,-4,0,6,-7,6,0,0,4,12,0,6,-7,6,0,0,-11,-5,6,34,-5,5,0,2,5,11,6,34,-5,5,0,2,-11,-4,34,54,-5,5,0,1,4,11,34,54,-5,5,0,1,-14,14,50,62,-8,8,1,1,-12,12,62,70,-8,8,0,0,13,21,60,66,-9,-5,0,1,-16,-10,68,92,-6,6,0,1,10,16,68,92,-6,6,0,1,-25,-7,58,92,-14,-9,1,2,-10,10,70,94,-6,6,0,2,-4,4,62,94,-8,-6,1,3,-3,3,88,108,6,12,0,0,-17,-9,90,100,-7,7,1,2,9,17,90,100,-7,7,1,2,-4,4,92,99,-5,5,0,0,15,19,64,128,-10,-6,0,3,-9,9,98,110,-6,6,0,2,-8,8,106,117,-7,7,0,3,-9,9,116,121,-2,8,1,3,-7,7,111,114,-9,-6,0,0,-2,2,115,124,-2,8,1,3};
inline constexpr short grandleon_playstation_mesh_archer[168] = {-11,-4,0,6,-7,5,0,0,4,11,0,6,-7,5,0,0,-10,-5,6,34,-4,4,0,1,5,10,6,34,-4,4,0,1,-10,-4,34,52,-5,5,0,0,4,10,34,52,-5,5,0,0,-20,-16,24,78,-8,-4,0,3,-13,13,48,64,-8,8,1,1,-12,12,62,68,-8,8,0,0,9,15,70,92,-5,5,0,2,-11,11,68,96,-5,5,1,2,-16,-9,70,95,-5,5,0,2,6,13,74,102,6,13,0,1,-21,-14,74,88,-9,-3,0,0,-3,3,84,104,5,11,0,0,-9,9,98,110,-5,5,0,2,-20,-16,84,128,-8,-4,0,3,-9,9,104,116,-6,6,1,2,-8,8,109,112,-8,-5,0,0,-2,2,113,122,2,7,1,2,-8,8,116,121,2,7,1,2};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-16,16,0,6,-9,9,0,0,-14,14,5,40,-8,8,1,1,-3,3,5,40,-10,-8,1,3,15,20,10,66,-8,-4,0,1,-14,14,38,72,-6,6,1,2,-3,3,38,72,-8,-6,1,3,-3,3,60,80,6,11,0,0,11,16,58,66,-9,-3,0,2,-14,-10,62,80,-5,5,1,1,10,14,62,80,-5,5,1,1,-13,13,76,92,2,8,0,0,-12,12,78,92,-6,6,0,2,15,20,66,104,-8,-4,0,1,-14,14,90,96,-8,3,1,2,-13,13,92,94,-10,-7,0,0,-12,12,95,110,-5,3,1,3,7,29,102,112,-9,-3,0,3,-12,12,112,122,-4,2,1,3,-3,3,108,128,-4,2,1,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-14,14,0,22,-8,8,1,1,-19,19,6,66,7,13,1,0,-19,19,20,54,-6,6,1,2,-22,-17,8,94,-8,-3,0,1,-12,12,52,58,-7,7,0,0,-12,12,56,84,-5,5,1,3,9,15,60,84,-5,5,1,2,-2,3,68,90,6,11,0,0,-19,-13,68,78,-9,-2,0,2,-16,-9,64,90,-6,5,1,2,-10,10,84,99,-5,6,0,1,-10,10,97,103,-5,7,1,3,-35,-5,90,102,-12,-2,0,1,11,31,102,122,6,14,0,2,-37,-5,100,106,-13,-1,0,0,-10,-5,103,114,-2,6,0,3,5,10,103,114,-2,6,0,3,-9,-3,106,116,-9,-4,0,3,-37,-31,106,117,-9,-4,0,3,-24,-16,106,128,-9,-4,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-16,16,0,6,-9,9,0,0,-15,15,5,42,-8,8,0,3,-3,3,5,80,-10,-7,1,1,-13,13,52,58,-7,7,0,0,-13,13,40,78,-6,6,0,3,15,19,14,104,-6,-2,0,1,-13,-9,56,82,-5,5,0,3,9,13,56,82,-5,5,0,3,10,16,62,72,-8,-1,0,2,-14,14,79,89,6,10,0,3,-3,3,80,100,6,10,0,3,-11,11,88,102,3,8,0,1,-10,10,90,104,-5,5,0,2,-12,12,100,116,-4,7,0,3,-11,11,107,111,-6,-3,0,0,5,29,110,117,-6,-2,0,3,14,19,104,128,-6,-2,0,3};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-11,-4,0,6,-8,6,0,0,4,11,0,6,-8,6,0,0,-10,-5,6,32,-5,5,0,2,5,10,6,32,-5,5,0,2,-10,-4,32,50,-5,5,0,1,4,10,32,50,-5,5,0,1,-13,13,6,90,7,14,1,1,-13,13,46,60,-7,7,1,1,-12,12,58,64,-8,8,0,0,19,24,14,122,4,10,0,1,-17,-11,66,90,-6,6,0,2,12,19,66,90,-6,6,0,2,-12,12,64,92,-6,6,1,3,-3,3,78,100,5,11,0,0,-18,-10,88,100,-7,7,1,2,10,18,88,100,-7,7,1,2,-4,4,94,100,-5,5,0,0,19,39,94,120,2,12,1,3,-10,10,99,111,-6,6,0,1,-10,10,108,117,-7,7,0,3,-9,9,112,114,-9,-6,0,0,15,29,120,128,4,10,0,3,-2,2,115,128,-7,5,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-27,-9,0,6,-8,6,0,0,9,27,0,6,-8,6,0,0,-21,-14,6,28,-5,5,0,0,14,21,6,28,-5,5,0,0,-24,-4,28,50,-6,6,0,1,4,24,28,50,-6,6,0,1,-12,12,46,56,-7,7,1,1,-11,11,54,60,-8,8,0,0,-12,12,56,98,6,12,1,0,-11,11,58,90,-5,5,1,2,-16,-10,62,88,-5,5,0,1,10,16,62,88,-5,5,0,1,-3,3,76,98,8,13,0,1,-29,-11,84,88,-8,-4,0,2,11,29,84,88,-8,-4,0,2,-10,10,88,95,-5,-2,1,3,-10,10,94,106,-5,5,0,2,-22,-17,86,112,-8,-4,0,3,17,22,86,112,-8,-4,0,3,-11,11,100,117,-5,6,0,0,-10,10,108,112,-7,-4,0,3,-10,10,116,123,2,7,0,0,-2,2,114,128,2,7,0,0};
inline constexpr short grandleon_playstation_mesh_beast[144] = {8,14,0,42,6,14,0,0,-18,-11,0,42,6,14,0,0,8,14,0,42,-15,-7,0,1,-18,-11,0,42,-15,-7,0,1,20,24,40,52,0,6,1,3,18,23,48,62,-1,5,0,2,-2,23,40,74,-15,13,0,2,-15,15,38,80,-14,12,0,1,-5,1,38,82,-16,14,1,2,14,20,58,68,-2,6,0,1,-26,-2,54,90,-15,13,1,1,-36,-12,72,88,-10,0,0,1,-33,-9,76,102,-12,2,0,2,-28,-25,86,94,-9,-3,0,3,-24,-18,87,94,-14,-11,0,0,-24,-19,98,110,2,8,0,0,-36,-7,104,110,2,8,0,0,-21,-17,102,128,-6,0,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {24,21,19,20,17,23,23,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {473,470,500,564,473,585,428,483};
