// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[184] = {-12,-4,0,6,-7,7,0,0,4,12,0,6,-7,7,0,0,-11,-5,6,34,-5,5,0,1,5,11,6,34,-5,5,0,1,-11,-4,32,56,-6,6,0,2,4,11,32,56,-6,6,0,2,12,28,8,76,-15,-7,1,3,12,28,36,44,-17,-15,0,3,-22,-16,36,66,-11,-5,0,1,-12,12,54,68,-9,9,1,1,12,16,66,92,-5,5,0,1,-16,-12,68,94,-5,5,0,1,-13,13,66,98,-8,8,1,2,-23,-15,64,92,-12,-4,0,2,-4,4,74,90,-10,-8,0,3,-4,4,84,122,8,14,0,0,-17,-10,92,102,-8,8,1,2,10,17,92,102,-8,8,1,2,-9,9,96,104,-5,5,0,0,-22,-16,90,106,-11,-5,0,3,-6,6,102,122,-7,7,0,2,-6,6,108,114,-9,-7,0,0,-5,5,118,128,-8,8,0,0};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-10,-3,0,7,-6,6,0,0,3,10,0,7,-6,6,0,0,-9,-4,7,36,-4,4,0,2,4,9,7,36,-4,4,0,2,-11,11,34,56,-8,8,1,1,-8,8,54,94,-6,6,1,2,10,14,64,86,-5,5,0,1,-14,-10,66,88,-5,5,0,1,11,25,70,78,-13,-7,0,1,-5,11,72,80,-14,-8,0,2,-26,-10,74,80,-13,-9,0,2,-33,-27,72,84,-15,-7,0,3,-3,3,78,86,-8,-6,0,3,-3,3,78,118,7,13,0,0,-8,8,92,108,-5,5,0,2,-8,8,99,103,-7,-4,0,0,-9,9,98,104,-7,-5,0,3,-10,10,106,118,-6,6,0,0,-10,10,117,123,-3,3,0,0,-3,3,116,128,-3,3,0,0};
inline constexpr short grandleon_playstation_mesh_mage[176] = {-9,-3,0,6,-6,6,0,0,3,9,0,6,-6,6,0,0,-8,-3,6,24,-4,4,0,2,3,8,6,24,-4,4,0,2,-14,14,22,60,-8,8,1,1,-2,2,26,56,-10,-8,0,3,11,18,48,60,-7,1,0,3,10,14,58,80,-4,4,0,2,-14,-10,60,84,-5,5,1,1,-8,8,58,90,-6,6,1,2,-20,-16,74,80,-3,1,0,3,-7,7,72,94,6,11,0,1,-24,-12,82,92,-5,3,0,2,-21,-15,84,90,-7,-5,0,3,-3,3,80,114,7,12,0,0,-7,7,88,96,-5,5,0,0,-5,5,94,110,-6,6,0,2,-5,5,99,105,-8,-6,0,3,-6,6,108,119,-6,6,1,1,-5,5,113,116,-8,-5,0,3,-2,6,117,123,-2,2,0,2,0,4,117,128,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-10,10,0,20,-8,8,1,0,-8,8,8,64,7,13,1,1,-8,8,18,52,-6,6,1,2,-8,8,46,54,-8,-6,0,0,15,19,0,110,-3,3,0,1,-13,-9,52,78,-4,4,1,1,-6,6,50,84,-6,6,1,3,9,14,54,80,-4,4,1,1,-3,3,58,70,-8,-6,0,3,-29,-21,68,88,-4,4,0,3,-2,3,74,104,8,13,0,0,-9,9,82,98,-5,5,0,1,-9,9,87,93,-7,-5,0,3,-11,11,94,108,-5,7,1,2,-10,10,100,104,-7,-4,0,0,-3,3,106,117,-1,5,1,2,5,29,106,116,-6,6,0,2,6,28,114,123,-4,4,0,3,6,28,121,126,-2,2,0,3,14,20,121,128,-2,2,0,3};
inline constexpr short grandleon_playstation_mesh_healer[144] = {-12,-4,0,6,-6,6,0,0,3,11,0,6,-6,6,0,0,-11,-4,6,32,-4,4,0,3,3,10,6,32,-4,4,0,3,-16,15,30,58,-7,7,0,3,-4,3,34,54,-9,-7,1,3,-14,14,56,90,-6,6,0,3,-18,-13,60,86,-4,4,0,3,12,17,62,88,-4,4,0,3,-13,12,70,76,-8,-6,1,3,-3,2,64,82,-8,-6,1,3,12,22,86,108,4,11,0,2,-20,19,88,98,-8,8,1,2,-17,16,92,95,-10,-7,0,0,-16,15,96,112,-5,5,0,2,-16,15,101,107,-7,-5,0,0,-17,16,108,124,-6,8,0,3,-4,3,122,128,-2,4,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-11,-3,0,6,-6,6,0,0,3,11,0,6,-6,6,0,0,-10,-4,6,36,-5,5,0,1,4,10,6,36,-5,5,0,1,-13,13,8,88,7,14,1,1,-13,13,34,62,-7,7,1,2,-22,-18,0,116,-1,5,0,1,-12,12,58,66,-8,8,0,0,-15,-11,66,90,-5,5,0,2,11,15,66,90,-5,5,0,2,-11,11,64,96,-8,8,1,3,-9,9,74,82,-10,-8,0,3,-3,3,76,112,6,12,0,0,-16,-9,90,101,-7,7,1,2,9,16,90,101,-7,7,1,2,-36,-18,84,112,0,6,1,3,-9,9,96,103,-4,4,0,0,-11,11,101,118,-6,6,0,2,-11,11,105,111,-8,-6,0,0,-23,-17,114,126,-1,5,0,3,-8,8,116,126,-7,7,0,0,-2,2,122,128,-5,7,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[176] = {-11,-3,0,6,-7,5,0,0,3,11,0,6,-7,5,0,0,-10,-4,6,34,-5,3,0,1,4,10,6,34,-5,3,0,1,-10,-3,32,50,-6,4,0,1,3,10,32,50,-6,4,0,1,-9,9,48,62,-8,6,0,0,-25,-18,58,64,-8,0,0,0,18,25,60,66,-8,0,0,0,-14,-10,62,84,-5,3,0,2,10,14,64,86,-5,3,0,2,-9,9,60,92,-6,4,1,2,-9,9,64,102,6,12,0,0,-24,-20,62,90,-7,-1,0,3,-2,2,64,86,-8,-6,0,3,20,24,64,92,-7,-1,0,3,-2,4,70,108,8,14,0,0,-10,10,92,100,-7,5,0,1,-10,10,98,122,-7,7,0,0,-9,9,105,110,-9,-7,0,3,-9,9,108,114,-9,-6,0,3,-4,4,120,128,-5,3,0,0};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-15,-9,0,46,5,13,0,0,11,17,0,46,5,13,0,0,-15,-9,0,46,-15,-7,0,1,11,17,0,46,-15,-7,0,1,22,28,46,54,-7,0,0,0,-15,17,42,72,-13,9,0,1,-23,-18,50,64,-7,1,0,1,-14,16,48,54,-15,-13,0,3,12,36,54,74,-9,1,0,2,-24,-21,60,74,-4,0,1,2,22,26,60,68,-11,-9,0,3,22,26,63,68,-11,-8,0,0,-21,3,70,82,-9,5,1,2,-1,23,70,82,-9,5,1,2,-3,3,80,98,-5,1,0,1,-15,17,90,102,-3,1,0,2,-1,3,96,120,-3,1,0,2,-2,4,118,128,-4,2,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {23,20,22,20,18,22,22,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,22,30,21,25,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {448,413,408,490,411,535,408,484};
