// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-17,1,0,5,-5,5,0,1,-2,16,0,5,-5,5,0,1,-12,-6,12,20,3,9,0,0,-10,-5,5,24,-4,4,0,2,4,10,5,24,-4,4,0,2,-12,11,23,37,-6,6,1,2,-11,10,34,39,-7,-5,0,2,-11,10,35,61,-5,5,0,2,-26,-5,28,62,-9,-7,0,1,-25,-6,34,57,-12,-9,0,2,14,17,51,57,-3,1,0,1,7,24,56,60,-3,-1,0,0,-3,3,57,76,6,12,0,0,-13,-8,58,66,-5,5,0,2,7,13,58,66,-5,5,0,2,-11,10,65,81,-5,5,0,2,14,17,57,87,-3,-1,0,2,-3,3,67,73,-9,-5,0,2,-10,-7,66,83,-4,5,0,2,7,10,66,83,-4,5,0,2,-2,1,68,71,-10,-9,0,2,-9,-5,80,86,-1,4,0,0,4,9,80,86,-1,4,0,2,-18,4,83,86,-1,4,0,2,-11,10,77,84,-7,-5,0,2};
inline constexpr short grandleon_playstation_mesh_archer[176] = {-9,-2,0,5,-6,4,0,1,4,10,0,5,-6,4,0,2,-8,-3,5,25,-4,4,0,2,5,10,5,25,-4,4,0,3,9,27,16,23,4,9,0,1,22,28,22,35,5,11,0,0,-20,-14,7,44,-4,0,0,2,-10,12,23,41,-6,6,1,3,-9,11,38,42,-7,-5,0,2,-7,9,39,63,-5,5,0,2,8,14,51,57,-8,-3,0,1,-11,-5,50,73,4,10,0,1,-13,-7,50,63,-6,-1,0,1,-6,8,66,80,5,9,0,0,-20,-14,44,93,-4,0,0,2,-7,7,64,79,-5,5,0,2,-2,3,66,73,-9,-5,0,2,-1,2,68,71,-10,-9,0,2,-6,8,76,82,-7,-5,0,3,-10,2,80,87,-1,4,0,2,-6,-1,77,90,-1,4,0,2,2,7,77,90,-1,4,0,2};
inline constexpr short grandleon_playstation_mesh_mage[176] = {-16,16,0,10,-7,7,0,1,-20,-14,0,41,-4,1,0,2,-14,14,9,39,-6,6,1,3,-4,4,9,64,-8,-6,1,3,-13,13,38,44,-7,-6,0,2,-11,11,42,64,-6,6,1,3,9,15,44,61,-5,2,0,0,-15,-9,44,61,-5,1,1,3,-20,-14,41,81,-4,1,0,2,-12,12,58,79,6,10,0,0,-12,12,61,65,-8,-6,1,2,-12,12,65,80,-5,5,0,2,-3,3,68,74,-9,-5,0,2,-2,2,69,72,-10,-9,0,2,-14,14,79,83,-6,6,0,2,-13,13,77,81,-7,-5,0,2,-14,-6,81,88,-1,4,0,3,6,14,81,88,-1,4,0,2,-29,-5,79,87,-4,1,0,2,-12,-8,87,93,-1,4,0,3,8,12,87,93,-1,4,0,0,-14,-6,89,92,-1,4,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[176] = {-11,11,0,14,-7,7,1,2,-8,8,12,39,-6,6,0,1,-4,4,12,63,-8,-5,0,2,-6,6,36,41,-8,-5,1,2,-38,-32,0,86,-3,2,0,0,-9,9,38,63,-5,5,1,3,8,14,42,62,-5,2,0,2,-16,-8,44,65,-5,2,0,2,-10,10,59,78,6,11,0,0,24,32,65,71,-3,5,0,0,-10,10,62,66,-8,-5,0,2,-11,11,65,80,-5,5,0,2,-3,3,68,73,-8,-5,0,2,18,26,74,80,0,6,0,2,28,34,77,83,-2,3,0,0,-10,-4,78,86,-1,5,0,2,4,10,78,86,-1,5,0,3,-19,5,82,86,-1,5,0,0,-13,13,77,83,-7,-5,0,3,-29,-11,84,90,-5,4,0,2,-22,-4,87,93,-6,-4,0,3,-29,-11,89,96,-6,0,0,2};
inline constexpr short grandleon_playstation_mesh_healer[152] = {-14,14,0,9,-6,6,0,1,-13,13,8,33,-5,5,1,3,-11,11,8,33,-7,-5,0,3,-31,-7,28,37,-4,3,0,3,-14,14,29,34,-7,-5,0,3,-31,-7,36,40,-5,3,0,3,-23,-15,38,45,-3,2,0,3,-14,14,30,54,-5,5,0,3,-13,-8,33,50,-4,1,1,3,11,16,36,53,-5,1,0,1,-3,3,46,66,6,10,0,1,-11,11,54,67,-5,5,0,3,-3,3,56,61,-8,-5,0,3,-2,2,57,60,-9,-8,1,3,-11,11,62,78,-3,7,0,3,6,12,66,73,-3,1,0,1,-12,-6,66,73,-3,1,0,3,-10,10,65,70,-6,-5,0,3,-9,9,75,85,-1,5,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-7,-1,0,5,-6,6,0,2,4,11,0,5,-6,6,0,1,-6,-1,5,25,-4,4,0,2,5,10,5,25,-4,4,1,2,-10,13,3,57,5,10,1,1,-10,13,23,42,-7,7,0,1,19,24,0,83,2,7,0,2,-8,12,39,45,-8,-7,0,2,-8,12,42,69,-6,6,0,2,-1,5,48,63,-8,-6,0,2,-1,4,58,76,6,12,0,0,20,36,61,80,1,7,1,2,-11,-6,64,72,-6,4,0,3,9,15,64,72,-6,4,0,2,26,31,67,74,0,1,0,0,-8,12,72,86,-5,5,0,3,-7,11,73,79,-7,-5,0,3,18,25,82,91,2,7,0,1,-8,-4,82,89,-1,4,0,1,8,12,82,89,-1,4,0,2,-16,3,86,90,-1,4,0,0,0,3,85,93,-7,4,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-12,-5,0,5,-5,2,0,1,5,12,0,5,-5,2,0,0,14,30,10,16,2,7,0,2,-11,-6,5,19,-5,1,0,2,6,11,5,19,-5,1,0,1,24,32,15,24,3,8,0,1,-14,14,17,30,-5,3,0,1,-12,12,29,33,-6,1,0,3,-11,11,32,49,-5,3,0,2,-15,-9,34,46,-6,-1,0,2,9,15,34,46,-6,-1,0,1,-18,-10,44,48,-5,-3,0,0,10,18,44,48,-5,-3,0,2,-4,4,50,63,5,9,0,0,-25,-21,46,60,-5,-3,0,3,12,16,46,60,-5,-3,0,2,-7,7,51,63,-4,4,0,3,-9,9,52,66,-2,5,1,3,-3,3,53,58,-7,-4,1,3,-2,2,54,56,-8,-7,0,0,-8,8,60,64,-5,-4,0,2,-7,7,64,71,1,5,0,1,-7,-2,65,74,-1,3,0,3,2,7,65,74,-1,3,0,2,-9,1,70,74,-1,3,0,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {10,16,0,19,3,7,0,0,-8,-3,0,19,3,7,0,0,10,16,0,19,-7,-3,0,1,-8,-3,0,19,-7,-3,0,1,-11,11,17,22,-7,7,0,2,14,18,21,30,-1,2,0,1,-12,16,17,34,-6,6,0,1,-34,-14,22,29,-8,-3,0,2,-29,-7,20,37,-5,4,0,1,17,21,28,33,0,3,0,1,-27,-23,27,32,-3,0,0,1,-25,-21,25,30,-9,-7,0,2,-20,-15,32,34,-6,-5,0,2,-19,-14,36,42,1,4,0,1,-19,-14,36,42,-4,-1,0,2,4,8,33,49,-1,1,0,2,-4,0,33,56,-1,1,1,3,-23,5,39,53,-1,1,0,1,-12,-8,33,61,-1,1,0,1};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,22,22,22,19,22,25,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,24,20,32,20,26,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {472,485,471,531,487,569,415,425};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,27,28,28,26,28,22,19};
