// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-14,-4,0,5,-5,5,0,0,4,14,0,5,-5,5,0,0,-13,-5,5,25,-4,4,0,1,5,13,5,25,-4,4,0,1,-14,-4,24,40,-5,5,0,1,4,14,24,40,-5,5,0,1,-13,13,39,55,-6,6,1,3,-26,-8,23,65,-8,-5,0,2,-23,-11,29,59,-10,-8,1,2,-19,-15,41,51,-12,-10,0,3,-12,12,53,68,-7,7,0,1,12,24,56,63,-9,-7,0,2,-19,-11,61,69,-6,6,0,1,11,19,61,69,-6,6,0,1,20,28,64,72,-9,-7,0,2,-12,12,67,83,-7,7,0,1,-5,5,69,76,-10,-7,0,2,-2,2,70,73,-11,-10,0,0,-13,-7,79,85,0,5,0,1,7,13,79,85,0,5,0,1,22,28,71,83,-10,-7,0,3,-4,4,75,83,-9,-7,0,3};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-13,-5,0,6,-6,6,0,0,5,13,0,6,-6,6,0,0,-12,-6,6,26,-4,4,0,2,6,12,6,26,-4,4,0,2,12,26,18,25,3,8,0,2,20,28,24,37,4,10,0,2,-24,-16,6,44,-6,0,0,1,-12,-4,25,42,-5,5,0,2,4,12,25,42,-5,5,0,2,-11,11,40,62,-6,6,1,3,-18,-8,51,57,-8,-3,0,2,8,14,49,61,-7,-1,0,2,10,16,51,74,3,8,0,1,-24,-16,43,80,-6,0,0,1,-11,11,60,65,-8,-6,1,2,-9,9,64,78,-6,6,0,2,-4,4,66,72,-10,-6,0,1,-2,2,67,70,-11,-10,0,0,-10,-4,75,89,0,6,0,2,4,10,75,89,0,6,0,2};
inline constexpr short grandleon_playstation_mesh_mage[168] = {-14,14,0,13,-6,6,0,1,-19,-13,0,41,-4,1,0,1,-13,13,11,36,-6,6,0,1,-5,5,10,36,-9,-6,1,3,-18,-12,36,43,-9,-3,0,2,12,18,36,43,-9,-3,0,2,-13,13,34,53,-7,7,0,2,-5,5,34,53,-9,-7,1,3,-17,-11,40,60,-6,3,0,2,11,17,40,60,-6,3,0,2,-19,-13,40,74,-4,1,0,1,-12,12,51,67,-7,7,0,2,-5,5,51,67,-9,-7,1,3,-12,12,64,70,-10,-8,1,2,-10,10,69,84,-6,6,0,2,-5,5,71,79,-11,-6,0,1,-20,-12,73,86,-6,3,0,2,-2,2,72,76,-12,-11,0,0,-14,-8,79,89,1,7,0,1,8,14,79,89,1,7,0,1,-18,-14,84,91,-5,2,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-15,15,0,16,-6,6,1,2,-13,13,14,34,-6,6,1,2,-6,6,14,34,-8,-6,1,3,-12,12,32,54,-6,6,0,2,-6,6,32,54,-8,-6,1,3,-26,-12,49,56,-4,3,0,2,12,26,49,56,-4,3,0,2,-32,-24,49,57,-5,1,0,2,24,32,49,57,-5,1,0,2,-32,-22,57,63,0,8,0,1,22,32,57,63,0,8,0,1,-8,8,54,58,-8,-6,1,3,-9,9,57,70,-6,6,0,2,-3,3,60,64,-8,-6,0,0,-26,-8,67,75,1,8,0,3,8,26,67,75,1,8,0,3,-30,-16,74,83,4,10,0,3,16,30,74,83,4,10,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-17,17,0,11,-6,6,0,2,-9,-4,0,4,-8,-6,0,0,4,9,0,4,-8,-6,0,0,-16,16,10,30,-6,6,0,2,-5,5,10,30,-8,-6,1,3,-22,-14,13,47,-5,4,0,3,14,22,13,47,-5,4,0,3,-15,15,29,52,-6,6,0,2,-5,5,29,52,-8,-6,1,3,14,20,39,63,0,5,0,1,-15,15,52,57,-8,-4,1,2,12,22,61,71,1,8,0,1,-14,14,56,73,-6,6,0,2,-13,-3,58,70,-8,-6,0,3,3,13,58,70,-8,-6,0,3,-2,2,63,70,-9,-8,0,0,-9,9,71,81,-5,5,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-13,-3,0,6,-6,6,0,1,3,13,0,6,-6,6,0,1,-12,-4,6,27,-4,4,0,1,4,12,6,27,-4,4,0,1,-18,18,3,58,6,11,1,2,-20,-14,7,58,-3,3,0,1,20,26,0,80,3,7,0,1,-14,14,38,53,-6,6,1,3,-12,12,48,53,-9,-7,0,3,-17,-12,51,66,-6,3,0,1,12,17,51,66,-6,3,0,1,-12,12,52,70,-7,7,0,1,-20,-12,56,73,-4,3,0,3,-18,-10,62,69,-8,1,0,2,10,18,62,69,-8,1,0,2,24,32,66,82,0,10,1,3,-15,15,68,84,-8,8,0,3,-8,8,70,82,-10,-8,0,1,-5,5,72,78,-12,-10,0,2,20,26,80,90,3,7,0,3,-12,-6,82,89,0,6,0,2,6,12,82,89,0,6,0,2};
inline constexpr short grandleon_playstation_mesh_rogue[176] = {-14,-6,0,6,-6,1,0,2,6,14,0,6,-6,1,0,2,14,30,8,13,2,7,0,1,-13,-7,4,18,-6,0,0,2,7,13,4,18,-6,0,0,2,24,30,12,21,3,8,0,1,-14,14,2,32,4,8,0,1,-28,-14,12,17,-10,-7,0,3,-13,-5,17,30,-4,1,0,2,5,13,17,30,-4,1,0,2,-12,12,29,34,-7,0,0,1,-17,-11,34,44,-8,-1,0,2,-11,11,33,49,-6,3,1,3,11,17,39,49,-8,-1,0,2,-5,5,36,51,-7,-6,0,3,-11,11,48,52,-7,-6,1,2,14,28,46,51,-11,-8,0,3,-9,9,51,63,-5,5,0,2,-4,4,53,57,-8,-5,0,3,-2,2,53,56,-9,-8,0,0,-9,-3,61,71,0,4,0,2,3,9,61,71,0,4,0,2};
inline constexpr short grandleon_playstation_mesh_beast[136] = {-22,-15,0,20,3,7,0,0,-1,6,0,20,3,7,0,0,-22,-15,0,20,-7,-4,0,1,-1,6,0,20,-7,-4,0,1,-25,-19,21,26,-1,3,0,1,-28,-22,22,28,0,4,1,3,-26,14,18,36,-7,6,0,1,24,34,22,30,-8,-4,0,1,16,32,21,38,-6,4,0,1,28,34,28,35,-4,-1,0,2,26,32,26,32,-9,-7,0,2,18,24,34,36,-7,-6,0,3,-24,-20,36,49,-2,2,1,3,-15,-11,36,49,-2,2,1,3,-6,-2,36,60,-2,2,1,3,3,7,36,60,-2,2,1,3,12,16,36,60,-2,2,1,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,20,21,18,17,22,22,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {26,26,20,32,22,26,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {491,502,489,549,505,588,430,442};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,27,28,28,26,28,22,19};
