// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'undead' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 5;
inline constexpr const char* grandleon_playstation_mesh_style_name = "undead";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[160] = {-13,-4,0,8,-8,8,0,1,4,13,0,8,-8,8,0,1,-34,-24,0,14,-10,-4,0,1,-12,-5,6,40,-6,6,0,3,5,12,6,40,-6,6,0,3,-12,-4,38,58,-7,7,0,3,4,12,38,58,-7,7,0,3,-13,13,54,68,-9,9,1,1,-38,-20,10,118,-10,-4,1,3,15,21,74,86,-6,2,0,3,-15,15,64,100,-10,10,1,2,-38,-20,74,84,-12,-10,0,2,-6,6,70,96,-12,-10,0,2,14,20,78,116,2,12,0,2,-15,-9,92,102,-7,7,0,1,9,15,92,102,-7,7,0,1,-10,10,96,120,-9,9,0,1,-10,10,102,110,-11,-9,0,0,-8,8,103,109,-12,-11,0,3,-34,-24,114,128,-10,-4,0,1};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-9,-3,0,42,-6,6,0,3,3,9,0,42,-6,6,0,3,-26,-20,4,72,-6,2,0,3,-11,11,38,58,-7,7,1,2,-13,13,24,84,4,10,1,1,11,17,56,92,2,10,0,1,-12,12,64,72,-9,-7,0,3,6,12,62,84,-6,4,0,3,-20,-6,68,76,-6,0,0,3,-4,4,72,98,-6,6,0,3,-12,12,86,94,-9,-7,0,3,12,16,90,112,4,12,0,3,-26,-20,68,124,-6,2,0,3,-11,11,96,102,-9,7,1,3,-6,6,92,100,-12,-6,0,1,-9,9,98,120,-12,2,0,3,-9,9,102,108,-14,-12,0,0,-6,6,116,128,-8,4,0,3};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-9,9,0,10,-5,5,0,2,-4,4,8,34,-3,3,0,1,-20,-4,30,42,-9,-7,0,0,4,20,30,42,-9,-7,0,0,-20,20,40,68,-6,6,1,2,-4,4,42,68,-8,-6,0,1,-14,14,66,94,-6,6,1,3,-4,4,68,94,-8,-6,0,1,-11,11,78,84,-9,-7,0,3,-10,10,92,98,-8,-6,0,1,-10,10,96,118,-6,6,1,1,-9,9,102,112,-8,-6,0,0,-8,-3,104,110,-10,-8,0,2,3,8,104,110,-10,-8,0,2,-5,5,116,128,-4,4,1,1};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-11,-4,0,26,-6,6,0,2,4,11,0,26,-6,6,0,2,-13,13,18,24,-9,-7,0,1,-30,-18,30,36,-8,8,0,1,18,30,30,36,-8,8,0,1,-13,13,22,64,-7,7,1,2,-28,-18,34,62,-6,6,0,3,18,28,34,62,-6,6,0,3,-11,11,50,56,-10,-8,0,3,-27,-21,60,86,-5,1,0,1,21,27,60,86,-5,1,0,1,-11,11,60,90,-6,6,1,3,-10,10,78,84,-9,-7,0,3,-27,27,84,92,-4,4,0,2,-9,9,88,94,-8,-6,0,1,-10,10,92,116,-6,6,0,2,-9,9,100,112,-8,-6,0,0,-8,-3,103,109,-10,-8,0,3,3,8,103,109,-10,-8,0,3,-6,6,114,128,-4,4,0,2};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-16,16,0,40,-7,7,0,3,-6,6,4,40,-9,-7,1,3,-26,-18,30,38,-6,-2,0,1,-22,-16,36,46,-6,0,0,3,-18,-12,44,62,-5,3,0,3,-13,13,38,76,-7,7,0,3,-30,-20,52,66,-8,0,0,1,-5,5,40,76,-9,-7,1,2,-28,-22,55,63,-10,-8,0,2,-10,10,74,102,-6,6,0,3,-10,10,84,90,-8,-6,1,2,-4,4,76,100,-8,-6,1,3,-7,7,92,104,-8,-6,0,0,-7,-3,95,101,-10,-8,0,2,3,7,95,101,-10,-8,0,2,-6,6,100,128,-5,5,0,3};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-13,-4,0,8,-8,8,0,1,4,13,0,8,-8,8,0,1,-12,-5,6,58,-6,6,0,3,5,12,6,58,-6,6,0,3,-18,18,4,78,4,10,1,1,-14,14,54,70,-9,9,1,2,16,22,6,128,4,10,0,3,-20,-14,30,92,-8,-2,0,1,22,28,70,80,8,18,1,1,-13,13,64,70,-11,-9,0,2,-15,15,68,100,-10,10,1,3,22,30,92,102,8,18,1,2,-7,7,74,96,-12,-10,0,1,-17,-9,88,98,-7,7,0,1,9,17,88,98,-7,7,0,1,-24,-16,88,112,-8,-2,0,2,-11,11,96,122,-7,7,0,3,22,32,114,124,8,18,1,3,-10,10,104,111,-9,-7,0,0,-10,10,120,126,-4,4,0,2,-4,2,120,128,-4,4,0,2,6,12,122,128,-3,3,0,2};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-22,-14,0,38,-6,6,0,3,14,22,0,38,-6,6,0,3,-32,-24,12,20,-14,-8,0,2,-28,-22,18,34,-12,-6,0,1,-16,16,10,64,4,10,0,1,-13,13,36,54,-8,4,1,2,-22,-14,38,54,-6,2,0,3,-8,8,54,70,-11,-9,0,1,-12,12,52,88,-9,7,1,3,-9,9,63,69,-13,-11,0,3,14,22,66,82,-6,2,0,3,-8,8,68,88,-11,-9,0,1,-9,9,80,86,-13,-11,0,3,14,24,94,108,6,14,0,1,-10,10,88,94,-10,-8,1,3,20,28,84,100,-12,-6,0,1,-9,9,92,128,-6,8,0,1,22,30,98,110,-18,-12,0,2,-9,9,104,118,-8,-6,0,0,-8,-3,108,114,-10,-8,0,3,3,8,108,114,-10,-8,0,3};
inline constexpr short grandleon_playstation_mesh_beast[160] = {-15,-8,0,46,-13,-5,0,2,8,15,0,46,-13,-5,0,2,-26,-18,46,56,-6,2,0,2,-22,-12,42,68,-9,5,0,2,-11,-6,38,62,-13,-10,0,3,-1,4,38,62,-13,-10,0,3,9,14,38,62,-13,-10,0,3,19,24,38,62,-13,-10,0,3,20,30,44,70,-9,5,0,2,-29,-24,52,64,-6,2,1,2,-16,26,60,70,-8,2,0,3,-10,-2,68,78,-6,0,1,3,4,12,68,78,-6,0,1,3,22,30,66,98,-6,2,0,3,21,29,76,84,-10,-4,1,3,25,35,88,98,-14,-6,0,2,26,35,91,95,-16,-14,0,0,18,32,92,114,-8,2,0,3,20,25,98,104,-10,-8,0,1,18,26,106,128,0,10,0,2};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {20,18,15,20,16,22,21,20};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {28,22,20,31,22,27,28,31};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,30,32,28,29,32,27,24};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {563,436,397,546,423,579,409,408};
