// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[168] = {-14,-5,0,8,-8,8,0,0,5,14,0,8,-8,8,0,0,-13,-6,8,42,-6,6,0,1,6,13,8,42,-6,6,0,1,-23,-15,16,44,-10,-4,1,2,-13,-5,40,62,-7,7,0,1,5,13,40,62,-7,7,0,1,-27,-11,42,70,-10,-4,1,3,-14,14,58,72,-9,9,1,1,22,28,66,100,4,10,0,3,-29,-9,66,92,-10,-4,1,3,-12,12,70,102,-10,10,1,1,-5,5,70,102,-12,-10,0,1,24,30,96,116,6,14,0,3,-19,-9,96,108,-6,10,0,2,9,19,96,108,-6,10,0,2,-8,8,100,106,-8,8,0,0,-10,10,104,124,-9,9,0,1,-10,10,108,113,-11,-9,0,0,-3,3,116,128,2,16,0,3,-7,7,113,117,-12,-10,0,3};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-13,-4,0,8,-8,8,0,0,4,13,0,8,-8,8,0,0,-12,-5,8,40,-6,6,0,1,5,12,8,40,-6,6,0,1,-12,-4,38,60,-7,7,0,1,4,12,38,60,-7,7,0,1,-13,13,56,68,-9,9,1,1,10,18,60,96,6,14,0,2,-15,-11,66,86,-6,6,1,1,11,15,66,86,-6,6,1,1,-11,11,66,98,-8,8,1,3,22,32,70,80,-20,-14,0,3,-11,11,74,80,-18,-16,0,1,-5,5,66,98,-10,-8,0,1,-30,30,78,84,-16,-10,0,3,12,16,92,108,8,16,0,3,-6,6,94,108,-10,2,0,2,-12,12,104,126,-6,10,1,2,-2,10,114,128,4,14,1,1,-9,9,110,116,-8,-6,0,0};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-14,14,0,20,-8,8,1,1,-12,12,18,44,-7,7,1,2,-4,4,4,64,-10,-8,0,2,-17,-12,34,44,-8,-2,0,1,12,17,34,44,-8,-2,0,1,-14,-8,40,58,-5,5,1,2,8,14,40,58,-5,5,1,2,-10,10,42,64,-6,6,1,2,-9,9,58,66,-7,7,1,3,-8,8,60,86,-8,4,0,1,-6,6,72,78,-10,-8,0,3,-8,8,84,92,6,11,0,3,-17,-7,87,97,6,11,0,2,7,17,87,97,6,11,0,2,-19,-13,95,117,6,11,0,3,13,19,95,117,6,11,0,3,-17,-7,115,125,6,11,0,2,7,17,115,125,6,11,0,2,-8,8,121,128,6,11,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[168] = {-15,15,0,20,-9,9,1,1,-13,13,18,52,-8,8,1,2,-4,4,6,84,-10,-8,0,1,-30,-16,46,76,2,10,1,0,16,30,46,76,2,10,1,0,-15,-11,50,76,-6,6,1,2,11,15,50,76,-6,6,1,2,-11,11,50,84,-8,8,1,3,-30,-16,72,86,-4,8,0,1,16,30,72,86,-4,8,0,1,-30,-20,82,92,-6,2,0,1,20,30,82,92,-6,2,0,1,-32,-20,88,98,-8,2,0,1,20,32,88,98,-8,2,0,1,-31,-23,98,106,2,8,0,3,23,31,98,106,2,8,0,3,-30,-25,92,96,-10,-8,0,3,25,30,92,96,-10,-8,0,3,-8,8,92,112,-7,7,0,2,-10,10,102,120,-4,10,0,1,-9,9,118,128,-6,6,0,3};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-16,16,0,20,-8,8,0,3,-6,6,4,58,-10,-8,1,3,-22,22,18,56,-8,8,0,3,-22,-16,42,52,-8,-2,0,1,-20,-15,50,76,-6,6,0,3,-15,15,54,84,-8,8,0,3,15,20,62,92,-6,6,0,3,-6,6,54,90,-10,-8,1,3,-7,7,90,95,-8,-6,0,0,-8,8,88,108,-6,6,0,1,-11,11,96,118,-4,10,0,3,16,26,98,116,-8,4,0,2,-10,10,106,112,-8,-4,1,3,19,23,106,112,-10,-8,0,2,-8,8,116,128,0,10,0,3,18,26,114,124,-6,2,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-12,-5,0,40,-6,6,0,1,5,12,0,40,-6,6,0,1,-17,17,6,84,4,10,1,1,-12,-4,38,60,-7,7,0,1,4,12,38,60,-7,7,0,1,16,32,38,76,2,8,1,1,-13,13,56,70,-9,9,1,2,-21,-15,44,96,-8,-2,0,3,-17,-12,70,94,-6,6,0,1,12,17,70,94,-6,6,0,1,18,34,72,106,4,10,1,2,-12,12,68,102,-10,10,0,1,-9,9,80,86,-12,-10,0,3,-20,-10,96,106,-8,6,0,1,10,20,96,106,-8,6,0,1,-23,-13,92,116,-6,2,0,3,20,32,102,128,6,12,1,3,-16,-7,110,120,2,8,0,3,7,16,110,120,2,8,0,3,-10,10,104,122,-9,9,0,1,-10,10,108,113,-11,-9,0,0,-7,7,113,117,-12,-10,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-22,-13,0,34,-8,4,0,1,13,22,0,34,-8,4,0,1,-16,16,6,56,4,12,0,1,-28,-19,22,30,-18,-12,0,3,-21,-14,30,42,-16,-10,0,3,-20,-11,32,54,-8,4,0,1,11,20,32,54,-8,4,0,1,-13,13,30,56,-12,-4,1,2,-15,15,52,60,-12,-4,0,3,-18,-13,58,78,-10,0,0,1,-13,13,56,86,-10,8,0,1,13,18,62,84,-10,0,0,1,-12,12,58,84,-14,-8,1,3,-11,11,84,92,-12,4,1,2,14,24,84,94,-18,-12,0,3,-9,9,90,110,-8,6,0,2,-17,-10,104,112,2,10,0,3,-21,-13,108,116,4,12,0,3,20,30,92,104,-20,-14,0,3,-11,11,100,122,-4,10,0,1,-24,-16,112,120,6,14,0,3,-7,7,106,111,-8,-6,0,3,-8,8,116,128,0,10,0,1};
inline constexpr short grandleon_playstation_mesh_beast[184] = {-21,-13,0,42,6,16,0,0,3,11,0,42,6,16,0,0,-16,-8,0,42,-16,-6,0,1,8,16,0,42,-16,-6,0,1,-32,-24,22,36,-6,2,0,3,-30,-18,30,46,-8,2,0,1,-22,-10,40,58,-10,4,0,1,-20,18,38,78,-16,10,0,1,12,22,60,84,-8,2,0,1,-22,-6,70,86,-2,6,1,2,6,22,70,86,-2,6,1,2,10,16,64,82,-12,-8,1,3,-14,-6,74,82,-10,-4,1,3,0,8,74,82,-10,-4,1,3,-32,-18,82,104,0,8,1,3,18,32,82,104,0,8,1,3,18,28,80,100,-8,2,0,1,26,32,90,95,-20,-18,0,3,19,32,92,110,-14,0,0,1,25,32,94,104,-18,-10,0,1,17,25,108,122,0,8,0,3,21,26,102,107,-16,-14,0,3,25,33,108,128,0,8,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {21,20,19,21,16,22,23,23};
inline constexpr int grandleon_playstation_mesh_max_parts = 23;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {29,30,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {490,446,377,496,427,650,434,597};
