// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[152] = {-22,-2,0,5,-5,5,0,1,2,22,0,5,-5,5,0,1,-15,-7,5,26,-4,4,0,1,7,15,5,26,-4,4,0,1,-18,18,25,39,-6,6,1,1,25,30,1,74,0,4,0,1,-16,16,43,47,-8,-6,0,0,-16,16,38,62,-6,6,1,2,7,33,48,55,-3,3,0,1,-34,-6,53,57,-5,5,1,3,6,34,53,57,-5,5,1,3,-28,-12,53,68,-5,5,0,1,12,28,53,68,-5,5,0,1,-9,9,68,74,-3,5,0,0,-8,8,64,74,-8,-1,0,3,-8,8,68,71,-8,-7,0,0,23,33,74,83,0,4,0,3,-8,8,73,83,-5,5,0,0,-3,3,77,83,-6,-5,1,3};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-12,-4,0,6,-5,5,0,1,4,12,0,6,-5,5,0,1,-11,-4,6,31,-4,4,1,1,4,11,6,31,-4,4,1,1,18,22,15,44,1,6,0,1,-11,11,29,42,-6,6,1,1,11,18,42,48,-4,4,1,1,-18,-12,42,65,4,9,0,1,-15,-11,44,60,-4,4,1,1,-12,12,41,67,-6,6,1,2,-11,11,51,55,-8,-6,0,0,-18,-12,65,74,6,10,0,3,20,25,44,93,1,6,0,1,-11,11,65,79,-8,-1,0,2,-7,7,71,75,-10,-8,0,0,-9,9,76,79,-9,-1,1,3,-8,8,79,89,-4,4,0,0,-3,3,87,92,-1,3,0,0};
inline constexpr short grandleon_playstation_mesh_mage[120] = {-13,13,0,5,-7,7,0,0,-9,9,0,42,-6,6,1,1,-3,3,5,41,-8,-6,1,3,-17,-10,41,60,-5,5,1,1,10,17,41,60,-5,5,1,1,-8,8,44,50,-8,-5,0,2,-10,10,41,69,-5,5,1,2,-3,3,47,63,-9,-7,0,3,-10,10,66,69,-8,-5,0,0,-9,9,69,81,-8,-1,0,2,-22,-16,72,84,-2,3,0,3,-6,6,75,78,-10,-8,0,0,18,24,75,90,-2,3,0,3,-7,7,78,81,-6,-5,0,3,-5,5,80,96,-3,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[120] = {-14,14,0,16,-6,6,1,1,-16,16,15,38,-5,5,1,2,-20,-14,34,38,-5,-1,0,2,25,29,5,75,-1,3,0,1,-14,14,41,45,-8,-5,1,3,-28,-14,37,57,-4,4,0,3,-9,9,37,64,-5,5,0,3,10,24,48,61,-4,3,0,3,21,29,59,64,-2,3,0,2,-11,11,66,77,-8,-1,0,2,-12,12,72,75,-8,-3,1,3,16,38,74,81,-4,4,0,0,-7,7,70,73,-12,-10,0,0,-11,11,75,86,-4,4,0,0,19,35,79,87,-3,3,1,3};
inline constexpr short grandleon_playstation_mesh_healer[120] = {-12,-4,0,4,-5,5,0,2,4,12,0,4,-5,5,0,2,-13,13,3,8,-6,6,0,1,-13,13,3,38,-6,6,0,3,16,21,8,77,-1,3,0,1,13,20,42,48,-2,2,0,2,-19,-13,39,57,-4,4,0,3,-13,13,36,64,-6,6,0,3,-4,18,39,53,-10,-8,1,2,-17,5,52,64,-8,-6,1,2,-11,11,59,62,-8,-7,0,0,-11,11,64,81,-8,0,0,2,-10,10,71,73,-9,-8,0,0,9,29,75,87,-1,3,0,3,17,21,85,89,-1,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[160] = {-19,3,0,5,-5,5,0,1,-3,19,0,5,-5,5,0,1,-11,-4,5,25,-4,4,0,1,4,11,5,25,-4,4,0,1,-14,14,24,38,-5,5,1,1,-27,-5,29,33,-7,-5,0,3,-14,14,20,60,5,8,1,2,-14,14,37,63,-5,5,0,1,-19,-12,54,65,-5,5,0,1,12,19,54,65,-5,5,0,1,-12,-7,46,84,8,11,0,1,-10,10,55,59,-7,-5,1,3,-11,11,61,69,-3,6,0,0,-12,10,63,82,8,11,1,2,-10,8,69,75,7,8,0,3,-9,9,63,73,-7,-1,0,2,-7,7,65,67,-9,-7,0,3,-11,11,71,82,-5,5,0,0,-16,-11,76,84,-2,1,0,3,11,16,76,84,-2,1,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {-25,-3,0,22,-4,3,0,1,3,25,0,22,-4,3,0,1,-16,-8,20,34,-4,3,0,1,8,16,20,34,-4,3,0,1,-11,11,32,38,-6,4,0,0,-8,8,33,37,-8,-6,1,3,-19,-12,37,52,-5,0,0,1,12,19,37,52,-5,0,0,1,-9,9,37,57,-6,3,0,1,-11,11,46,61,3,7,0,2,-9,9,40,54,-8,-6,0,0,-22,-15,48,54,-6,-2,0,2,15,22,48,54,-6,-2,0,2,-10,10,56,61,-7,2,0,0,-33,-28,54,69,-5,-2,0,3,16,21,54,69,-5,-2,0,3,-11,11,60,75,-4,4,0,1,-10,10,63,68,-8,-4,0,2,-7,7,66,70,-9,-7,0,3,-6,6,73,82,-3,4,0,1};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-12,-7,0,23,2,7,0,0,7,13,0,23,2,7,0,0,5,10,0,23,-8,-3,0,1,-15,-10,0,23,-8,-3,0,1,-17,14,20,40,-8,5,0,1,-27,-3,22,39,-7,4,0,2,4,27,29,43,-1,4,0,1,-34,-11,32,37,-5,-1,0,3,-26,-23,33,36,-7,-3,0,0,-24,0,34,40,-8,4,1,3,-13,11,37,42,-8,4,1,2,-28,-5,33,46,-6,1,0,2,-24,-8,38,41,-9,-8,0,0,-16,-12,44,54,-2,2,0,1,-21,-17,44,54,-2,2,0,1,16,22,41,60,-1,4,0,2,-28,0,47,51,-4,1,0,1,17,22,57,75,0,5,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {19,18,15,15,15,20,20,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 20;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {32,21,19,31,23,22,25,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,490,393,524,489,518,369,476};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,28,28,26,26,28,24,24};
