// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-12,-5,0,6,-5,5,0,0,5,12,0,6,-5,5,0,0,-11,-5,4,29,-4,4,0,1,5,11,4,29,-4,4,0,1,-15,15,27,40,-6,6,1,1,-13,13,39,44,-6,6,0,0,-17,-11,44,63,-4,4,0,2,11,17,44,63,-4,4,0,2,-13,13,49,52,-7,-6,1,0,-13,13,43,66,-5,5,1,2,-13,13,56,59,-7,-6,1,0,15,21,60,67,-4,0,0,1,-3,5,63,76,4,8,0,0,-17,-10,59,77,-4,4,0,0,-13,13,66,80,-4,4,0,2,-12,12,71,75,-6,-5,0,0,21,27,66,86,-4,1,0,3,-12,12,79,92,-5,2,1,2};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-12,-5,0,7,-5,5,0,0,5,12,0,7,-5,5,0,0,-11,-5,5,28,-4,4,0,2,5,11,5,28,-4,4,0,2,-9,9,26,38,-5,5,1,1,-9,9,37,42,-5,5,0,0,-19,-12,43,55,-3,3,0,2,12,19,43,55,-3,3,0,2,-15,15,41,62,-5,5,0,1,-29,1,45,53,-7,-3,0,1,-4,30,47,51,-9,-6,0,3,-4,4,42,60,-7,-6,1,2,1,7,43,60,-8,-7,0,0,2,6,50,53,-9,-7,0,3,-9,-1,51,55,-9,-6,0,0,-14,-8,55,75,-3,4,0,0,8,14,55,75,-3,4,0,0,-7,7,60,74,-4,4,0,2,-7,7,66,70,-6,-5,0,0,-7,7,74,84,-5,5,0,0};
inline constexpr short grandleon_playstation_mesh_mage[136] = {3,8,0,4,-4,3,0,1,-10,-3,0,5,-5,3,0,0,3,7,3,30,-3,3,0,1,-9,-3,4,30,-4,3,0,1,2,8,27,33,-7,-5,0,0,-12,12,27,44,-5,5,1,1,-10,10,42,48,-5,5,0,0,9,14,38,56,-3,3,0,2,-9,9,46,66,-4,4,1,2,-15,-9,49,70,-3,3,0,2,4,10,51,75,4,8,0,0,-9,9,60,74,-4,4,0,2,-9,9,65,69,-6,-5,0,0,-13,-10,70,78,-3,-1,0,1,-10,10,71,74,-6,-5,1,3,-9,9,72,87,-4,5,0,0,-19,-5,75,83,-5,-1,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[168] = {5,12,0,6,-5,5,0,0,-12,-5,0,6,-5,5,0,0,5,11,5,31,-5,5,0,1,-11,-5,5,31,-5,5,0,1,-13,13,29,43,-6,6,0,1,17,22,0,79,-2,2,0,1,-11,11,41,47,-6,6,0,0,-16,-10,46,64,-4,4,0,2,-11,11,46,70,-5,5,1,2,11,17,47,69,-4,4,0,2,-12,12,53,57,-7,-5,1,0,-4,4,69,81,5,8,0,0,-14,-8,63,85,-4,5,0,0,-11,11,69,84,-5,5,0,2,-11,11,75,79,-7,-5,0,0,9,31,78,85,-5,5,0,0,10,30,79,82,-6,-5,0,3,15,25,84,92,-3,3,0,3,-7,7,82,96,-5,4,0,1,-5,5,85,89,-7,-5,0,3,16,23,90,98,-2,2,1,3};
inline constexpr short grandleon_playstation_mesh_healer[120] = {-16,16,0,16,-5,5,1,1,1,7,20,24,-7,-5,0,1,-14,14,14,39,-5,5,0,3,3,23,30,39,-7,-1,1,1,-12,12,37,41,-6,6,0,0,10,16,41,60,-3,3,0,2,-10,10,39,63,-5,5,0,3,-8,-2,48,52,-7,-5,0,1,-16,-10,44,63,-3,3,0,2,0,6,42,63,-7,-5,1,1,-14,-7,58,76,-3,4,0,1,-12,12,63,76,-4,4,0,2,5,12,69,79,3,7,0,3,-12,12,68,71,-6,-5,0,0,-12,12,75,87,-5,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-12,-4,0,7,-5,5,0,0,4,12,0,7,-5,5,0,0,-10,-4,6,26,-4,4,0,1,4,10,6,26,-4,4,0,1,-13,13,6,68,6,9,1,1,-13,13,24,45,-6,6,1,1,20,25,3,83,3,6,0,1,-11,11,42,47,-6,6,0,0,-3,3,42,46,-7,-6,0,3,-17,-11,45,65,-4,4,1,2,11,17,45,65,-4,4,1,2,-11,11,46,70,-5,5,1,2,-3,3,47,69,-7,-6,0,3,-17,-11,60,65,-5,-1,0,3,11,17,60,65,-5,-1,0,3,3,10,63,78,4,7,0,1,-11,11,66,70,-6,-5,0,0,19,41,68,82,2,11,1,3,-13,13,65,79,-4,4,0,2,27,32,72,78,1,2,0,0,-12,12,70,75,-6,-5,0,0,-12,12,78,81,-6,-5,0,0,-11,11,78,88,-4,4,0,3,-2,2,85,92,-4,6,1,2,-7,7,88,91,-4,6,1,2};
inline constexpr short grandleon_playstation_mesh_rogue[160] = {-23,-5,0,5,-4,4,0,0,5,23,0,5,-4,4,0,0,-17,-9,4,25,-4,3,0,1,9,17,4,25,-4,3,0,1,-11,11,24,33,-5,5,1,2,11,17,31,47,-3,3,0,2,-9,9,36,39,-5,-4,1,1,-9,9,31,51,-4,4,0,3,-11,11,34,59,4,7,1,1,-9,9,42,45,-5,-4,1,1,-18,-12,39,56,-3,3,0,2,26,32,45,51,-4,0,0,1,-8,0,52,63,3,5,0,0,26,31,50,63,-3,0,0,3,-12,12,52,64,-4,4,0,2,-21,-15,54,60,-4,0,0,1,-12,12,56,60,-5,-4,0,0,-19,-14,59,73,-3,0,0,3,-11,11,63,75,-4,4,1,1,-4,4,74,77,-2,4,1,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {2,9,0,5,-6,2,0,2,-9,-3,0,5,-6,2,0,2,-24,-8,3,9,-1,4,1,1,3,7,3,19,-3,2,0,2,-7,-3,3,19,-3,2,0,2,-20,-5,8,18,-1,4,1,2,-15,0,16,28,-1,4,1,2,-5,8,26,46,5,7,1,1,-6,10,18,49,-5,7,1,2,-5,8,25,45,-7,-5,1,1,-4,7,33,37,-9,-7,0,3,3,15,46,59,-4,4,1,3,4,17,58,67,-5,6,1,3,14,24,59,64,-4,0,0,1,6,10,62,64,-5,-4,0,0,10,16,67,71,1,5,0,3,11,15,66,74,1,5,0,3,2,6,66,76,-2,3,0,3,6,10,67,84,-1,3,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,20,17,21,15,25,20,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {24,26,18,25,21,25,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {464,402,397,484,434,563,417,339};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,25,26,28,25,28,23,25};
