// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'medieval' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 0;
inline constexpr const char* grandleon_playstation_mesh_style_name = "medieval";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[192] = {-12,-4,0,4,-5,4,0,0,4,12,0,4,-5,4,0,0,-11,-5,4,25,-4,4,0,2,5,11,4,25,-4,4,0,2,-11,-4,25,40,-4,4,0,1,4,11,25,40,-4,4,0,1,-14,14,37,46,-6,6,1,1,-12,12,46,52,-6,6,0,0,13,21,45,49,-7,-4,0,1,-16,-10,51,69,-4,4,0,1,10,16,51,69,-4,4,0,1,-4,4,46,70,-6,-4,1,3,-25,-7,43,69,-10,-7,1,2,-10,10,52,70,-6,2,0,2,-3,3,66,81,4,9,0,0,-17,-9,67,75,-5,5,1,2,9,17,67,75,-5,5,1,2,-4,4,69,74,-4,4,0,0,15,19,48,96,-7,-4,0,3,-9,9,73,82,-4,4,0,2,-8,8,79,87,-5,5,0,3,-9,9,87,90,-1,6,1,3,-2,2,86,93,-1,6,1,3,-5,5,83,85,-9,-7,0,0};
inline constexpr short grandleon_playstation_mesh_archer[168] = {-11,-4,0,4,-5,3,0,0,4,11,0,4,-5,3,0,0,-10,-5,4,23,-3,3,0,1,5,10,4,23,-3,3,0,1,-10,-4,23,36,-3,3,0,0,4,10,23,36,-3,3,0,0,-20,-16,16,53,-5,-3,0,3,-13,13,33,44,-5,5,1,1,-12,12,42,46,-5,5,0,0,9,15,48,63,-3,3,0,2,-11,11,46,66,-3,3,1,2,-16,-9,48,65,-3,3,0,2,6,13,51,70,4,9,0,1,-21,-14,51,60,-6,-2,0,0,-3,3,57,71,3,8,0,0,-9,9,67,75,-3,3,0,2,-20,-16,57,88,-5,-3,0,3,-9,9,71,79,-4,4,1,2,-2,2,77,83,1,5,1,2,-8,8,79,83,1,5,1,2,-6,6,75,77,-7,-5,0,0};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-16,16,0,5,-7,7,0,0,-14,14,4,30,-6,6,1,1,-3,3,4,30,-8,-6,1,3,15,20,8,50,-6,-3,0,1,-14,14,29,55,-5,5,1,2,-3,3,29,55,-6,-5,1,3,11,16,44,50,-7,-2,0,2,-3,3,46,61,5,8,0,0,-14,-10,47,61,-4,4,1,1,10,14,47,61,-4,4,1,1,-13,13,58,70,2,6,0,0,-12,12,59,70,-5,5,0,2,15,20,50,79,-6,-3,0,1,-8,8,64,67,-8,-5,0,0,-14,14,69,73,-6,2,1,2,-12,12,72,84,-4,2,1,3,7,29,78,85,-7,-2,0,3,-12,12,85,93,-3,2,1,3,-3,3,82,97,-3,2,1,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[160] = {-14,14,0,15,-6,6,1,1,-19,19,4,46,5,9,1,0,-19,19,14,38,-4,4,1,2,-22,-17,6,66,-6,-2,0,1,-12,12,36,41,-5,5,0,0,-12,12,39,59,-3,3,1,3,9,15,42,59,-3,3,1,2,-2,3,48,63,4,8,0,0,-19,-13,48,55,-6,-1,0,2,-16,-9,45,63,-4,3,1,2,-10,10,59,69,-3,4,0,1,-10,10,68,72,-3,5,1,3,-35,-5,63,71,-8,-1,0,1,11,31,71,85,4,10,0,2,-37,-5,70,74,-9,-1,0,0,-10,-5,72,80,-1,4,0,3,5,10,72,80,-1,4,0,3,-9,-3,74,81,-6,-3,0,3,-37,-31,74,82,-6,-3,0,3,-24,-16,74,90,-6,-3,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-16,16,0,5,-7,7,0,0,-15,15,4,32,-6,6,0,3,-3,3,4,60,-8,-5,1,1,-13,13,39,44,-5,5,0,0,-13,13,30,59,-5,5,0,3,15,19,11,78,-5,-2,0,1,-13,-9,42,62,-4,4,0,3,9,13,42,62,-4,4,0,3,10,16,47,54,-6,-1,0,2,-14,14,59,67,5,8,0,3,-3,3,60,75,5,8,0,3,-11,11,66,77,2,6,0,1,-10,10,68,78,-4,4,0,2,-12,12,75,87,-3,5,0,3,-8,8,80,83,-6,-4,0,0,5,29,83,88,-5,-2,0,3,14,19,78,96,-5,-2,0,3};
inline constexpr short grandleon_playstation_mesh_commander[184] = {-11,-4,0,4,-6,4,0,0,4,11,0,4,-6,4,0,0,-10,-5,4,23,-4,4,0,2,5,10,4,23,-4,4,0,2,-10,-4,23,35,-4,4,0,1,4,10,23,35,-4,4,0,1,-13,13,4,63,5,10,1,1,-13,13,32,42,-5,5,1,1,-12,12,41,45,-6,6,0,0,19,24,10,86,3,7,0,1,-17,-11,46,63,-4,4,0,2,12,19,46,63,-4,4,0,2,-12,12,45,65,-4,4,1,3,-3,3,55,70,4,8,0,0,-18,-10,62,70,-5,5,1,2,10,18,62,70,-5,5,1,2,-4,4,66,70,-4,4,0,0,19,39,66,84,1,8,1,3,-10,10,70,78,-4,4,0,1,-7,7,73,75,-6,-4,0,3,-10,10,76,82,-5,5,0,3,15,29,84,90,3,7,0,3,-2,2,81,90,-5,4,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[184] = {-27,-9,0,4,-5,4,0,0,9,27,0,4,-5,4,0,0,-21,-14,4,17,-3,3,0,0,14,21,4,17,-3,3,0,0,-24,-4,17,30,-4,4,0,1,4,24,17,30,-4,4,0,1,-12,12,27,33,-4,4,1,1,-11,11,32,36,-5,5,0,0,-12,12,33,59,4,7,1,0,-11,11,35,54,-3,3,1,2,-16,-10,37,53,-3,3,0,1,10,16,37,53,-3,3,0,1,-3,3,45,59,5,8,0,1,-29,-11,50,53,-5,-2,0,2,11,29,50,53,-5,-2,0,2,-10,10,53,57,-3,-1,1,3,-10,10,56,63,-3,3,0,2,-22,-17,51,67,-5,-2,0,3,17,22,51,67,-5,-2,0,3,-11,11,60,70,-3,4,0,0,-7,7,65,67,-6,-4,0,3,-10,10,69,73,1,4,0,0,-2,2,68,76,1,4,0,0};
inline constexpr short grandleon_playstation_mesh_beast[144] = {8,14,0,23,3,8,0,0,-18,-11,0,23,3,8,0,0,8,14,0,23,-8,-4,0,1,-18,-11,0,23,-8,-4,0,1,20,24,22,28,0,3,1,3,18,23,26,34,-1,3,0,2,-2,23,22,40,-8,7,0,2,-15,15,21,44,-8,7,0,1,-5,1,21,45,-9,8,1,2,14,20,32,37,-1,3,0,1,-26,-2,29,49,-8,7,1,1,-36,-12,39,48,-5,0,0,1,-33,-9,41,56,-7,1,0,2,-28,-25,47,51,-5,-2,0,3,-29,-13,47,51,-10,-8,0,0,-24,-19,53,60,1,4,0,0,-36,-7,57,60,1,4,0,0,-21,-17,56,70,-3,0,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {24,21,19,20,17,23,23,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {22,21,20,32,20,27,27,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,32,31,32,27,25};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {473,470,500,564,473,585,428,483};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {28,25,28,28,27,28,23,21};
