// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'pirates' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 6;
inline constexpr const char* grandleon_playstation_mesh_style_name = "pirates";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[144] = {-14,-6,0,9,-7,7,0,0,6,14,0,9,-7,7,0,0,-13,-6,7,42,-6,6,0,1,6,13,7,42,-6,6,0,1,-14,14,40,50,-8,8,1,1,-13,13,58,63,-11,-9,1,0,-13,13,48,90,-8,8,1,2,13,20,60,86,-6,6,0,2,-3,3,50,90,-11,-9,0,0,-20,-13,64,92,-6,6,0,2,-13,13,70,75,-11,-9,1,0,-24,-18,82,92,-6,0,0,1,-11,11,90,110,-7,7,0,2,8,16,100,112,5,11,1,1,8,11,96,100,-8,-5,0,3,-11,11,97,103,-10,-8,0,0,-27,-21,90,122,-5,1,0,3,-11,11,106,128,-7,3,1,2};
inline constexpr short grandleon_playstation_mesh_archer[144] = {-12,-5,0,12,-8,8,0,0,5,12,0,12,-8,8,0,0,-10,-4,10,40,-7,7,0,2,4,10,10,40,-7,7,0,2,-9,9,36,66,-9,9,0,1,-19,-12,68,80,-6,6,0,1,12,18,66,86,-6,6,0,1,-15,15,64,96,-9,9,0,1,-28,1,70,82,-12,-6,0,1,-5,28,73,79,-13,-9,0,3,1,6,74,80,-14,-12,0,3,0,7,64,94,-13,-11,1,1,-12,12,66,94,-14,-12,1,2,-9,-2,80,86,-14,-10,0,0,-4,3,92,108,6,11,0,1,-7,7,90,110,-7,7,0,2,-6,6,98,104,-10,-8,0,0,-7,7,106,128,-7,6,0,1};
inline constexpr short grandleon_playstation_mesh_mage[136] = {-8,-3,0,6,-6,4,0,1,3,11,0,10,-7,6,0,0,-7,-3,4,46,-5,4,0,1,4,10,8,46,-6,5,0,1,-3,3,42,50,-10,-8,0,0,-12,12,42,66,-8,8,1,1,-11,11,64,72,-9,9,0,0,-16,-10,58,84,-5,5,0,2,-10,10,70,98,-7,7,1,2,10,16,74,104,-5,5,0,2,-16,-8,80,118,-5,6,0,0,-9,9,88,110,-6,6,0,2,-9,9,96,102,-9,-7,0,0,11,14,104,116,-6,-3,0,1,-8,8,106,111,-9,-7,1,3,-9,9,108,128,-6,7,0,0,5,19,112,124,-8,-2,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-13,-6,0,10,-7,7,0,0,6,13,0,10,-7,7,0,0,-12,-6,8,42,-6,6,0,1,6,12,8,42,-6,6,0,1,-13,13,40,53,-8,8,0,1,18,23,0,106,-3,3,0,1,-12,12,50,58,-9,9,0,0,-18,-12,58,84,-5,5,0,2,-12,12,66,71,-10,-8,1,0,-12,12,56,92,-7,7,1,2,12,18,62,90,-5,5,0,2,-11,11,88,110,-7,7,0,2,-11,11,97,102,-10,-8,0,0,10,30,104,114,-6,6,0,0,10,30,106,110,-8,-6,0,3,-6,6,106,124,-7,6,0,1,15,25,112,122,-4,4,0,3,-6,6,110,115,-9,-7,0,3,17,24,120,128,-3,3,1,3};
inline constexpr short grandleon_playstation_mesh_healer[144] = {-12,-4,0,9,-7,7,0,0,4,12,0,9,-7,7,0,0,-11,-4,7,38,-6,6,0,1,4,11,7,38,-6,6,0,1,-14,14,36,60,-8,8,0,3,-8,-2,44,50,-10,-8,0,1,3,23,46,60,-10,-2,1,1,12,18,58,86,-5,5,0,2,3,9,66,72,-10,-8,0,1,-18,-12,60,90,-5,5,0,2,-12,12,58,94,-7,7,0,3,0,6,62,94,-10,-8,1,1,-10,-6,88,96,-9,-7,0,0,6,10,88,96,-9,-7,0,0,-12,12,90,112,-7,7,0,2,6,13,104,114,5,10,0,3,-12,12,99,105,-10,-8,0,0,-12,12,110,128,-7,3,0,3};
inline constexpr short grandleon_playstation_mesh_commander[192] = {-13,-6,0,11,-7,7,0,0,2,9,0,11,-7,7,0,0,-12,-6,9,38,-6,6,0,1,2,8,9,38,-6,6,0,1,-14,11,6,96,8,14,1,1,-14,11,36,66,-8,8,1,1,-24,-19,4,118,4,9,0,1,-13,9,62,70,-9,9,0,0,-5,2,63,68,-11,-9,0,3,-19,-14,64,92,-6,6,1,2,10,15,64,92,-6,6,1,2,-13,9,68,100,-8,8,1,2,-5,2,70,98,-11,-9,0,3,-19,-14,86,92,-8,-2,0,3,10,15,86,92,-8,-2,0,3,-37,-17,96,116,3,15,1,3,-13,9,92,112,-7,7,0,2,-13,9,94,100,-10,-8,0,0,-29,-24,102,110,1,3,0,0,-13,9,100,106,-10,-8,0,0,-12,8,110,124,-7,7,0,3,-13,9,110,115,-10,-8,0,0,-4,1,120,128,-6,10,1,2,-8,5,122,127,-6,10,1,2};
inline constexpr short grandleon_playstation_mesh_rogue[152] = {-26,-8,0,9,-8,6,0,0,8,26,0,9,-8,6,0,0,-24,-8,7,44,-7,5,0,1,8,24,7,44,-7,5,0,1,-11,11,42,52,-8,8,1,2,-11,11,58,63,-10,-8,1,1,-11,11,50,86,-7,7,0,3,-13,13,58,100,7,12,1,1,-18,-12,60,88,-5,5,0,2,-11,11,68,73,-10,-8,1,1,12,18,64,92,-5,5,0,2,-20,-14,86,96,-7,-1,0,1,-12,12,84,104,-6,6,0,2,14,20,90,100,-7,-1,0,1,-12,12,90,97,-9,-7,0,0,-18,-13,94,116,-6,0,0,3,13,18,98,120,-6,0,0,3,-11,11,102,122,-7,6,1,1,-4,4,120,128,-4,8,1,1};
inline constexpr short grandleon_playstation_mesh_beast[152] = {-10,-3,0,7,-9,3,0,2,1,8,0,7,-9,3,0,2,8,23,6,16,-2,6,1,1,-8,-4,5,30,-5,3,0,2,2,6,5,30,-5,3,0,2,2,19,14,30,-2,6,1,2,-2,13,26,44,-2,6,1,2,-12,5,28,76,-8,10,1,2,-10,5,42,72,8,11,1,1,-10,5,40,70,-11,-8,1,1,-10,3,52,58,-13,-11,0,3,-17,-3,72,92,-6,6,1,3,-18,-5,90,104,-7,9,1,3,-25,-15,92,99,-6,0,0,1,-11,-8,96,100,-8,-6,0,0,-18,-12,102,109,1,7,0,3,-17,-13,102,116,1,7,0,3,-7,-3,102,120,-3,4,0,3,-12,-8,104,128,-2,5,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {18,18,17,19,18,24,19,19};
inline constexpr int grandleon_playstation_mesh_max_parts = 24;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {25,28,18,25,21,26,25,24};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,29,30,32,29,32,27,29};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,420,416,503,452,581,434,353};
