// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'scifi' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 1;
inline constexpr const char* grandleon_playstation_mesh_style_name = "scifi";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-18,-2,0,4,-5,5,1,1,2,18,0,4,-5,5,1,1,-13,-6,4,23,-4,4,1,2,6,13,4,23,-4,4,0,1,-13,-5,22,37,-4,4,1,3,5,13,22,37,-4,4,1,1,13,31,6,52,-10,-5,0,0,14,30,27,32,-11,-10,0,3,-23,-17,24,45,-8,-4,1,3,-12,12,36,42,-5,5,0,2,14,18,42,60,-4,4,0,1,-18,-14,43,61,-4,4,0,1,-14,14,41,64,-6,6,0,2,-24,-16,43,61,-8,-3,1,3,-11,11,47,58,-7,-6,0,2,-20,-12,60,67,-6,6,1,2,12,20,60,67,-6,6,0,2,-9,9,62,67,-4,4,0,0,-23,-17,60,70,-8,-4,1,2,-7,7,66,79,-6,6,0,1,-6,6,70,74,-7,-6,0,0,-3,3,76,81,-5,4,0,2};
inline constexpr short grandleon_playstation_mesh_archer[176] = {-12,-4,0,5,-5,5,0,0,4,12,0,5,-5,5,0,1,-11,-5,5,27,-3,3,0,1,5,11,5,27,-3,3,0,0,-11,-4,26,42,-4,4,0,2,4,11,26,42,-4,4,0,0,-10,10,41,47,-5,5,0,1,12,17,46,61,-4,4,0,0,-17,-12,47,62,-4,4,0,0,-9,9,46,66,-5,5,0,3,13,27,50,55,-9,-5,0,1,-3,13,51,57,-10,-6,0,1,-26,-8,53,57,-9,-7,0,3,-34,-28,51,59,-11,-5,0,3,-4,4,54,59,-6,-5,0,2,-16,-10,64,69,-5,5,0,0,-9,9,66,77,-4,4,0,2,-9,9,70,74,-5,-4,0,2,-10,10,76,82,-5,5,1,3,-7,7,78,80,-6,-4,1,2,4,8,78,86,-1,1,0,2,-2,14,81,85,-1,1,1,2};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-10,-3,0,5,-5,5,1,3,3,10,0,5,-5,5,1,2,-13,13,8,52,-6,6,1,2,-2,2,11,49,-8,-6,1,3,12,19,41,50,-6,0,0,2,11,16,49,66,-4,4,0,0,-16,-11,50,69,-4,4,1,2,-6,6,55,75,6,10,0,1,-8,8,50,72,-6,6,1,3,-21,-17,60,64,-3,2,0,3,-24,-14,66,74,-5,3,0,0,-22,-16,68,72,-6,-5,0,3,-6,6,71,77,-5,5,0,3,-5,5,75,88,-5,5,0,2,-5,5,79,84,-6,-5,0,3,-6,6,86,94,-6,6,0,2,-4,4,90,92,-7,-5,0,3,-2,4,93,97,-2,2,0,2,-1,3,93,101,-2,2,0,2};
inline constexpr short grandleon_playstation_mesh_stormcaller[152] = {-9,9,0,18,-6,6,1,2,-9,9,4,51,6,10,0,0,-8,8,16,41,-5,5,1,3,16,20,0,82,-2,2,0,2,-8,8,37,43,-7,-5,0,3,-14,-10,40,59,-4,4,0,1,10,15,41,60,-4,4,0,1,-7,7,40,63,-5,5,1,3,-4,4,46,54,-7,-5,1,3,-30,-22,51,66,-4,4,0,0,-9,9,62,73,-4,4,0,1,-9,9,65,70,-6,-4,0,2,-11,11,71,81,-4,6,0,0,-7,7,75,78,-7,-4,1,1,-4,4,79,88,-1,4,0,1,6,30,79,87,-5,5,0,0,7,29,85,91,-4,4,0,1,7,29,90,93,-2,2,0,0,15,21,90,94,-2,2,0,0};
inline constexpr short grandleon_playstation_mesh_healer[160] = {-10,-3,0,4,-4,4,0,3,3,10,0,4,-4,4,0,1,-9,-3,4,25,-4,4,0,3,3,9,4,25,-4,4,0,3,-9,-2,24,42,-4,4,0,3,2,9,24,42,-4,4,0,2,-11,11,40,46,-4,4,0,3,-17,-13,46,65,-4,4,0,0,-13,13,45,68,-5,5,0,3,13,17,48,67,-4,4,0,2,-3,3,49,62,-7,-5,1,3,-11,11,54,58,-7,-5,0,3,-14,14,67,74,-7,7,0,2,10,18,65,83,3,9,0,2,-11,11,73,85,-4,4,0,2,-11,11,77,81,-5,-4,0,0,-11,11,83,89,-4,4,0,3,-2,2,88,93,-1,1,0,2,-10,10,88,92,-3,0,0,1,-4,4,92,95,-3,3,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-12,-4,0,5,-5,5,0,2,4,12,0,5,-5,5,0,1,-11,-5,5,28,-4,4,1,2,5,11,5,28,-4,4,0,3,-14,14,4,65,5,11,1,2,-11,-4,26,44,-4,4,1,2,4,11,26,44,-4,4,0,1,-24,-20,0,86,-1,4,1,3,-13,13,42,49,-5,5,0,0,-18,-13,51,68,-4,4,0,2,13,18,51,68,-4,4,0,2,-12,12,48,73,-7,7,0,2,-10,10,57,63,-8,-7,0,2,-18,-11,68,77,-6,6,0,2,11,18,68,77,-6,6,1,2,-39,-19,64,84,0,4,0,3,-10,10,73,78,-4,4,0,0,-10,10,76,89,-6,6,0,1,-10,10,79,84,-7,-6,0,1,-25,-19,84,93,-1,4,0,3,-30,-14,87,92,-1,4,0,2,-2,2,87,93,-4,6,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[168] = {-12,-4,0,4,-5,4,0,1,4,12,0,4,-5,4,0,0,-11,-5,4,22,-4,2,0,1,5,11,4,22,-4,2,0,1,-11,-4,21,35,-4,3,0,2,4,11,21,35,-4,3,1,1,-11,11,34,40,-5,4,0,1,-26,-19,36,40,-5,-1,0,0,19,26,38,41,-5,-1,0,0,-11,11,36,63,4,8,0,0,-18,-12,39,52,-4,2,0,1,12,18,40,53,-4,2,0,1,-11,11,39,58,-4,3,0,2,-25,-21,39,56,-5,-1,0,0,21,25,40,57,-5,-1,0,0,-3,3,41,55,-5,-4,1,3,-12,12,57,62,-5,4,0,2,-11,11,61,75,-5,5,0,1,-10,10,65,68,-6,-5,0,0,-7,7,67,70,-8,-7,1,3,-4,4,74,78,-4,2,0,2};
inline constexpr short grandleon_playstation_mesh_beast[144] = {-14,-8,0,30,3,8,0,0,11,18,0,30,3,8,0,0,-14,-8,0,30,-9,-4,0,2,11,18,0,30,-9,-4,0,2,22,29,30,35,-5,0,0,0,-16,19,27,46,-9,6,0,2,-22,-18,32,41,-5,1,0,1,-14,18,31,35,-10,-9,0,2,-22,-19,35,38,-6,-5,0,3,12,38,35,47,-6,1,0,1,22,27,38,43,-7,-6,0,2,16,34,40,43,-11,-9,0,2,-22,6,44,52,-6,4,0,2,-2,25,44,52,-6,4,0,2,-17,18,49,56,-2,0,0,2,-3,3,51,62,-4,1,1,2,-1,2,60,75,-2,0,0,0,-2,4,74,79,-3,1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,22,19,19,20,22,21,18};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {27,28,24,30,21,26,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,29,32,31,31,32,27,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {466,429,430,508,430,555,423,503};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {25,25,28,27,27,28,23,24};
