// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'mythical' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 2;
inline constexpr const char* grandleon_playstation_mesh_style_name = "mythical";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[192] = {-16,-1,0,9,-8,8,0,0,1,16,0,9,-8,8,0,0,7,20,10,22,8,14,0,1,-12,-6,9,44,-6,6,0,1,6,12,9,44,-6,6,0,1,-11,11,42,58,-9,9,1,1,-11,11,56,62,-10,10,0,0,10,29,58,64,-3,3,0,0,-29,-12,30,86,-13,-3,1,2,-23,-18,52,64,-15,-13,1,3,12,16,62,92,-6,6,0,1,-16,-12,62,92,-6,6,0,1,-12,12,60,96,-9,9,1,2,-10,10,70,88,-11,-9,1,3,18,21,64,118,-2,2,0,3,-20,-5,92,102,-7,7,0,2,5,20,92,102,-7,7,0,2,-9,9,96,102,-8,8,0,0,-8,8,98,100,-10,-7,0,3,-9,9,100,122,-9,9,0,2,-9,9,106,111,-11,-9,0,0,-19,-3,120,125,-2,4,0,3,-14,-9,118,128,-2,4,0,3,9,14,118,128,-2,4,0,3};
inline constexpr short grandleon_playstation_mesh_archer[184] = {-12,-4,0,9,-8,8,0,0,4,12,0,9,-8,8,0,0,13,27,8,20,6,12,0,1,-11,-4,9,38,-6,6,0,1,4,11,9,38,-6,6,0,1,-11,-3,36,58,-7,7,0,1,3,11,36,58,-7,7,0,1,-11,11,54,66,-8,8,1,2,-30,-26,8,120,-2,2,0,3,-31,-25,66,80,-3,3,0,0,-26,-14,70,78,-4,2,0,1,8,16,62,100,7,15,0,1,-14,-10,64,86,-6,6,0,1,10,14,64,86,-6,6,0,1,-7,7,64,94,-8,8,1,2,-3,3,64,94,-10,-8,0,0,-5,5,92,104,-8,6,0,2,9,15,98,112,8,14,0,3,-5,5,96,101,-10,-8,0,0,-6,6,102,117,-6,8,1,2,-5,5,108,112,-8,-5,0,0,-3,3,116,123,-2,8,0,3,-2,2,114,128,-2,8,0,3};
inline constexpr short grandleon_playstation_mesh_mage[152] = {-13,13,0,22,-8,8,1,1,-12,12,20,48,-7,7,1,2,-4,4,8,70,-9,-7,0,0,-15,-10,44,68,-5,5,1,1,10,15,44,68,-5,5,1,1,-11,11,46,72,-6,6,1,2,13,17,10,110,-4,0,0,1,22,29,56,66,-6,0,0,1,-9,9,70,78,-7,7,1,3,-8,8,73,75,-9,-6,0,0,-8,8,76,94,-8,4,0,2,-8,8,84,89,-10,-8,0,3,-11,11,88,110,-4,8,0,1,-13,-7,94,110,-2,4,0,3,7,13,94,110,-2,4,0,3,11,19,108,122,-6,2,0,3,-9,-4,108,128,-1,5,0,3,4,9,108,128,-1,5,0,3,4,26,115,122,-6,2,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[136] = {-10,10,0,18,-8,8,1,1,-8,8,16,56,-7,7,1,2,-3,3,4,80,-9,-7,0,0,20,24,0,112,-2,2,0,1,-30,-14,40,92,3,11,1,0,-14,-10,54,80,-5,5,1,2,10,14,54,80,-5,5,1,2,12,28,66,76,-3,3,0,1,-9,9,54,88,-7,7,1,3,-11,11,88,102,-7,6,0,2,-11,11,92,97,-9,-7,0,3,-11,11,100,118,-5,8,0,1,-15,-8,108,120,-2,4,0,3,8,15,108,120,-2,4,0,3,11,33,110,120,-6,6,0,0,12,32,118,126,-5,5,0,2,19,25,124,128,-4,4,0,3};
inline constexpr short grandleon_playstation_mesh_healer[112] = {-16,16,0,22,-8,8,0,3,-15,15,20,80,-8,8,0,3,-12,12,2,88,-10,-8,1,2,-15,15,48,54,-9,9,0,1,16,20,4,118,-3,1,0,1,13,21,60,70,-5,1,0,1,-18,-13,52,84,-6,6,0,3,13,18,52,84,-6,6,0,3,-12,12,88,104,-6,6,0,1,-13,13,98,103,-8,-6,0,0,-13,13,96,122,-5,9,0,3,-6,6,118,128,0,10,0,3,8,28,114,126,-4,2,0,3,15,21,117,123,-5,-4,1,3};
inline constexpr short grandleon_playstation_mesh_commander[200] = {-13,-5,0,9,-8,8,0,0,5,13,0,9,-8,8,0,0,-12,-5,9,42,-6,6,0,1,5,12,9,42,-6,6,0,1,-14,14,4,96,5,11,1,1,-12,-4,40,60,-7,7,0,1,4,12,40,60,-7,7,0,1,20,24,0,128,0,4,0,3,-15,15,58,68,-9,9,1,2,-15,15,66,72,-9,9,0,0,15,23,74,84,-2,4,0,1,-18,-13,68,96,-6,6,0,1,13,18,68,96,-6,6,0,1,-15,15,70,100,-9,9,0,2,-13,13,78,92,-11,-9,1,3,24,32,88,98,0,4,1,2,-19,-11,96,106,-7,7,0,2,11,19,96,106,-7,7,0,2,-13,13,100,106,-8,8,0,0,-12,12,102,104,-10,-7,0,3,19,43,96,124,0,4,1,3,-12,12,104,124,-8,8,0,1,-12,12,108,113,-10,-8,0,0,-3,3,120,128,-6,8,0,3,-10,10,123,128,-6,8,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[192] = {-12,-4,0,8,-8,8,0,0,4,12,0,8,-8,8,0,0,7,29,12,24,6,12,0,1,-11,-4,8,36,-6,6,0,1,4,11,8,36,-6,6,0,1,-11,-3,34,54,-7,7,0,1,3,11,34,54,-7,7,0,1,-11,11,52,62,-8,8,1,1,-11,11,40,92,5,11,0,0,-10,10,60,65,-9,9,0,3,-15,-11,62,82,-6,6,0,1,11,15,62,82,-6,6,0,1,-10,10,63,90,-8,8,0,1,-10,10,66,86,-10,-8,1,2,-20,-13,74,84,-8,-2,0,1,13,20,74,84,-8,-2,0,1,-8,8,88,100,-7,6,0,2,-8,8,92,96,-9,-7,0,3,-19,-14,84,110,-7,-3,0,3,14,19,84,110,-7,-3,0,3,-11,11,96,118,-4,9,0,1,-10,10,105,111,-6,-3,0,3,-3,3,114,128,2,12,0,1,-10,10,119,126,2,12,0,1};
inline constexpr short grandleon_playstation_mesh_beast[176] = {-11,-5,0,40,7,17,0,0,8,14,0,40,7,17,0,0,5,11,0,40,-17,-7,0,1,-14,-8,0,40,-17,-7,0,1,7,24,36,54,-6,6,0,1,-12,8,34,46,-16,-14,0,2,13,29,44,60,-4,4,0,1,-12,10,34,70,-14,12,0,1,20,25,56,74,-3,3,0,3,8,12,62,72,-3,3,1,3,-4,15,62,84,6,12,1,2,0,5,66,76,-3,3,1,3,-25,-6,56,88,-6,4,0,1,-8,-3,68,78,-3,3,1,3,-18,-13,58,84,-9,-6,1,3,-26,-22,82,87,-8,-4,0,3,-27,-21,86,96,-10,-2,0,1,-31,-10,84,104,-8,4,0,1,-23,-19,97,102,-10,-8,0,3,-18,-12,102,128,1,6,0,3,-18,-12,102,126,-6,-1,0,3,-25,-3,111,123,-6,-1,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {24,23,19,17,14,25,24,22};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {29,30,18,32,21,28,28,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {32,29,32,27,29,32,27,31};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {490,446,377,496,427,650,434,597};
