// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[176] = {-14,-4,0,8,-8,8,0,0,4,14,0,8,-8,8,0,0,-13,-5,8,38,-6,6,0,1,5,13,8,38,-6,6,0,1,-14,-4,36,60,-7,7,0,1,4,14,36,60,-7,7,0,1,-13,13,58,82,-9,9,1,3,-26,-8,34,98,-12,-8,0,2,-23,-11,44,88,-15,-12,1,2,-19,-15,62,76,-18,-15,0,3,-12,12,80,102,-10,10,0,1,12,24,84,94,-14,-10,0,2,-19,-11,92,104,-9,9,0,1,11,19,92,104,-9,9,0,1,20,28,96,108,-14,-10,0,2,-12,12,100,124,-10,10,0,1,-5,5,104,114,-15,-10,0,2,-2,2,105,110,-17,-15,0,0,-13,-7,118,128,0,8,0,1,7,13,118,128,0,8,0,1,22,28,106,124,-15,-10,0,3,-4,4,112,124,-14,-11,0,3};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-13,-5,0,8,-8,8,0,0,5,13,0,8,-8,8,0,0,-12,-6,8,38,-6,6,0,2,6,12,8,38,-6,6,0,2,12,26,26,36,4,12,0,2,20,28,34,54,6,14,0,2,-24,-16,8,64,-8,0,0,1,-12,-4,36,60,-7,7,0,2,4,12,36,60,-7,7,0,2,-11,11,58,90,-8,8,1,3,8,14,70,88,-10,-2,0,2,-18,-8,74,82,-12,-4,0,2,10,16,74,106,4,12,0,1,-24,-16,62,116,-8,0,0,1,-11,11,86,94,-11,-8,1,2,-9,9,92,112,-8,8,0,2,-4,4,95,104,-14,-8,0,1,-2,2,96,101,-16,-14,0,0,-10,-4,108,128,0,8,0,2,4,10,108,128,0,8,0,2};
inline constexpr short grandleon_playstation_mesh_mage[168] = {-14,14,0,18,-9,9,0,1,-19,-13,0,58,-6,2,0,1,-13,13,16,50,-9,9,0,1,-5,5,14,50,-12,-9,1,3,-18,-12,50,60,-12,-4,0,2,12,18,50,60,-12,-4,0,2,-13,13,48,74,-10,10,0,2,-5,5,48,74,-13,-10,1,3,-17,-11,56,84,-8,4,0,2,11,17,56,84,-8,4,0,2,-19,-13,56,104,-6,2,0,1,-12,12,72,94,-10,10,0,2,-5,5,72,94,-13,-10,1,3,-12,12,90,98,-14,-11,1,2,-10,10,96,118,-9,9,0,2,-5,5,100,110,-15,-9,0,1,-20,-12,102,120,-8,4,0,2,-2,2,101,106,-17,-15,0,0,-14,-8,110,124,2,10,0,1,8,14,110,124,2,10,0,1,-18,-14,118,128,-7,3,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[144] = {-15,15,0,24,-10,10,1,2,-13,13,22,52,-9,9,1,2,-6,6,22,52,-12,-9,1,3,-12,12,50,84,-9,9,0,2,-6,6,50,84,-12,-9,1,3,-26,-12,76,86,-6,4,0,2,12,26,76,86,-6,4,0,2,-32,-24,76,88,-8,2,0,2,24,32,76,88,-8,2,0,2,-32,-22,88,98,0,12,0,1,22,32,88,98,0,12,0,1,-8,8,84,90,-12,-9,1,3,-9,9,88,108,-9,9,0,2,-3,3,93,99,-13,-9,0,0,-26,-8,104,116,2,12,0,3,8,26,104,116,2,12,0,3,-30,-16,114,128,6,16,0,3,16,30,114,128,6,16,0,3};
inline constexpr short grandleon_playstation_mesh_healer[136] = {-17,17,0,18,-10,10,0,2,-9,-4,0,6,-13,-10,0,0,4,9,0,6,-13,-10,0,0,-16,16,16,48,-9,9,0,2,-5,5,16,48,-12,-9,1,3,-22,-14,20,74,-8,6,0,3,14,22,20,74,-8,6,0,3,-15,15,46,82,-9,9,0,2,-5,5,46,82,-13,-10,1,3,14,20,62,100,0,8,0,1,-15,15,82,90,-13,-6,1,2,12,22,96,112,2,12,0,1,-14,14,88,116,-10,10,0,2,-13,-3,92,110,-13,-10,0,3,3,13,92,110,-13,-10,0,3,-2,2,100,110,-15,-13,0,0,-9,9,112,128,-8,8,0,2};
inline constexpr short grandleon_playstation_mesh_commander[176] = {-13,-3,0,8,-8,8,0,1,3,13,0,8,-8,8,0,1,-12,-4,8,38,-6,6,0,1,4,12,8,38,-6,6,0,1,-18,18,4,82,8,16,1,2,-20,-14,10,82,-4,4,0,1,20,26,0,114,4,10,0,1,-14,14,54,76,-9,9,1,3,-12,12,68,76,-13,-10,0,3,-17,-12,72,94,-8,4,0,1,12,17,72,94,-8,4,0,1,-12,12,74,100,-10,10,0,1,-20,-12,80,104,-6,4,0,3,-18,-10,88,98,-11,1,0,2,10,18,88,98,-11,1,0,2,24,32,94,116,0,14,1,3,-15,15,96,120,-11,11,0,3,-8,8,100,116,-14,-11,0,1,-5,5,103,111,-17,-14,0,2,20,26,114,128,4,10,0,3,-12,-6,116,126,0,8,0,2,6,12,116,126,0,8,0,2};
inline constexpr short grandleon_playstation_mesh_rogue[176] = {-14,-6,0,10,-10,2,0,2,6,14,0,10,-10,2,0,2,14,30,14,24,4,12,0,1,-13,-7,8,32,-10,0,0,2,7,13,8,32,-10,0,0,2,24,30,22,38,6,14,0,1,-14,14,4,58,8,14,0,1,-28,-14,22,30,-18,-12,0,3,-13,-5,30,54,-8,2,0,2,5,13,30,54,-8,2,0,2,-12,12,52,62,-12,0,0,1,-11,11,60,88,-10,6,1,3,-17,-11,62,80,-14,-2,0,2,11,17,70,88,-14,-2,0,2,-5,5,66,92,-13,-10,0,3,-11,11,86,94,-13,-10,1,2,14,28,84,92,-20,-14,0,3,-9,9,92,114,-9,9,0,2,-4,4,95,104,-14,-9,0,3,-2,2,96,101,-16,-14,0,0,-9,-3,110,128,0,8,0,2,3,9,110,128,0,8,0,2};
inline constexpr short grandleon_playstation_mesh_beast[136] = {-22,-15,0,42,6,14,0,0,-1,6,0,42,6,14,0,0,-22,-15,0,42,-16,-8,0,1,-1,6,0,42,-16,-8,0,1,-25,-19,44,56,-2,6,0,1,-28,-22,48,60,0,8,1,3,-26,14,38,76,-14,12,0,1,24,34,48,64,-18,-8,0,1,16,32,44,82,-12,8,0,1,28,34,60,74,-8,-2,0,2,26,32,56,68,-20,-16,0,2,18,24,72,78,-14,-12,0,3,-24,-20,76,104,-4,4,1,3,-15,-11,76,104,-4,4,1,3,-6,-2,76,128,-4,4,1,3,3,7,76,128,-4,4,1,3,12,16,76,128,-4,4,1,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {22,20,21,18,17,22,22,17};
inline constexpr int grandleon_playstation_mesh_max_parts = 22;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {26,26,20,32,22,26,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {491,502,489,549,505,588,430,442};
