// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-16,0,0,7,-7,7,0,0,0,16,0,7,-7,7,0,0,4,17,20,32,6,14,0,0,-11,-5,7,34,-6,6,0,1,5,11,7,34,-6,6,0,1,-11,11,32,58,-8,8,1,2,-11,11,52,60,-11,-9,0,0,5,26,38,96,-14,-10,0,2,-11,11,56,92,-9,9,0,1,-16,-11,66,84,-6,4,0,1,6,25,46,88,-17,-14,1,1,13,18,60,74,-19,-17,0,3,-19,-15,74,82,-5,1,0,1,-26,-8,80,86,-5,-1,0,0,-16,-10,86,100,-8,8,0,2,10,16,86,100,-8,8,0,2,-19,-15,82,128,-5,-1,0,3,-11,11,98,122,-9,9,0,3,-3,3,100,110,-14,-9,0,3,-2,2,102,106,-16,-14,0,0,-6,-3,102,122,-12,-9,0,0,3,6,102,122,-12,-9,0,0,-11,-6,118,127,-2,6,0,0,6,11,118,127,-2,6,0,0,-19,2,120,125,-2,6,0,0};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-16,0,0,8,-9,7,0,0,0,16,0,8,-9,7,0,0,-12,-5,8,36,-6,6,0,2,5,12,8,36,-6,6,0,2,10,18,24,34,6,13,0,3,21,28,8,62,-7,-1,0,1,-13,13,34,56,-8,8,0,1,-12,12,52,59,-10,-8,0,0,-11,11,54,88,-8,8,1,3,-18,-10,70,78,-10,-3,0,2,12,19,70,88,-8,-1,0,2,-17,-9,70,104,5,13,0,1,21,28,62,120,-7,-1,0,1,-10,10,84,92,-11,-8,1,2,-8,8,90,110,-8,8,0,2,-4,4,93,102,-13,-8,0,3,-2,2,95,99,-15,-13,0,0,-13,1,108,119,-1,6,0,2,-9,-3,106,128,-1,6,0,2,3,9,106,128,-1,6,0,2};
inline constexpr short grandleon_playstation_mesh_mage[168] = {-11,12,0,16,-9,9,0,1,11,16,0,54,-5,1,0,1,-10,11,14,52,-8,8,0,1,-2,4,14,90,-12,-9,1,3,-10,11,50,58,-10,-8,1,3,-12,-7,58,84,-7,3,0,2,-9,10,56,90,-9,9,0,2,8,13,60,86,-7,1,0,2,11,16,54,110,-5,1,0,1,-9,10,84,92,-12,-9,0,3,-9,10,92,112,-8,8,0,2,-2,4,96,104,-13,-8,0,1,-1,2,97,101,-15,-13,0,0,-9,11,110,116,-9,9,0,0,5,23,106,118,-6,2,0,2,-11,-5,114,122,-2,6,0,3,6,12,114,122,-2,6,0,3,-9,10,112,114,-11,-8,0,3,-17,1,118,123,-2,6,0,3,-9,-6,120,128,-2,6,0,3,8,11,120,128,-2,6,0,3};
inline constexpr short grandleon_playstation_mesh_stormcaller[168] = {-9,9,0,20,-9,9,1,2,-14,-6,18,28,6,13,0,1,-8,8,18,54,-8,8,1,2,-5,5,18,86,-11,-8,1,3,18,24,0,116,-4,2,0,1,-7,7,50,58,-11,-8,0,0,-10,10,52,86,-8,8,0,2,-15,-9,56,84,-7,3,0,2,9,17,60,88,-7,1,0,2,-32,-24,88,96,-4,6,0,3,-10,10,84,90,-11,-8,1,3,-11,11,88,108,-8,8,0,2,-3,3,92,99,-12,-8,0,0,-26,-18,100,108,0,8,1,3,-34,-28,104,112,-2,4,0,3,-11,-5,104,116,-1,7,0,2,5,11,104,116,-1,7,0,2,-42,-20,107,112,-2,4,0,3,12,30,114,122,-7,5,0,0,13,29,120,128,-5,3,0,3,20,28,118,126,-8,-5,1,3};
inline constexpr short grandleon_playstation_mesh_healer[144] = {8,28,2,8,4,10,0,1,-12,12,0,16,-9,9,0,2,-12,12,14,52,-8,8,0,2,8,30,40,54,-6,4,0,1,8,30,52,58,-7,5,0,0,-14,14,46,54,-11,-9,1,3,15,23,56,66,-5,3,0,1,12,17,50,78,-6,2,0,2,-14,14,48,84,-9,9,1,2,-16,-9,54,80,-7,2,0,2,-9,9,84,104,-8,8,0,2,-4,4,87,95,-13,-8,0,3,-2,2,89,93,-15,-13,0,0,-10,10,96,120,-5,10,1,2,-13,-7,102,112,-3,4,0,2,7,13,102,112,-3,4,0,2,-9,9,106,112,-7,-4,0,0,-8,8,116,128,-2,8,1,2};
inline constexpr short grandleon_playstation_mesh_commander[168] = {-18,1,0,8,-8,8,0,1,-4,14,0,8,-8,8,0,1,-11,-5,8,36,-6,6,0,1,2,8,8,36,-6,6,0,1,-15,12,2,80,7,15,1,1,-14,11,34,60,-9,9,1,3,-24,-19,0,116,3,9,0,1,-14,10,56,64,-12,-9,0,3,-14,11,62,96,-9,9,0,1,-12,9,70,88,-12,-9,1,3,-38,-19,86,112,2,10,1,2,-18,-11,90,102,-9,7,0,2,8,14,90,102,-9,7,0,2,-31,-26,94,104,0,2,0,3,-14,11,100,120,-8,8,0,2,-13,9,102,110,-11,-8,0,0,-25,-18,114,126,3,9,0,3,-13,-9,114,124,-2,6,0,1,5,9,114,124,-2,6,0,1,-21,1,118,123,-2,6,0,1,-3,0,118,128,-10,6,1,3};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-13,-5,0,9,-9,3,0,2,5,13,0,9,-9,3,0,2,-29,-15,16,26,4,12,0,1,-12,-6,9,34,-9,1,0,2,6,12,9,34,-9,1,0,2,-32,-24,24,40,6,14,0,0,-12,-4,32,54,-7,3,0,2,4,12,32,54,-7,3,0,2,-12,12,52,60,-11,1,0,0,-10,10,50,92,8,14,0,1,-9,9,58,86,-9,7,1,3,-16,-10,60,82,-12,-2,0,2,10,16,60,82,-12,-2,0,2,-19,-11,78,84,-10,-6,0,0,11,19,78,84,-10,-6,0,0,-8,8,82,89,-12,-9,1,2,-39,-35,82,106,-10,-6,0,3,13,17,82,106,-10,-6,0,3,-8,8,90,110,-8,8,0,2,-9,9,92,116,-5,10,0,1,-4,4,93,101,-13,-8,0,3,-2,2,95,99,-15,-13,0,0,-7,7,112,124,0,10,0,1,-8,-3,114,128,-1,6,0,2,3,8,114,128,-1,6,0,2};
inline constexpr short grandleon_playstation_mesh_beast[128] = {11,17,0,40,7,15,0,0,-8,-2,0,40,7,15,0,0,11,17,0,40,-15,-7,0,1,-8,-2,0,40,-15,-7,0,1,14,19,42,58,-3,5,0,1,-13,17,36,74,-13,13,0,1,17,22,52,64,-1,7,0,0,-36,-14,46,62,-17,-7,0,2,-31,-7,42,80,-11,9,0,1,-27,-23,58,74,-7,-1,0,3,-26,-21,54,68,-19,-15,0,3,-20,-16,68,74,-13,-11,0,0,-18,12,73,97,-3,3,1,3,3,7,72,104,-3,3,1,3,-5,-1,72,120,-3,3,1,3,-12,-9,72,128,-3,3,1,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,20,21,21,18,21,25,16};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {26,26,20,32,22,26,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {491,502,489,549,505,588,430,442};
