// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'nature' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 3;
inline constexpr const char* grandleon_playstation_mesh_style_name = "nature";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[200] = {-16,0,0,5,-5,5,0,1,0,16,0,5,-5,5,0,1,4,17,14,22,4,10,0,0,-11,-5,5,24,-4,4,0,2,5,11,5,24,-4,4,0,2,-11,11,22,40,-6,6,1,3,-11,11,36,42,-8,-6,0,0,5,26,26,67,-10,-7,0,0,-16,-11,46,58,-4,3,1,3,-11,11,39,64,-8,4,0,2,6,25,32,61,-12,-10,0,2,13,18,42,51,-13,-12,0,0,-19,-15,51,57,-3,1,1,3,-26,-8,56,60,-3,-1,0,1,-16,-10,60,69,-6,6,0,2,10,16,60,69,-6,6,0,2,-19,-15,57,89,-3,-1,0,2,-11,11,68,85,-6,6,0,2,-3,3,69,76,-10,-6,0,3,-2,2,71,74,-11,-10,0,2,-6,-3,71,85,-8,-6,0,2,3,6,71,85,-8,-6,0,2,-11,-6,82,88,-1,4,0,0,6,11,82,88,-1,4,0,2,-19,2,83,87,-1,4,0,2};
inline constexpr short grandleon_playstation_mesh_archer[160] = {-16,0,0,6,-6,5,0,2,0,16,0,6,-6,5,0,1,-12,-5,6,25,-4,4,0,0,5,12,6,25,-4,4,0,2,10,18,17,24,4,9,0,0,21,28,6,43,-5,-1,0,2,-13,13,24,39,-6,6,0,2,-12,12,36,41,-7,-6,0,2,-11,11,38,62,-6,6,0,2,-18,-10,49,55,-7,-2,0,2,-17,-9,49,73,4,9,0,2,12,19,49,62,-6,-1,0,1,21,28,43,84,-5,-1,0,1,-10,10,59,65,-8,-6,0,2,-8,8,63,77,-6,6,0,3,-4,4,65,72,-9,-6,0,2,-2,2,67,69,-11,-9,1,3,-13,1,76,83,-1,4,0,2,-9,-3,74,90,-1,4,0,2,3,9,74,90,-1,4,0,2};
inline constexpr short grandleon_playstation_mesh_mage[160] = {-11,12,0,12,-7,7,0,1,11,16,0,39,-4,1,0,2,-10,11,10,38,-6,6,0,2,-2,4,10,65,-9,-7,0,2,-10,11,36,42,-7,-6,0,2,-12,-7,42,61,-5,2,0,0,-9,10,41,65,-7,7,0,2,8,13,44,63,-5,1,1,3,11,16,39,80,-4,1,0,2,-9,10,61,67,-9,-7,1,3,-9,10,67,81,-6,6,0,2,-2,4,70,76,-9,-6,0,2,-1,2,71,73,-11,-9,0,2,-9,11,80,84,-7,7,0,2,5,23,77,86,-4,1,0,2,-11,-5,83,89,-1,4,0,3,6,12,83,89,-1,4,0,2,-17,1,86,89,-1,4,0,0,-9,-6,87,93,-1,4,0,2,8,11,87,93,-1,4,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[168] = {-9,9,0,15,-7,7,1,2,-14,-6,14,21,5,10,1,3,-8,8,14,41,-6,6,1,2,-5,5,14,65,-8,-6,1,3,18,24,0,87,-3,2,0,0,-7,7,38,44,-8,-6,1,3,-10,10,39,65,-6,6,1,3,-15,-9,42,63,-5,2,0,2,9,17,45,66,-5,1,0,2,-32,-24,66,72,-3,5,0,1,-10,10,63,68,-8,-6,0,2,-11,11,66,81,-6,6,0,2,-26,-18,75,81,0,6,0,2,-3,3,69,75,-9,-6,0,2,-34,-28,78,84,-2,3,0,0,-11,-5,78,87,-1,5,0,0,5,11,78,87,-1,5,0,3,-42,-20,81,84,-2,3,0,2,12,30,86,92,-5,4,0,1,13,29,90,96,-4,2,0,2,20,28,89,95,-6,-4,0,0};
inline constexpr short grandleon_playstation_mesh_healer[144] = {8,28,1,5,3,7,0,3,-12,12,0,11,-6,6,0,2,-12,12,9,34,-5,5,0,2,8,30,26,36,-4,3,0,3,8,30,34,38,-5,3,0,3,-14,14,30,36,-7,-6,0,3,15,23,37,44,-3,2,0,3,12,17,33,52,-4,1,0,3,-14,14,32,55,-8,4,0,3,-16,-9,36,53,-5,1,0,3,-9,9,55,69,-5,5,0,3,-4,4,57,63,-9,-5,0,3,-2,2,59,61,-10,-9,1,3,-10,10,63,79,-3,7,0,3,-13,-7,67,74,-2,3,0,2,7,13,67,74,-2,3,0,3,-7,7,70,74,-7,-5,0,3,-8,8,77,85,-1,5,0,3};
inline constexpr short grandleon_playstation_mesh_commander[168] = {-18,1,0,6,-6,6,0,1,-4,14,0,6,-6,6,0,0,-11,-5,6,26,-4,4,1,2,2,8,6,26,-4,4,0,1,-15,12,1,58,5,11,0,2,-14,11,24,43,-6,6,0,1,-24,-19,0,84,2,6,0,2,-14,10,40,46,-9,-6,0,1,-14,11,45,69,-6,6,0,2,-12,9,50,63,-9,-6,0,2,-38,-19,62,81,1,7,0,3,-18,-11,65,73,-6,5,0,2,8,14,65,73,-6,5,0,0,-31,-26,68,75,0,1,0,0,-14,11,72,86,-6,6,0,2,-13,9,73,79,-8,-6,0,1,-25,-18,82,91,2,6,0,0,-13,-9,82,89,-1,4,0,1,5,9,82,89,-1,4,1,3,-21,1,85,89,-1,4,0,3,-3,0,85,92,-7,4,0,1};
inline constexpr short grandleon_playstation_mesh_rogue[200] = {-13,-5,0,5,-5,2,0,0,5,13,0,5,-5,2,0,1,-29,-15,9,15,2,7,1,2,-12,-6,5,19,-5,1,0,1,6,12,5,19,-5,1,0,0,-32,-24,13,22,3,8,0,2,-12,-4,18,30,-4,2,1,2,4,12,18,30,-4,2,0,2,-12,12,29,34,-6,1,0,1,-10,10,28,52,4,8,0,2,-9,9,33,48,-5,4,0,1,-16,-10,34,46,-7,-1,0,3,10,16,34,46,-7,-1,0,2,-19,-11,44,47,-6,-3,0,2,11,19,44,47,-6,-3,0,0,-8,8,46,50,-7,-5,0,2,-39,-35,46,59,-6,-3,0,3,13,17,46,59,-6,-3,0,0,-8,8,50,62,-4,4,0,1,-9,9,52,65,-3,6,0,2,-4,4,52,57,-7,-4,0,2,-2,2,53,56,-8,-7,0,2,-7,7,63,70,0,6,0,0,-8,-3,64,72,-1,3,0,2,3,8,64,72,-1,3,0,0};
inline constexpr short grandleon_playstation_mesh_beast[128] = {11,17,0,19,3,7,0,0,-8,-2,0,19,3,7,0,0,11,17,0,19,-7,-3,0,1,-8,-2,0,19,-7,-3,0,1,14,19,20,28,-1,2,0,1,-13,17,17,35,-6,6,0,2,17,22,25,31,0,3,0,2,-36,-14,22,30,-8,-3,0,2,-31,-7,20,38,-5,4,0,1,-27,-23,28,35,-3,0,0,2,-26,-21,26,32,-9,-7,0,1,-20,-16,32,35,-6,-5,0,2,-18,12,35,46,-1,1,0,2,3,7,34,50,-1,1,0,2,-5,-1,34,57,-1,1,1,3,-12,-9,34,61,-1,1,0,1};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {25,20,20,21,18,21,25,16};
inline constexpr int grandleon_playstation_mesh_max_parts = 25;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {26,26,20,32,22,26,28,29};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {30,31,32,32,30,32,26,23};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {491,502,489,549,505,588,430,442};
// The figure's own height, above the faction disc: what rule 1 builds a mesh to be
// drawn, as opposed to the cell height above, which counts the four rows of ground
// a unit stands on.
inline constexpr int grandleon_playstation_mesh_silhouette_figure_height[8] = {26,27,28,28,26,28,22,19};
