// Generated by tools/placeholder_art/generate.py from placeholder_art/playstation_header.py.
// Do not edit.
//
// The character meshes of the 'sengoku' style: each archetype as a short list of
// convex axis-aligned boxes, in the figure's own space -- x right, y up, z away,
// origin at the centre of the feet -- built 128 world units tall, which is
// unit_world / cos(60) and not unit_world, because a world-vertical extent is
// drawn focal*H*cos(pitch)/depth pixels tall.
//
// A part is eight values: x0,x1,y0,y1,z0,z1,ramp,rung. There is no colour here and
// there is nowhere for one to be -- a face names a ramp and a rung and the drawing
// resolves it from the faction's own CLUT, which is what keeps all six faction
// recolourings free. Parts are authored far-to-near at the shipped pitch, which is
// what buys the scene freedom from a depth buffer.
//
// The silhouette rows are measured, not authored: they are the opaque box of each
// archetype's own sprite, in texels of its 32x32 cell, read from the very arrays
// playstation_characters_<style>.h sends to VRAM.
#pragma once
// Which entry of grandleon_playstation_style_names these meshes belong to.
inline constexpr int grandleon_playstation_mesh_style = 4;
inline constexpr const char* grandleon_playstation_mesh_style_name = "sengoku";
// Whether this style has a mesh commission at all. A style without one is still a
// complete style: a mesh is an additional drawing of an archetype, not a cell of
// the animation sequence every style is required to ship.
inline constexpr bool grandleon_playstation_mesh_commissioned = true;
inline constexpr int grandleon_playstation_mesh_values_per_part = 8;
inline constexpr int grandleon_playstation_mesh_world_height = 128;
inline constexpr int grandleon_playstation_mesh_pitch_degrees = 60;
inline constexpr int grandleon_playstation_mesh_unit_world = 64;
inline constexpr int grandleon_playstation_mesh_ramp_neutral = 0;
inline constexpr int grandleon_playstation_mesh_ramp_faction = 1;
inline constexpr int grandleon_playstation_mesh_ramp_count = 2;
inline constexpr int grandleon_playstation_mesh_rung_count = 4;
inline constexpr int grandleon_playstation_mesh_faces_per_part = 6;
inline constexpr int grandleon_playstation_mesh_vertices_per_part = 8;
inline constexpr short grandleon_playstation_mesh_knight[128] = {-16,-6,0,8,-8,8,0,1,6,16,0,8,-8,8,0,1,-14,-6,8,44,-6,6,0,1,6,14,8,44,-6,6,0,1,-17,17,42,62,-9,9,1,1,-13,13,60,100,-9,9,1,2,-32,22,74,80,-16,-10,0,2,22,33,79,87,-16,-10,0,3,-24,-13,84,104,-8,8,0,1,13,24,84,104,-8,8,0,1,-13,13,88,94,-12,-10,1,3,-14,14,94,106,-6,8,0,1,-24,-13,104,108,-8,8,1,3,13,24,104,108,-8,8,1,3,-9,9,96,116,-12,-2,0,3,-11,11,110,128,-8,8,0,0};
inline constexpr short grandleon_playstation_mesh_archer[128] = {-13,-4,0,8,-8,8,0,1,4,13,0,8,-8,8,0,1,-12,-5,8,44,-6,6,1,1,5,12,8,44,-6,6,1,1,-22,-18,24,58,2,8,0,1,-14,14,42,58,-8,8,1,1,13,19,60,92,6,12,0,1,-16,-12,60,84,-6,6,1,1,12,16,60,84,-6,6,1,1,-12,12,56,94,-8,8,1,2,-12,12,72,78,-11,-9,1,3,-27,-20,56,128,2,8,0,1,13,19,92,104,8,14,0,3,-8,8,88,108,-12,-2,0,1,-15,15,104,109,-8,8,0,2,-7,7,109,116,-6,6,0,2};
inline constexpr short grandleon_playstation_mesh_mage[112] = {-14,14,0,58,-8,8,1,1,-4,4,4,58,-11,-8,1,3,-16,-11,46,54,-9,-3,0,2,11,16,46,54,-9,-3,0,2,-16,-11,52,76,-6,6,1,1,11,16,52,76,-6,6,1,1,-11,11,56,94,-7,7,1,2,14,19,46,110,2,8,0,1,-4,4,58,94,-10,-7,1,3,-12,12,90,94,-11,-8,0,3,19,26,92,114,4,10,0,3,-8,8,92,112,-12,-2,0,2,-6,6,106,110,-7,-5,0,3,-4,4,106,128,-5,2,0,0};
inline constexpr short grandleon_playstation_mesh_stormcaller[128] = {-20,20,0,26,-10,10,1,1,-18,18,24,58,-9,9,1,2,-31,-21,34,58,-6,6,0,3,21,31,42,66,-6,6,0,3,-24,-16,50,74,-6,6,0,3,16,24,52,76,-6,6,0,3,-14,14,58,66,-11,-9,1,3,-11,11,60,96,-8,8,0,3,19,25,78,104,-6,2,0,3,20,26,102,108,-6,0,0,2,-12,-8,98,116,-6,4,0,0,8,12,98,116,-6,4,0,0,22,32,106,120,2,10,0,1,-8,8,98,114,-12,-2,0,2,-9,9,112,116,-9,-7,1,3,-11,11,114,128,-6,8,0,0};
inline constexpr short grandleon_playstation_mesh_healer[128] = {-13,13,0,30,-8,8,0,3,-15,15,28,58,-8,8,0,3,-21,-15,50,58,-9,-3,0,2,15,21,50,58,-9,-3,0,2,-22,-16,20,112,0,6,0,1,-16,16,56,78,-8,8,0,3,-20,-15,60,84,-6,6,0,3,15,20,60,84,-6,6,0,3,-4,16,58,78,-11,-8,1,2,-18,18,76,96,-9,9,0,3,-16,4,78,96,-12,-9,1,2,-15,15,88,94,-12,-9,1,3,-24,-19,96,110,0,4,0,3,-9,9,94,118,-12,0,0,2,-7,7,106,108,-14,-12,0,0,-26,-14,110,128,2,8,0,3};
inline constexpr short grandleon_playstation_mesh_commander[144] = {-14,-5,0,8,-8,8,0,1,5,14,0,8,-8,8,0,1,-12,-5,8,40,-6,6,0,1,5,12,8,40,-6,6,0,1,-20,20,18,52,-9,9,1,1,-26,-12,34,40,-12,-8,0,3,-18,18,50,74,-8,8,1,2,8,13,60,106,10,16,0,1,-13,13,66,102,-9,9,0,0,-13,13,78,84,-12,-10,1,3,-21,-13,84,98,-8,6,0,1,13,21,84,98,-8,6,0,1,-13,13,104,120,10,26,1,2,-14,14,98,110,-6,10,0,0,-4,4,118,122,12,20,0,3,-9,9,98,116,-12,-2,0,2,-11,11,110,128,-8,8,0,0,-9,9,116,126,-12,-9,0,3};
inline constexpr short grandleon_playstation_mesh_rogue[136] = {-24,-14,0,36,-8,4,0,1,14,24,0,36,-8,4,0,1,-26,-13,26,34,-16,-10,0,2,-21,-12,34,56,-8,4,0,1,12,21,34,56,-8,4,0,1,-15,15,32,58,-12,-4,0,0,-14,14,54,62,-14,-6,1,3,-19,-13,60,80,-10,0,0,1,13,19,60,80,-10,0,0,1,-13,13,58,88,-10,6,0,1,-11,11,60,86,-14,-10,0,0,-11,11,86,94,-12,4,0,2,12,22,90,97,-18,-12,0,3,-11,11,92,116,-8,6,0,1,-10,10,100,106,-10,-8,1,3,20,28,96,108,-18,-12,1,3,-8,8,112,128,-4,8,0,1};
inline constexpr short grandleon_playstation_mesh_beast[120] = {-18,-10,0,44,4,12,0,0,6,14,0,44,4,12,0,0,-14,-6,0,44,-14,-6,0,1,10,18,0,44,-14,-6,0,1,-20,20,40,76,-14,10,0,1,14,24,46,72,-12,4,0,1,-24,-12,48,80,0,8,0,1,16,28,48,64,-16,-10,1,3,26,36,60,70,-18,-12,0,3,19,34,62,80,-12,2,0,2,-14,14,72,78,-10,8,1,2,19,24,78,94,0,6,0,2,29,34,78,94,0,6,0,2,-27,-19,76,108,2,10,0,2,-29,-23,106,128,4,12,0,3};
// One row per archetype, in the roster's order; a null row is an archetype this
// style has no mesh for, and its part count is zero.
inline constexpr const short* grandleon_playstation_mesh_parts[8] = {grandleon_playstation_mesh_knight,grandleon_playstation_mesh_archer,grandleon_playstation_mesh_mage,grandleon_playstation_mesh_stormcaller,grandleon_playstation_mesh_healer,grandleon_playstation_mesh_commander,grandleon_playstation_mesh_rogue,grandleon_playstation_mesh_beast};
inline constexpr int grandleon_playstation_mesh_part_count[8] = {16,16,14,16,16,18,17,15};
inline constexpr int grandleon_playstation_mesh_max_parts = 18;
// The silhouette each archetype's mesh is held to: the opaque box of its own
// sprite, in texels of the cell, measured on faction colour zero -- every faction
// recolours inside the same silhouette. Present for every archetype, including the
// ones with no mesh, because the measurement is of the sprite and not of the mesh.
inline constexpr int grandleon_playstation_mesh_silhouette_width[8] = {32,21,19,31,23,22,25,30};
inline constexpr int grandleon_playstation_mesh_silhouette_height[8] = {29,32,32,30,30,32,28,28};
inline constexpr int grandleon_playstation_mesh_silhouette_area[8] = {483,490,393,524,489,518,369,476};
