// Generated by tools/placeholder_art/generate.py from placeholder_art/styles.py.
// Do not edit.
#pragma once
inline constexpr int grandleon_character_style_count = 7;
inline constexpr const char* grandleon_character_style_names[] = {"medieval","scifi","mythical","nature","sengoku","undead","pirates"};
// The archetype roster, shared by every style and closed at this length: a
// ninth would cost one draw routine in every style, forever. A style may not
// add, remove or rename one.
inline constexpr int grandleon_archetype_count = 8;
inline constexpr const char* grandleon_archetype_names[] = {"knight","archer","mage","stormcaller","healer","commander","rogue","beast"};
// The bodies a role can be drawn with, in the order every client indexes
// them by (placeholder_art/figures.py). Appended to, never inserted into:
// the first entry is the sprite that shipped before figures existed.
inline constexpr int grandleon_character_figure_count = 2;
inline constexpr const char* grandleon_character_figure_names[] = {"first","second"};
