// Generated by tools/placeholder_art/generate.py from placeholder_art/themes.py.
// Do not edit.
#pragma once
inline constexpr int grandleon_theme_count = 4;
inline constexpr const char* grandleon_theme_names[] = {"temperate","autumn","winter","ashland"};
inline constexpr int grandleon_terrain_kind_count = 13;
// Terrain kinds in keyword match order, with the keywords an authored terrain
// name may contain to select each one. The first match wins.
inline constexpr const char* grandleon_terrain_kind_names[] = {"water","road","forest","mountain","sand","snow","swamp","hills","ruins","grass","farmland","bamboo","paved"};
inline constexpr int grandleon_terrain_keyword_count = 2;
inline constexpr const char* grandleon_terrain_keywords[][2] = {{"water","river"},{"bridge","road"},{"forest","wood"},{"mountain","rock"},{"sand","desert"},{"snow","ice"},{"swamp","marsh"},{"hill","highland"},{"ruin","rubble"},{"grass","plain"},{"farm","field"},{"bamboo","thicket"},{"pave","cobble"}};
// How many levels above the valley floor each terrain kind reads as. A client
// draws the cell's art lifted by this many steps and changes nothing else:
// presentation only, never state, never hashed. A client that
// ignores it draws the flat board.
inline constexpr unsigned char grandleon_terrain_elevation[13] = {0,0,0,2,0,0,0,1,0,0,0,0,0};
// The flat colour each terrain kind is drawn in, per theme: what a client
// paints when it is painting cells rather than tiles.
inline constexpr unsigned char grandleon_terrain_flat[4][13][3] = {{{49,130,164},{168,135,83},{39,97,58},{117,105,93},{212,184,107},{220,235,238},{101,115,59},{98,168,82},{148,135,121},{77,145,71},{125,100,64},{131,194,104},{91,81,69}},{{49,130,164},{168,135,83},{126,59,27},{117,105,93},{212,184,107},{220,235,238},{101,115,59},{168,164,66},{148,135,121},{134,139,51},{125,100,64},{198,190,106},{91,81,69}},{{118,170,192},{168,135,83},{32,79,76},{117,105,93},{212,184,107},{220,235,238},{101,115,59},{176,192,182},{148,135,121},{146,164,153},{125,100,64},{210,222,214},{91,81,69}},{{78,110,92},{168,135,83},{60,48,40},{117,105,93},{142,139,136},{220,235,238},{101,115,59},{103,109,91},{148,135,121},{80,87,74},{125,100,64},{130,135,113},{91,81,69}}};
// Master palette index to the index a theme paints in its place, for a client
// holding art in master-palette indices. The default theme is the identity.
inline constexpr unsigned char grandleon_theme_palette[4][124] = {{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123},{0,1,2,3,4,80,81,82,83,84,85,86,87,88,89,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123},{0,1,2,3,4,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123},{0,1,2,3,4,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123}};
// Animated water, presentation-side only (placeholder_art/shimmer.py). These are
// addresses a client rotates in the palette it loaded, dark to light; the
// master palette above is unpermuted and every asset byte is what it always
// was. The phase is timing and lives in view/motion.hpp.
inline constexpr int grandleon_water_cycle_entries = 4;
// Master palette indices, for a client holding art in them.
inline constexpr unsigned char grandleon_water_cycle_master[4][4] = {{16,17,18,19},{16,17,18,19},{101,102,103,104},{116,117,118,119}};
// Slots in the water base sheet's own palette, for a client whose hardware
// holds one lookup table per texture — the Nintendo 64's CI4 TLUT.
inline constexpr unsigned char grandleon_water_cycle_tlut[4][4] = {{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
