# SPDX-License-Identifier: MIT
"""The sprite set as a C++ header, for clients that embed their art.

The desktop SDL presenter includes this the same way the Nintendo 64 title
screen includes ``logo.h``: master-palette indices plus the palette itself,
compiled straight into the binary. That keeps the client free of an image
decoder and a runtime asset path, and it keeps the art single-sourced: a client
cannot drift from the generator because both are this module's output.

What it carries is the native 32-pixel content of the ``modern`` profile: one
47-variant blob sheet per terrain, every character sprite, and the 256-entry
``mask_to_variant`` autotile lookup, so an embedding client applies the same
convention the manifests describe without re-deriving it.
"""

from __future__ import annotations

from typing import List, Sequence

from . import autotile, palette
from .characters import FACTION_COLOURS
from .raster import Canvas
from .terrain import TILE


def _array(values: Sequence[int]) -> str:
    return ",".join(str(value) for value in values)


def _blocks(canvases: Sequence[Canvas]) -> str:
    return ",".join("{%s}" % _array(canvas.data) for canvas in canvases)


def _names(names: Sequence[str]) -> str:
    return ",".join('"%s"' % name for name in names)


def emit(
    terrain_names: Sequence[str],
    terrain_blobs: Sequence[Canvas],
    character_names: Sequence[str],
    character_sprites: Sequence[Canvas],
    shadow: Canvas,
) -> str:
    """The header text. Inputs are parallel name/canvas sequences."""
    blob_rows = terrain_blobs[0].height // TILE
    lines: List[str] = [
        "// Generated by tools/placeholder_art/generate.py from"
        " placeholder_art/sprites_header.py.",
        "// Do not edit.",
        "#pragma once",
        f"inline constexpr int grandleon_sprites_tile = {TILE};",
        "inline constexpr unsigned char grandleon_sprites_transparent = "
        f"{palette.TRANSPARENT};",
        "inline constexpr unsigned char grandleon_sprites_palette[][3] = {"
        + ",".join("{%d,%d,%d}" % colour for colour in palette.RGB) + "};",
        "inline constexpr unsigned char grandleon_sprites_mask_to_variant[256]"
        " = {" + _array(autotile.MASK_TO_VARIANT) + "};",
        "inline constexpr int grandleon_sprites_blob_columns = "
        f"{terrain_blobs[0].width // TILE};",
        f"inline constexpr int grandleon_sprites_blob_rows = {blob_rows};",
        "inline constexpr int grandleon_sprites_terrain_count = "
        f"{len(terrain_names)};",
        "inline constexpr const char* grandleon_sprites_terrain_names[] = {"
        + _names(terrain_names) + "};",
        "inline constexpr unsigned char grandleon_sprites_terrain_blobs"
        f"[{len(terrain_blobs)}][{terrain_blobs[0].width * terrain_blobs[0].height}]"
        " = {" + _blocks(terrain_blobs) + "};",
        # A faction colour's palette rows, padded with the transparent index,
        # which no rendered pixel can carry. A probe that scans for these
        # indices' colours finds a faction sprite without knowing its shape.
        "inline constexpr int grandleon_sprites_faction_count = "
        f"{len(FACTION_COLOURS)};",
        "inline constexpr const char* grandleon_sprites_faction_names[] = {"
        + _names([colour.name for colour in FACTION_COLOURS]) + "};",
        "inline constexpr int grandleon_sprites_faction_ramp_length = "
        f"{max(len(colour.colours) for colour in FACTION_COLOURS)};",
        "inline constexpr unsigned char grandleon_sprites_faction_ramps"
        f"[{len(FACTION_COLOURS)}]"
        f"[{max(len(colour.colours) for colour in FACTION_COLOURS)}] = {{"
        + ",".join(
            "{%s}" % _array(
                list(colour.colours)
                + [palette.TRANSPARENT]
                * (
                    max(len(c.colours) for c in FACTION_COLOURS)
                    - len(colour.colours)
                )
            )
            for colour in FACTION_COLOURS
        ) + "};",
        "inline constexpr int grandleon_sprites_character_count = "
        f"{len(character_names)};",
        "inline constexpr const char* grandleon_sprites_character_names[] = {"
        + _names(character_names) + "};",
        "inline constexpr unsigned char grandleon_sprites_characters"
        f"[{len(character_sprites)}][{TILE * TILE}] = {{"
        + _blocks(character_sprites) + "};",
        # The drop shadow every unit stands on, on the same grid as the
        # characters so it lines up with their feet without any offset of the
        # renderer's own.
        "inline constexpr unsigned char grandleon_sprites_shadow"
        f"[{TILE * TILE}] = {{" + _array(shadow.data) + "};",
    ]
    return "\n".join(lines) + "\n"
